### ISSUE TITLE
SyntaxError: invalid syntax with run_windows.bat

### ISSUE THREAD

**Issue by flo-rider** [alievk/avatarify#100]
Microsoft Windows [Version 10.0.18363.778]
(c) 2019 Microsoft Corporation. All rights reserved.

C:\Users\MyUsername>cd C:\Users\MyUsername\avatarify

C:\Users\MyUsername\avatarify>run_windows.bat

C:\Users\MyUsername\avatarify>REM Web-camera device id

C:\Users\MyUsername\avatarify>set CAMID=0

C:\Users\MyUsername\avatarify>REM ################################################

C:\Users\MyUsername\avatarify>REM Normally you don't want to change settings below

C:\Users\MyUsername\avatarify>REM Conda environment name

C:\Users\MyUsername\avatarify>set CONDA_ENV_NAME=avatarify
'conda' is not recognized as an internal or external command,
operable program or batch file.
  File "cam_fomm.py", line 37
    generator = OcclusionAwareGenerator(**config['model_params']['generator_params'],
                                                                                    ^
SyntaxError: invalid syntax

C:\Users\MyUsername\avatarify>

**Comment by E3V3A** [comment]
@flo-rider 
It seem you didn't install conda and if you did, you didn't run it from the conda "shell", like said in README. Open windows "run" and search for the *conda prompt* and try again. 

PS. To paste shell text in github, use triple back-ticks (`\``) at start and end on its own line.

**Comment by flo-rider** [comment]
Hmm, I performed these steps:
![image](https://user-images.githubusercontent.com/7127039/79895434-2c3c2c80-8407-11ea-930f-d1ff5e43fde7.png)

Also I have everything installed in C:\ProgramData\Miniconda3, so looks like I did take the right steps? Or are you referring to something else?

**Comment by E3V3A** [comment]
>  I have everything installed in C:\ProgramData\Miniconda3

No that is not right. try to re-install. Make sure you get the `Anaconda Prompt` icon on your desktop after.

**Comment by flo-rider** [comment]
Ok, did that, apparently I DID have to select "ADD TO PATH", even though the installer did not recommend that.
Now I see 2 windows: 1 cam and 1 with einstein :-)
However, for me there's no option to select "[python.exe]: avatarify". See screenshot:
![image](https://user-images.githubusercontent.com/7127039/79914841-36b9ee80-8426-11ea-97db-1697aaa0cfc7.png)


Also, minor typo "Windows" should be "Window":
![image](https://user-images.githubusercontent.com/7127039/79914880-476a6480-8426-11ea-8d66-4b62e6aa5101.png)

**Comment by E3V3A** [comment]
Did you install the obs-virtual-cam correctly? (I had trouble with that.)
But then it just worked. (make sure to run OBS Studio once **before** installing the cam plugin.)

**Comment by flo-rider** [comment]
I started OBS. Closed OBS, then installed the plugin, then started OBS again, still no  "[python.exe]: avatarify" option appears
I then started OBS, tried installing the plugin, the installer notifies of a running OBS instance which I need to close, so I let the installer do that, install the plugin, start OBS, but still that option is not there.
What else can I try? Is there perhaps a config file I can change?

**Comment by flo-rider** [comment]
@E3V3A What else could I try? I was hoping to impress my colleagues next week :)

**Comment by alievk** [comment]
@flo-rider is Avatarify running when you open OBS studio?

**Comment by flo-rider** [comment]
@alievk yes, it is

**Comment by E3V3A** [comment]
I had something similar happen to me yesterday. 
I don't recall what I did, but it kind of fixed itself... :grimacing: 

I think I has to use the 32-bit OSB Studio, because the 64-bit one would not show the `Virtual Cam` option under the `Tool` menu. I have no idea why. Try that.

**Comment by flo-rider** [comment]
@E3V3A 
Uninstalled 64bit, reinstalled 32bit and OBS-VirtualCam2.0.4-Installer, started OBS, still no "[python.exe]: avatarify" option appears. Is there no way to get that option by manipulating the registry or something?

**Comment by nt314p** [comment]
When the "Create/Select Source" window in OBS pops up, click OK.

**Comment by JohanAR** [comment]
Since we haven't heard anything from @flo-rider for almost a year I'm going to assume they either solved their problem or moved on to other things. If there still is something that points to a bug in Avatarify, feel free to re-open the issue or create a new one.
