### ISSUE TITLE
Could this be integrated into Google Colab for more accessibility?

### ISSUE THREAD

**Issue by SpectrixOfficial** [alievk/avatarify#102]
Google Colab can use webcams, and I was wondering out of curiosity if it was possible (I am not requesting this, just wondering) to integrate this project, since it would allow more accessibility for those without CUDA or powerful machines. Are there limitations? 
Thanks.

**Comment by alievk** [comment]
Maybe @karfly may comment here

**Comment by alievk** [comment]
Yes!
[Google Colab](https://colab.research.google.com/github/alievk/avatarify/blob/master/avatarify.ipynb)

**Comment by SpectrixOfficial** [comment]
Thanks! This is awesome lol
