### ISSUE TITLE
Installation : Error on window

### ISSUE THREAD

**Issue by Xamamule** [alievk/avatarify#106]
I am trying to install Avatarify under window. When running the script I got this error:

ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'fomm/requirements.txt'

![image](https://user-images.githubusercontent.com/5912646/79951059-5417a880-8478-11ea-9335-fb14f666fd2a.png)

Can you help me ?

thank you .

**Comment by 1271** [comment]
Try:

`git clone --recursive https://github.com/alievk/avatarify.git`

After:

`pip install -r fomm/requirements.txt`

**Comment by Xamamule** [comment]
Yes install is done.

But when I run the following script run_windows.bat 
I get this error message: 

![image](https://user-images.githubusercontent.com/5912646/79955326-f2a70800-847e-11ea-96b7-6792ad7c08da.png)

Any idea?

**Comment by 1271** [comment]
I can’t help you with this. This works for me.

Try to run this manually:

cmd: python

>>> from PIL import PILLOW_VERSION
>>> PILLOW_VERSION

It's worked?

**Comment by fishhead1982** [comment]
Hi, not OP but getting the same error. 

Your suggestion didn't work for me unfortunately.

![image](https://user-images.githubusercontent.com/64136470/79971594-daafa280-84d7-11ea-8ebd-0cb4d654117d.png)

**Comment by 1271** [comment]
Ok

```
import PIL
```

??

**Comment by 1271** [comment]
And... Please, show this:

```
python -mpip freeze
```

**Comment by fishhead1982** [comment]
It had an error as well, sorry I didn't grab that at the time.

I moved the install to the users folder after seeing a few posts suggesting that was the way to do it and this is the result:

![image](https://user-images.githubusercontent.com/64136470/79973031-311de080-84da-11ea-8440-42dad5cf2923.png)

As requested:

```
(avatarify) c:\Users\fishh\avatarify>python -mpip freeze
certifi==2020.4.5.1
chardet==3.0.4
cloudpickle==1.3.0
cycler==0.10.0
cytoolz==0.10.1
dask==2.14.0
decorator==4.4.2
face-alignment==1.0.1
future==0.18.2
idna==2.9
imageio==2.8.0
joblib==0.14.1
kiwisolver==1.0.1
matplotlib==3.1.3
mkl-fft==1.0.15
mkl-random==1.1.0
mkl-service==2.3.0
networkx==2.4
numpy==1.18.1
olefile==0.46
opencv-python==4.2.0.34
pandas==1.0.3
Pillow==7.0.0
pycparser==2.20
pygit==0.1
pyparsing==2.4.6
python-dateutil==2.8.1
pytz==2019.3
PyWavelets==1.1.1
PyYAML==5.3.1
requests==2.23.0
scikit-image==0.16.2
scikit-learn==0.22.2.post1
scipy==1.4.1
sip==4.19.13
six==1.14.0
toolz==0.10.0
torch==1.5.0
torchvision==0.2.2
tornado==6.0.4
tqdm==4.45.0
urllib3==1.25.9
wincertstore==0.2
```

**Comment by 1271** [comment]
Please, try PIL, not pil

**Comment by 1271** [comment]
Oh. Sorry, I didn't pay attention.
Please follow the instructions.

You are using python 3.8 when readme explicitly says “Install miniconda 3.7”

https://github.com/alievk/avatarify#windows

**Comment by Xamamule** [comment]
the latest miniconda version which is 3.7 install python 3.8

**Comment by fishhead1982** [comment]
Ah yes, I see that now. I just tried uninstalling and installing the 3.7 but I got a different error so I will reinstall most of the stuff again and see how I go.

**Comment by 1271** [comment]
@Xamamule Try it file:

https://repo.anaconda.com/miniconda/Miniconda3-py37_4.8.2-Windows-x86_64.exe

**Comment by fishhead1982** [comment]
Thanks heaps @1271 and @Xamamule it is working now.

It's not quite usable yet though, it isn't matching mouth movements for instance, but we're early days; I look forward to the improvements :)

**Comment by alievk** [comment]
Package versions are fixed (including pillow) in the latest update. Refer to https://github.com/alievk/avatarify/issues/107

**Comment by Xamamule** [comment]
Perfect ! works for me now
Thank you.

**Comment by E3V3A** [comment]
I just want to say that I'm using miniconda *3.7) but using 3.8 in avitarify env on Win8 and it works fine...

**Comment by Brown241** [comment]
![IMG_20241028_161120](https://github.com/user-attachments/assets/109ead8e-bde7-41c6-8838-73335204a580)

**Comment by Brown241** [comment]
It's showing me (avatarify) c: \windows\system32> 
Can someone help me out 😞😭
