### ISSUE TITLE
Error Mac when 'bash run_mac.sh'

### ISSUE THREAD

**Issue by HatimLs** [alievk/avatarify#108]
[ERROR:0] global /Users/travis/build/skvark/opencv-python/opencv/modules/videoio/src/cap.cpp (193) open VIDEOIO(AVFOUNDATION): raised unknown C++ exception!

Traceback (most recent call last):
  File "cam_fomm.py", line 223, in <module>
    cap = VideoCaptureAsync(opt.cam)
  File "/Users/hatimlassouli/Documents/avatarify/videocaptureasync.py", line 17, in __init__
    raise RuntimeError("Cannot open camera. Try to choose other CAMID in './scripts/settings.sh'")
RuntimeError: Cannot open camera. Try to choose other CAMID in './scripts/settings.sh'

**Comment by jeremybdk** [comment]
Try editing scrips/settings.sh and changing the CAMID, mine had to be changed from 0 to 2 to work, try 1 or 2 it should fix the issue

**Comment by HatimLs** [comment]
Thanks, it's works 👯

**Comment by HatimLs** [comment]
@jeremybdk I have a message from Manycam but it is software that I no longer use and that I have deleted. U know how can I change the source?
<img width="825" alt="Capture d’écran 2020-04-23 à 12 23 30" src="https://user-images.githubusercontent.com/25247819/80088906-71727280-855d-11ea-8792-1c68fa327e11.png">

**Comment by E3V3A** [comment]
New question, new issue. Please close this one if it helped you resolve.
