### ISSUE TITLE
Windows ModuleNotFoundError: No module named 'yaml'

### ISSUE THREAD

**Issue by AptemCat** [alievk/avatarify#110]
Traceback (most recent call last):
  File "cam_fomm.py", line 3, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'

**Comment by alphasldiallo** [comment]
You can fix it by installing the requirements. You can use `pip install -r requirements.txt` from the folder avatarify

**Comment by reecepounder** [comment]
I fixed this problem by reinstalling anaconda and selecting "Add to PATH"

**Comment by pag3** [comment]
Neither of those solutions worked for me but just "pip install yaml" again did.

**Comment by AptemCat** [comment]
> You can fix it by installing the requirements. You can use `pip install -r requirements.txt` from the folder avatarify

It makes some errors connected with matplotlib

**Comment by E3V3A** [comment]
I noticed that the mathplotlib was outdated, but not sure if that is your issue. Try to update?
