### ISSUE TITLE
Windows 10 installation fatal error

### ISSUE THREAD

**Issue by krl91** [alievk/avatarify#112]
Hi,
the installation on Windows 10 crashed. I strictly followed the installation procedure from https://github.com/alievk/avatarify

full logs:

[avatarify_installation_crachsh.txt](https://github.com/alievk/avatarify/files/4517762/avatarify_installation_crachsh.txt)

> (base) PS C:\Users\kb\git\avatarify> .\scripts\install_windows.bat
> 
> C:\Users\kb\git\avatarify>call scripts/settings_windows.bat
> 
> .....
>         self.distribution.run_command(command)
>       File "C:\Users\kb\Miniconda3\envs\avatarify\lib\distutils\dist.py", line 985, in run_command
>         cmd_obj.run()
>       File "C:\Users\kb\AppData\Local\Temp\pip-install-a5xjnidm\torch\setup.py", line 51, in run
>         from tools.nnwrap import generate_wrappers as generate_nn_wrappers
>     ModuleNotFoundError: No module named 'tools.nnwrap'
>     ----------------------------------------
> ERROR: Command errored out with exit status 1: 'C:\Users\kb\Miniconda3\envs\avatarify\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\kb\\AppData\\Local\\Temp\\pip-install-a5xjnidm\\torch\\setup.py'"'"'; __file__='"'"'C:\\Users\\kb\\AppData\\Local\\Temp\\pip-install-a5xjnidm\\torch\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\kb\AppData\Local\Temp\pip-record-tejgd_uh\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\kb\Miniconda3\envs\avatarify\Include\torch' Check the logs for full command output.

**Comment by E3V3A** [comment]
Lots of errors there. Also download errors. Try again and post your output in triple back-ticks, (```).
> call scripts/settings_windows.bat

That is not how you start it.

**Comment by alievk** [comment]
> 'git' n’est pas reconnu en tant que commande interne

I guess it says you don't have `git`. You have to install it (see readme)
