### ISSUE TITLE
ADD Issue template 

### ISSUE THREAD

**Issue by E3V3A** [alievk/avatarify#114]
We need an issue template to help users post proper issues and not just some random copy paste text.

I suggest to **require** user to:
* State what is their OS & version (Windows, Linus, MAC etc.)
  - We add some command line snippets for the user to get this info
* Versions for: 
  - Avatarify
  - CUDA
  - OS & HW info
* Show all commands leading up to issue. 
  (How to reproduce the issue?)

Then ask user to put post: 
* screen shots
* code/ terminal text and make sure they put it in between *triple-back-ticks* (```) markdown. 

etc...

**Comment by alievk** [comment]
That's a good idea, let's discuss it.

I doubt CUDA is necessary, though.

**Comment by E3V3A** [comment]
> I doubt CUDA is necessary, though.

No it's not ncessary, but people are going to post a lot of CUDA related issues here anyway, so might as well include it, if they have it. Or at least the CUDA related versions in the pytorch dependencies sub-dirs.

**Comment by alievk** [comment]
Two issue templates were added: one for bug report, another for new feature of improvement discussion.
