### ISSUE TITLE
Can I run with Intel Iris Pro 1536 MB

### ISSUE THREAD

**Issue by Joel1188** [alievk/avatarify#117]
Hi Alievk,

I have an Intel Iris Pro 1536 MB, can I run this program or is my laptop not fast enough?

Thanks

Joel

**Comment by E3V3A** [comment]
You can run, but it will not use your (AFAIK) graphics card as only nVidia supporting CUDA are fully supported. So you it will depend a lot on your processor and OS.

**Comment by Joel1188** [comment]
My laptop is a late 2013 Macbook Pro running Catalina OS 10.15.4   
Processor Name:	Quad-Core Intel Core i7
Processor Speed:	2 GHz
Its been running slow for a while, ever since I loaded Catalina, its a bummer but hey! 
This looks like great fun and if it wont run smoothly, it may end up becoming more frustrating than enjoyable.
Thank you for creating it and offering as an open source program :)
