### ISSUE TITLE
MAGMA library not found in compilation

### ISSUE THREAD

**Issue by thrakotool** [alievk/avatarify#118]
I'm on Mac 10.12, with nVidia 1080TI. Avatarify runs fine with the default torch 1.0.0, but it doesn't use Cuda - hence the performance is horrible. 
When I try to use a different Pytorch build with Cuda support, I get this:

0: ./avatars/einstein.jpg
load checkpoints..
Traceback (most recent call last):
  File "cam_fomm.py", line 284, in <module>
    pred = predict(frame, avatar, opt.relative, opt.adapt_scale, fa, device=device)
  File "cam_fomm.py", line 143, in predict
    use_relative_jacobian=relative, adapt_movement_scale=adapt_movement_scale)
  File "/Users/thrakotool/avatarify/fomm/animate.py", line 33, in normalize_kp
    jacobian_diff = torch.matmul(kp_driving['jacobian'], torch.inverse(kp_driving_initial['jacobian']))
RuntimeError: inverse: MAGMA library not found in compilation. Please rebuild with MAGMA.

Unfortunately I wasn't able to build pytorch from source with magma support. 
Is it possible for Mac users to utilize Cuda, but not use Magma?

**Comment by E3V3A** [comment]
Not enough info! Please post more details with *OS, info, versions* with *screenshots* and *commands* + (text) *output* leading up to the issue. Otherwise close this.

**Comment by thrakotool** [comment]
To be clear, I am using pip instead of conda, and I am able to run Avatarify without a single error - as long as I use standard Pytorch 1.0.0 without Cuda support. The issue is only present when I use Pytorch with Cuda support, taken from this repo: https://github.com/TomHeaven/pytorch-osx-build

OS info:
![sys info](https://user-images.githubusercontent.com/63564683/80071785-39464200-8513-11ea-992e-167ca87014a0.png)

pip list:
![pip list](https://user-images.githubusercontent.com/63564683/80072171-de611a80-8513-11ea-99af-29424d71378f.png)

Output:
![commands](https://user-images.githubusercontent.com/63564683/80072682-94c4ff80-8514-11ea-96c9-8b3bafdf90e3.png)

Also, due to not using Conda I had to slightly modify run_mac.sh, to this:
![run_mac_sh](https://user-images.githubusercontent.com/63564683/80072797-bf16bd00-8514-11ea-976b-111219d66d8a.png)

**Comment by E3V3A** [comment]
Well since you chose to not use conda, there's not much we can do to help you. (conda is used, because it is tuned to use compatible libraries/packages, so doing it on your own, will re-introduce those issues as soon as you are using the "latest" of everything. )

However keep us informed to the success to your alternative way of installing. Look like you're close...

**Comment by thrakotool** [comment]
Understandible. 

Once again, to be clear, with pip installation everything works perfectly well - as long as the libraries/packages match the requirements. So conda, while being more streamlined, is not a necessity. 

Also, it was not about using the latest versions, but only about making the setup Cuda compatible on Mac. 
So torch==1.0.0 (without Cuda) - perfectly running code (albeit slow).
torch==1.0.0 (with Cuda, or any other version of pytorch with Cuda)  - the described Magma error.

But I see how this is more of a pytorch/fomm related question, not an Avatarify issue. Cheers.
