### ISSUE TITLE
Not working on Mac OS 10.15 

### ISSUE THREAD

**Issue by vsinjavin** [alievk/avatarify#12]
Hi, 

All screens starting but without video substitution. 

Python version is Python 3.7.6.

Please help with what logs do you need to help. 

thanks

**Comment by karfly** [comment]
Hi, @vsinjavin!
Did you follow Mac installation [instructions](https://github.com/alievk/avatarify#mac) including downloading CamTwis?

**Comment by vsinjavin** [comment]
Sure, I applied all instructions.

**Comment by ricill** [comment]
Hi there,

I've got issues on 10.15 macOS as well
But in my case it fails to open camera when I run the script and select iTerm in CamTwist's "select from window"
```
[ERROR:0] global /Users/travis/build/skvark/opencv-python/opencv/modules/videoio/src/cap.cpp (193) open VIDEOIO(AVFOUNDATION): raised unknown C++ exception!


Cannot open camera
2020-04-11 18:56:46.578 python[76278:593824] MyPlugTeardown
2020-04-11 18:56:46.578 python[76278:593824] MyPlugTeardown
```

**Comment by karfly** [comment]
@vsinjavin, when you click 0-9 buttons, are you focused on one of the windows with cam stream?

**Comment by ricill** [comment]
Hi there!

Similar issue, not working on macOS 10.15
Camera turns on for a second and then immediately turns off, seems like script is not receiving any image from the camera https://take.ms/D6XeT

Console output end with error message:
```
Can't receive frame (stream end?). Exiting ...
2020-04-11 19:28:17.735 python[80172:631758] MyPlugTeardown
```

**Comment by ricill** [comment]
figured that out by setting CAMID to 3, not 0, 1 or 2 as mentioned in the troubleshooting
it works now, with a solid 0.3~0.5 fps

**Comment by Jackieyewang** [comment]
FileNotFoundError: [Errno 2] No such file or directory: 'vox-adv-cpk.pth.tar'

**Comment by vsinjavin** [comment]
[https://www.dropbox.com/s/rbmlceprajsca54/Screenshot%202020-04-13%2010.36.59.png?dl=0](url)

Nothing is happening for me still. ((( 

Any advise?
