### ISSUE TITLE
BUG: Wrong avatar names for the given keys 0-9

### ISSUE THREAD

**Issue by E3V3A** [alievk/avatarify#122]
The avatar images does not correspond to the number keys displayed. (E.g. 0 = Einstein)
The offending code is [here somewhere](https://github.com/alievk/avatarify/blob/master/cam_fomm.py#L349-L354).

**Comment by alievk** [comment]
Could your describe the problem in more detail?

**Comment by E3V3A** [comment]
```
0: ./avatars\einstein.jpg
1: ./avatars\eminem.jpg
2: ./avatars\jobs.jpg
3: ./avatars\mona.jpg
4: ./avatars\obama.jpg
5: ./avatars\potter.jpg
6: ./avatars\ronaldo.png
7: ./avatars\schwarzenegger.png
```

**Comment by alievk** [comment]
Ok, what's wrong with that?

**Comment by E3V3A** [comment]
> Ok, what's wrong with that?
Pushing `0` gives you your own cam, so no avatar can be mapped to zero AFAIK.

**Comment by Mantene** [comment]
Sounds more like an update of the documentation would fix this a lot simpler than a code change.

**Comment by E3V3A** [comment]
> Sounds more like an update of the documentation would fix this a lot simpler than a code change.

No, because it's an indexing problem.

**Comment by alievk** [comment]
> ```
> 0: ./avatars\einstein.jpg
> 1: ./avatars\eminem.jpg
> 2: ./avatars\jobs.jpg
> 3: ./avatars\mona.jpg
> 4: ./avatars\obama.jpg
> 5: ./avatars\potter.jpg
> 6: ./avatars\ronaldo.png
> 7: ./avatars\schwarzenegger.png
> ```

That was not originally meant to be key numbers. Gonna fix it.

**Comment by alievk** [comment]
6c0c85068c4e0ae3cab12fac1d1ad0ea3601d49a
