### ISSUE TITLE
Python environment issue - MAC

### ISSUE THREAD

**Issue by YubinXie** [alievk/avatarify#13]
I followed all the steps but got an environment issue. It seems the install is done not in the right environment. in My mac, the command should be 'source activate' instead of conda activate.

**Comment by YubinXie** [comment]
After fixing that, i got this issue:
ModuleNotFoundError: No module named 'face_alignment'

**Comment by YubinXie** [comment]
after install face_alignment, it shows...

**Comment by alievk** [comment]
Haven't added new dependency to Mac installer, sorry for that.
Did you install face_alignment from pip?

**Comment by YubinXie** [comment]
> Haven't added new dependency to Mac installer, sorry for that.
> Did you install face_alignment from pip?

Yes.

**Comment by karfly** [comment]
Hi, @YubinXie.
Please, make sure that you install `face_alignment ` to the `avatarify` conda environment:
```bash
conda activate avatarify
pip install face_alignment
```

**Comment by YubinXie** [comment]
@karfly I meant I did and it worked now...

**Comment by karfly** [comment]
@YubinXie, glad that you managed to solve a problem!
1. I use miniconda (v4.7.12) and `conda activate` works fine.
2. Added `face_alignment` installation to the `scripts/install_mac.sh` in 5a67ae846892efe3387c2d687ed85e0fbfaa5c2d. Thank you.
