### ISSUE TITLE
Distortion

### ISSUE THREAD

**Issue by jyu041** [alievk/avatarify#130]
When I use the software, the output of the face seems very distorted, and does not follow my facial expressions. Is it because my bad laptop webcam? Or is it because my Asian face is poorly recognized? Oh btw is there anyway to train it to fit my Asian face better? I am sorry if I sound stupid.

**Comment by akatasonov** [comment]
I have the same issue. As long as the camera is capturing darkness everything seems more or less okay (Einstein's face is a bit wobbly) but as soon as the camera starts capturing my face Einstein becomes super distorted, almost unrecognizable.

**Comment by jyu041** [comment]
i solved the problem by using a dedicated webcam, and by staring into it while the porgram startsup, like literally stare into it’s soul while the programme starts, and it would follow your face better.

**Comment by russelldc** [comment]
@jyu041 Rather than holding still and staring into the camera while the program starts up, you can always just press the X key on your keyboard to reset the alignment at any time while it's running. 

https://github.com/alievk/avatarify#driving-your-avatar

**Comment by jyu041** [comment]
> @jyu041 Rather than holding still and staring into the camera while the program starts up, you can always just press the X key on your keyboard to reset the alignment at any time while it's running.
> 
> https://github.com/alievk/avatarify#driving-your-avatar

OMG thanks for the tip, i didn't completely read through the guides, thank you so much
