### ISSUE TITLE
[request] how to uninstall

### ISSUE THREAD

**Issue by emmepunto** [alievk/avatarify#131]
hello there!
I've just installed following the whole procedure on my mac. here my system configuration:
![system](https://user-images.githubusercontent.com/64312905/80279531-96eab200-86fe-11ea-92fa-581b2c52fa76.png)
Once I've tried to run CamTwist, the app immediately crashed. I've then tried to open all the other app that use integrated camera (zoom, skype, photobooth) and all of them crashed.

Maybe there's something that it's in conflict..I'd like to restore the situation before, but I'm not finding how to uninstall everything.

could you please help me on this point?

thanks very much
a.

**Comment by nt314p** [comment]
You can start by uninstalling CamTwist.

**Comment by emmepunto** [comment]
> You can start by uninstalling CamTwist.

I did, but still having issues with the camera.
so I've tried to use the camera with another osx installed on the second hard drive and it works perfectly. so I've tried to re-install el capitan without formatting, but I've the same problem.

**Comment by emmepunto** [comment]
I'm attaching:
_a report after Skype crashing:
![skype_log](https://user-images.githubusercontent.com/64312905/80475196-d1478f80-8948-11ea-9402-e42882b5d3e4.png)
_a report after going to 'about this mac --> system report --> hardware --> camera 
![system_error](https://user-images.githubusercontent.com/64312905/80475210-d6a4da00-8948-11ea-937b-cab8a5f829a3.png)
![system_report](https://user-images.githubusercontent.com/64312905/80475215-d86e9d80-8948-11ea-9ee4-837d41023fd4.png)

none of this happens on the same mac book pro, but using my backup operating system on the second internal hard drive.

**Comment by emmepunto** [comment]
thanks @E3V3A
