### ISSUE TITLE
ERROR: Command errored out with exit status 1.

### ISSUE THREAD

**Issue by odrapj** [alievk/avatarify#133]
Hi,

I have this error  **Running setup.py install for torch ... error**.

 **ERROR: Command errored out with exit status 1**: ...Check the logs for full command output.

![image](https://user-images.githubusercontent.com/64170808/80283692-3d26bf80-86df-11ea-825d-72509db3ea1e.png)

**Comment by alievk** [comment]
Please re-open an issue and attach more information indicated in the issue template
