### ISSUE TITLE
OSERROR  Failed to open file b'C:\\Users\\...\\AppData\\Local\\Temp\\scipy-ikn1w3ak'

### ISSUE THREAD

**Issue by ExcaliburEX** [alievk/avatarify#138]
**Describe the bug**

after `load checkpoints`，it raises below error message：
```
AttributeError: 'NoneType' object has no attribute 'close'
Exception ignored in: 'scipy.spatial.qhull._Qhull.__dealloc__'
AttributeError: 'NoneType' object has no attribute 'close'
Traceback (most recent call last):
```
**To Reproduce**

**Info (please complete the following information):**
 - OS (e.g., Linux): Windows
 - GPU model: GTX 1070
 - Any other relevant information: 

**Screenshots**

![微信截图_20200427022026.png](https://i.loli.net/2020/04/27/mnNpRrDHTscU6zd.png)
**Logs**

```
AttributeError: 'NoneType' object has no attribute 'close'
Exception ignored in: 'scipy.spatial.qhull._Qhull.__dealloc__'
AttributeError: 'NoneType' object has no attribute 'close'
Traceback (most recent call last):
  File "cam_fomm.py", line 242, in <module>
    change_avatar(fa, avatars[cur_ava])
  File "cam_fomm.py", line 169, in change_avatar
    avatar_kp = get_frame_kp(fa, new_avatar)
  File "cam_fomm.py", line 64, in get_frame_kp
    kp_image = normalize_alignment_kp(kp_image)
  File "cam_fomm.py", line 55, in normalize_alignment_kp
    area = ConvexHull(kp[:, :2]).volume
  File "qhull.pyx", line 2335, in scipy.spatial.qhull.ConvexHull.__init__
  File "qhull.pyx", line 266, in scipy.spatial.qhull._Qhull.__init__
  File "messagestream.pyx", line 36, in scipy._lib.messagestream.MessageStream.__init__
OSError: Failed to open file b'C:\\Users\\\xe6\x9f\xaf\xe6\x91\xa9\\AppData\\Local\\Temp\\scipy-ikn1w3ak'
```

**Comment by ExcaliburEX** [comment]
can anyone have experienced this question?

**Comment by alievk** [comment]
Hi @ExcaliburEX , my guess is that something goes wrong 'cause the path contains non-latin characters.

**Comment by E3V3A** [comment]
Please post the output of the following commands:
(And for privacy remove your home directory username, if necessary.)
Enclose your output in triple back-ticks (```) on separate lines.

```bash
# conda activate avatarify
conda info
conda list
pip list
```

PS. It looks like you have a funny username possibly in a language character set that is not recognized by conda. Try using a simple ASCII username...

**Comment by E3V3A** [comment]
To check charset please use post the powershell output from:
```powershell
(Get-CimInstance Win32_OperatingSystem) | Select-Object Caption,Version,OSArchitecture | Format-Table -hideTableHeader
(Get-Variable OutputEncoding).Value.EncodingName
Get-Host
```
and since you're at it, the output from a CMD when typing:  `chcp.com`

**Comment by alievk** [comment]
@ExcaliburEX please let us know if you have resolved this issue.

**Comment by ExcaliburEX** [comment]
> Please post the output of the following commands:
> (And for privacy remove your home directory username, if necessary.)
> Enclose your output in triple back-ticks (```) on separate lines.
> 
> ```shell
> # conda activate avatarify
> conda info
> conda list
> pip list
> ```
> 
> PS. It looks like you have a funny username possibly in a language character set that is not recognized by conda. Try using a simple ASCII username...

Thank for all your help! These commands help me find the reason for the problem which is the pathname of the conda dir. Then I used administrator rights to change the user dir name into Latin characters so avatarify can work without any mistake!

**Comment by ExcaliburEX** [comment]
> @ExcaliburEX please let us know if you have resolved this issue.

Thanks a lot for your suggestion and  I am sorry that I am a bit slow to reply. After changing the pathname of user dir, I solved the problem.
