### ISSUE TITLE
Bug when running: scripts\install_windows.bat

### ISSUE THREAD

**Issue by Boris34000** [alievk/avatarify#139]
**Describe the bug**
I obtain a red screen under Miniconda (picture attached)

**To Reproduce**
I follow your video guide, step: scripts\install_windows.bat

**Info (please complete the following information):**
 - OS (e.g., Linux): Win10
 - GPU model: GTX 2070
 - Any other relevant information: Last driver

**Screenshots**
Attached

**Logs**

**Comment by E3V3A** [comment]
Where's the picture?

**Comment by alievk** [comment]
Hi @Boris34000 , seems like you haven't attached the screenshot.

**Comment by Boris34000** [comment]
Hi,
Sorry, I thought it was correctly attached. Now I've deleted it.

Your avatarify software seems gret, good luck for the improvements :)
best, Boris

     Le lundi 27 avril 2020 à 10:47:27 UTC+2, Ali Aliev <notifications@github.com> a écrit :  
 
 


Hi @Boris34000 , seems like you haven't attached the screenshot.

**Comment by alievk** [comment]
Is the issue resolved?

**Comment by 18845045369** [comment]
![2020-04-30 120619](https://user-images.githubusercontent.com/64247303/80671271-f02a5b00-8adb-11ea-8630-2feee5c2c39e.gif)

**Comment by E3V3A** [comment]
Did you run the installation script? 
At this point I'd suggest removing all and start from scratch. We have no way to check what you did, leading up to the error shown. Please provide detailed (as asked for in issue template) description of all commands issued for installation,activation and running.

**Comment by alievk** [comment]
@18845045369 could you insert output of the following commands here?
```
conda activate avatarify
pip freeze
```

**Comment by 18845045369** [comment]
Thank you so much




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"E:V:A"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月30日(星期四) 下午4:12
收件人:&nbsp;"alievk/avatarify"<avatarify@noreply.github.com&gt;;
抄送:&nbsp;"Fate．垨堠"<2415200549@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [alievk/avatarify] Bug when running: scripts\install_windows.bat (#139)





 
Did you run the installation script?
 At this point I'd suggest removing all and start from scratch. We have no way to check what you did, leading up to the error shown. Please provide detailed (as asked for in issue template) description of all commands issued for installation,activation and running.

**Comment by 18845045369** [comment]
I did not press the first step to enter the git command miniconada, but to clone on GitHub.


The reason is that I can never download a full project






------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Ali Aliev"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月30日(星期四) 下午5:12
收件人:&nbsp;"alievk/avatarify"<avatarify@noreply.github.com&gt;;
抄送:&nbsp;"Fate．垨堠"<2415200549@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [alievk/avatarify] Bug when running: scripts\install_windows.bat (#139)





 
@18845045369 could you insert output of the following commands here?
 conda activate avatarify pip freeze

**Comment by 18845045369** [comment]
![Snipaste_2020-04-30_21-47-40](https://user-images.githubusercontent.com/64247303/80718571-e7ae4080-8b2c-11ea-9692-8cad5bfd3ddb.gif)
What's the matter?

**Comment by E3V3A** [comment]
@18845045369 Those are big packages and you seem to be on a slow or unstable connection. Make sure you have a reliable internet connection. *pytorch* is another package that is slow to download. Just keep trying.

**Comment by 18845045369** [comment]
Thank you for helping me finish it

**Comment by E3V3A** [comment]
@18845045369 Did you manage? If yes, please close this issue.
