### ISSUE TITLE
Mac- Zoom doesn't see avatarify camera

### ISSUE THREAD

**Issue by YubinXie** [alievk/avatarify#14]
After re-start Zoom many times, I still did not see the avatarify camera in the video setting.

**Comment by alievk** [comment]
Do you follow these instructions https://github.com/alievk/avatarify#mac-1 ?
You should look for CamTwist camera in case of Mac.

**Comment by YubinXie** [comment]
Yes, I followed the instruction. Only the laptop camera shows up in my Zoom.

**Comment by YubinXie** [comment]
@alievk 
I saw ppl discussing that this could potentially be due to the latest update of Zoom 
https://www.reddit.com/r/Zoom/comments/fuq3wk/camtwist_and_zoom/

**Comment by karfly** [comment]
We updated the [installation guide for Mac](https://github.com/alievk/avatarify/blob/master/README.md#mac) regarding new Zoom updates:

*(!) Note*: we found out that in versions after [v4.6.8 (March 23, 2020)](https://zoom.us/client/4.6.19178.0323/ZoomInstaller.pkg) Zoom disabled support for virtual cameras on both Mac and Windows. Please, install [Zoom v4.6.8](https://zoom.us/client/4.6.19178.0323/ZoomInstaller.pkg) which is the last version that supports virtual cameras.

**Comment by YubinXie** [comment]
Zoom has security issues which is the reason behind the update... this makes things more complicated...
