### ISSUE TITLE
How to remove Avatarify from macOS?

### ISSUE THREAD

**Issue by TimurC1** [alievk/avatarify#142]
Hello, Ali! The Avatarify is good, but I wanna delete it with all dependencies for some reasons. How I can do it, do you have the script for this? Operation system is macOS.

**Comment by alievk** [comment]
Hi @TimurC1 ,

### Remove Avatarify  
1. Open terminal window
2. Replace `/path/to/avatarify` with the actual path and run:    
```
rm -rf /path/to/avatarify
```

### Uninstall Miniconda
1. Open terminal window
2. Find `conda` location:  
```
which conda  
```  
3. Remove Miniconda directory. For example, if the previous command returned `/opt/miniconda3/bin/conda`, then remove `/opt/miniconda3`:  
```
rm -rf /opt/miniconda3
``` 

 ### Uninstall CamTwist  
Go to Programs and move CamTwist to Trash.

**Comment by TimurC1** [comment]
Thank you! Maybe you will add it to Readme?

**Comment by emmepunto** [comment]
> Hi @TimurC1 ,
> 
> ### Remove Avatarify
> 1. Open terminal window
> 2. Replace `/path/to/avatarify` with the actual path and run:
> 
> ```
> rm -rf /path/to/avatarify
> ```
> 
> ### Uninstall Miniconda
> 1. Open terminal window
> 2. Find `conda` location:
> 
> ```
> which conda  
> ```
> 
> 1. Remove Miniconda directory. For example, if the previous command returned `/opt/miniconda3/bin/conda`, then remove `/opt/miniconda3`:
> 
> ```
> rm -rf /opt/miniconda3
> ```
> 
> ### Uninstall CamTwist
> Go to Programs and move CamTwist to Trash.

Hi @alievk 
I've followed all these instructions and removed everything related..after restarting the mac, I'm still having problems with the camera..osx is not finding the camera. I know it's not broken (I've no problem with another osx on the second hard drive of my mbp), but el capitan isn't not finding it even after a re-installation of the operating system. there're more details in a thread I've opened a couple of days ago.
I hope you'll be able to help.
thanks,
alessandro

**Comment by alievk** [comment]
Hi @emmepunto , I'm not an experienced Mac user, unfortunately. Maybe @karfly may help?

**Comment by emmepunto** [comment]
thanks @alievk for coming back to me. I'll wait for @karfly :)

**Comment by cjboco** [comment]
If you installed Miniconda with `brew`, then you should:

`brew cask uninstall miniconda`

**Comment by alievk** [comment]
> If you installed Miniconda with `brew`, then you should:
> 
> `brew cask uninstall miniconda`

Sure! Added to Wiki https://github.com/alievk/avatarify/wiki/Removing-Avatarify

**Comment by emmepunto** [comment]
hi everyone!
I've done all the unistall processes, but I'm still having this problem with the camera..the operating system doesn't recognize it, while it's still working on my second hard drive (with a backup osx).
the report issue is:
![Screen Shot 2020-04-30 at 14 45 50](https://user-images.githubusercontent.com/64312905/80712042-a2205200-8af1-11ea-9ede-78ae299edc51.png)


I think I'll have to try to re-install it again..or to inizialize and format..
thanks,
ale

**Comment by karfly** [comment]
Hi, @emmepunto!
It's highly unlikely your camera doesn't work because of the Avatarify. Maybe there are some issues with CamTwist, so I'd try to search for your problem in the context of CamTwist.

**Comment by emmepunto** [comment]
hi @karfly 
yep, maybe camtwist did something..actually I didn't have the chance to use it 'cause it crashed the first time I open it..after that, I've tried opening other camera-related software (previously all working) and they started crashing.
I've then uninstalled camtwist (using app cleaner), but the issus is still present..I don't know if there are any files I've to manually remove..

**Comment by emmepunto** [comment]
I've find a solution. there was one last camtwist plugin in a remote library folder:
(your HD) --> Library --> CoreMediaIO --> Plug-Ins --> DAL
I've just removed CamTwist.plugin (it's not been removed even using an app like appcleaner). now everything's working.
thanks @karfly for making me focusing the attention only on camtwist

**Comment by alievk** [comment]
Thank you @emmepunto , added that to the Wiki :)

**Comment by emmepunto** [comment]
you're welcome @alievk :)
