### ISSUE TITLE
Cannot run avatarify on MacOs Catalina

### ISSUE THREAD

**Issue by dzaiats** [alievk/avatarify#144]
**Describe the bug**
After successfully installing, etc, it says that cannot find the camera

```
[ERROR:0] global /Users/travis/build/skvark/opencv-python/opencv/modules/videoio/src/cap.cpp (193) open VIDEOIO(AVFOUNDATION): raised unknown C++ exception!


Traceback (most recent call last):
  File "cam_fomm.py", line 250, in <module>
    cap = VideoCaptureAsync(opt.cam)
  File "/Users/ZayCo/Developing/Python/avatarify/videocaptureasync.py", line 17, in __init__
    raise RuntimeError("Cannot open camera. Try to choose other CAMID in './scripts/settings.sh'")
RuntimeError: Cannot open camera. Try to choose other CAMID in './scripts/settings.sh'
```

**To Reproduce**
Try to run on MacOs Catalina

**Info (please complete the following information):**
 - OS Mac OS Catalina: 
 - GPU Radeon:

**Comment by victorwu** [comment]
Edit [run_mac.sh](https://github.com/alievk/avatarify/blob/master/run_mac.sh)
Add/set the new variable CAMID=1
Try 0, 1, 2, or 3

**Comment by karfly** [comment]
As @victorwu mentioned, it looks like the wrong camera is chosen.
Try to change `CAMID=0` to `CAMID=1` or `CAMID=2` in `scripts/settings.sh`.

**Comment by DrexelRose** [comment]
changing the camera ID worked for me with this issue

**Comment by dzaiats** [comment]
Hi @karfly , I was trying to change camera, etc.
It looks like internal issue of Catalina and python. Perhaps OpenCV version.

**Comment by karfly** [comment]
Hi, @dzaiats!
What errors do you get in the terminal? Can you show the full log?
