### ISSUE TITLE
Failed to succesfully grab frame from the camera

### ISSUE THREAD

**Issue by Nawiss** [alievk/avatarify#145]
Failed to succesfully grab frame from the camera (File "cam_fomm.py" was update to latest version 3e30b11)
When the command starts, two windows (camera and avatar) immediately close.
I spent a lot of time but I don’t know what else can be done to make the camera work.

Windows 10 Pro (64)
Intel® Core™ i3-6100U CPU @ 2.30GHz
NVIDIA GeForce 920MX 
and
Intel® HD Graphics 520
RAM 8Gb

**Logs**
load checkpoints..
[ WARN:1] global C:\projects\opencv-python\opencv\modules\videoio\src\cap_msmf.cpp (1113) SourceReaderCB::OnReadSample videoio(MSMF): OnReadSample() is called with error status: -1072873822
[ WARN:1] global C:\projects\opencv-python\opencv\modules\videoio\src\cap_msmf.cpp (1125) SourceReaderCB::OnReadSample videoio(MSMF): async ReadSample() call is failed with error status: -1072873822
[ WARN:0] global C:\projects\opencv-python\opencv\modules\videoio\src\cap_msmf.cpp (1159) CvCapture_MSMF::grabFrame videoio(MSMF): can't grab frame. Error: -1072873822
[ WARN:2] global C:\projects\opencv-python\opencv\modules\videTraceback (most recent call last):
oi  File "cam_fomm.py", line 251, in <module>
o\src\c    cap.start()
a  File "C:\Windows\System32\avatarify\videocaptureasync.py", line 44, in start
p_    raise RuntimeError(f"Failed to succesfully grab frame from the camera (timeout={WARMUP_TIMEOUT}s). Try to restart.")
RuntimeError: Failed to succesfully grab frame from the camera (timeout=10.0s). Try to restart.
msmf.cpp (1159) CvCapture_MSMF::grabFrame videoio(MSMF): can't grab frame. Error: -2147483638

**Comment by nt314p** [comment]
I know it might be obvious but: is your camera being used by any other application?

**Comment by Nawiss** [comment]
> I know it might be obvious but: is your camera being used by any other application?

It seems that everything that could use it turned off. And besides, the indicator that camera was working didn’t light up, so it’s not involved others

**Comment by liuhuixiang-987** [comment]
> 我知道这可能是显而易见的，但是：您的相机是否被任何其他应用程序使用？

The camera is not occupied, but it does appear break when running res, frame = camera.read()，this is failed to grab frame。Because the camera is available while I'm running another detection code

**Comment by liuhuixiang-987** [comment]
> 未能成功从相机抓取帧（文件“cam_fomm.py”已更新到最新版本[3e30b11](https://github.com/alievk/avatarify-python/commit/3e30b1176ef4e2f4f4a22f4f8c83d23250084399)）当命令启动时，两个窗口（相机和头像）立即关闭。我花了很多时间，但我不知道还可以做些什么来使相机工作。
> 
> Windows 10 Pro （64） Intel Core i3-6100U CPU @ 2.30GHz NVIDIA GeForce 920MX 和 Intel® HD Graphics 520 RAM 8Gb™®
> 
> **日志**加载检查点。. [ WARN：1] global C：\projects\opencv-python\opencv\modules\videoio\src\cap_msmf.cpp （1113） SourceReaderCB：：OnReadSample videoio（MSMF）： OnReadSample（） 被调用时出现错误状态： -1072873822 [ WARN：1] global C：\projects\opencv-python\opencv\modules\videoio\src\cap_msmf.cpp （1125） SourceReaderCB：：OnReadSample videoio（MSMF）： async ReadSample（） 调用失败，错误状态为 ：-1072873822 [ WARN：0] global C：\projects\opencv-python\opencv\modules\videoio\src\cap_msmf.cpp （1159） CvCapture_MSMF：：grabFrame videoio（MSMF）： can't grab frame.错误： -1072873822 [ WARN：2] 全局 C：\projects\opencv-python\opencv\modules\videTraceback （最近一次调用）： oi 文件 “cam_fomm.py”， 第 251 行， 在 o\src\c cap.start（） 一个文件 “C：\Windows\System32\avatarify\videocaptureasync.py”， 第 44 行， 在开始p_提高 RuntimeError（f“未能成功从相机抓取帧 （timeout={WARMUP_TIMEOUT}s）。请尝试重新启动。运行时错误：无法成功从相机抓取帧（超时 = 10.0 秒）。尝试重新启动。 msmf.cpp （1159） CvCapture_MSMF：：grabFrame videoio（MSMF）：无法抓取帧。错误：-2147483638

Have you made this mistake：cv2.error: OpenCV(4.5.4) D:\a\opencv-python\opencv-python\opencv\modules\core\src\rand.cpp:394: error: (-215:Assertion failed) !_mat.empty() in function 'cv::RNG::fill'. The error occurs in this read video stream here:fg_mask = bs.apply(frame).

**Comment by liuhuixiang-987** [comment]
> 未能成功从相机抓取帧（文件“cam_fomm.py”已更新到最新版本[3e30b11](https://github.com/alievk/avatarify-python/commit/3e30b1176ef4e2f4f4a22f4f8c83d23250084399)）当命令启动时，两个窗口（相机和头像）立即关闭。我花了很多时间，但我不知道还可以做些什么来使相机工作。
> 
> Windows 10 Pro （64） Intel Core i3-6100U CPU @ 2.30GHz NVIDIA GeForce 920MX 和 Intel® HD Graphics 520 RAM 8Gb™®
> 
> **日志**加载检查点。. [ WARN：1] global C：\projects\opencv-python\opencv\modules\videoio\src\cap_msmf.cpp （1113） SourceReaderCB：：OnReadSample videoio（MSMF）： OnReadSample（） 被调用时出现错误状态： -1072873822 [ WARN：1] global C：\projects\opencv-python\opencv\modules\videoio\src\cap_msmf.cpp （1125） SourceReaderCB：：OnReadSample videoio（MSMF）： async ReadSample（） 调用失败，错误状态为 ：-1072873822 [ WARN：0] global C：\projects\opencv-python\opencv\modules\videoio\src\cap_msmf.cpp （1159） CvCapture_MSMF：：grabFrame videoio（MSMF）： can't grab frame.错误： -1072873822 [ WARN：2] 全局 C：\projects\opencv-python\opencv\modules\videTraceback （最近一次调用）： oi 文件 “cam_fomm.py”， 第 251 行， 在 o\src\c cap.start（） 一个文件 “C：\Windows\System32\avatarify\videocaptureasync.py”， 第 44 行， 在开始p_提高 RuntimeError（f“未能成功从相机抓取帧 （timeout={WARMUP_TIMEOUT}s）。请尝试重新启动。运行时错误：无法成功从相机抓取帧（超时 = 10.0 秒）。尝试重新启动。 msmf.cpp （1159） CvCapture_MSMF：：grabFrame videoio（MSMF）：无法抓取帧。错误：-2147483638
Have you solved this problem

**Comment by JohanAR** [comment]
Check if your webcam is supported by OpenCV. If it is not you'll either have to get a different camera, or modify the avatarify-python to use a different library to read frames from it.
