### ISSUE TITLE
On my Mac it doesn't work?

### ISSUE THREAD

**Issue by Anish6002** [alievk/avatarify#147]
FileNotFoundError: [Errno 2] No such file or directory: 'vox-adv-cpk.pth.tar'

**Comment by Anish6002** [comment]
FileNotFoundError: [Errno 2] No such file or directory: 'vox-adv-cpk.pth.tar'

**Comment by DrexelRose** [comment]
Read through the instructions on https://aliaksandrsiarohin.github.io/first-order-model-website/
It has a link to download that file from somewhere. 

Its worth noting that "first order model" and subsequently "avatarify" run painfully slow on Mac as these programs utilize Nvidia CUDA enabled GPUs to be able to smoothy run the neural network black magic that they do.

**Comment by DrexelRose** [comment]
my bad, the link I meant to paste was this:
https://github.com/AliaksandrSiarohin/first-order-model
