### ISSUE TITLE
Slow performance on nvidia gtx 1080 gpu

### ISSUE THREAD

**Issue by hanlinniu** [alievk/avatarify#15]
Hello, I tried the code on my laptop using nvidia 1080 gpu with cuda installed, however the fps is only 2 fps, do you know why?

**Comment by alievk** [comment]
@hanlinniu Can you check gpu utilization in  nvidia-smi? Is torch.cuda.is_available() returning True?

**Comment by hanlinniu** [comment]
@alievk , thank you very much, it was my torch version didn't work and I changed it, now it is 15 fps

**Comment by Mumzkid4** [comment]
> [@hanlinniu](https://github.com/hanlinniu) Can you check gpu utilization in nvidia-smi? Is torch.cuda.is_available() returning True?

yes
