### ISSUE TITLE
Jitsi meet fails to access camera

### ISSUE THREAD

**Issue by gamboz** [alievk/avatarify#150]
I have avatarify working well in zoom and [Talk](https://nextcloud.com/talk/), but jitsi (and I think also [hangouts](hangouts.google.com/) ) fails to access any camera (both the hardware one and the virtual one).

To Reproduce, run avatarify and then access https://meet.jit.si/anything 

 - OS: Archlinux 
 - GPU model:  NVIDIA Corporation GP108M [GeForce MX250] (rev a1)
 - browser: firefox and chromium

![Screenshot_2020-05-01_18-36-47](https://user-images.githubusercontent.com/11026476/80822800-c22c4000-8bdb-11ea-84f6-8a70ea4d3a8f.png)

(compliments for the wonderful project :)

**Comment by gamboz** [comment]
Sorry, I forgot this: in firefox's web developer console, I have a couple of the following (not sure if this is related):
```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://api.amplitude.com/. (Reason: CORS request did not succeed).
```

**Comment by alievk** [comment]
I had problems with Chrome since it tries to connect the default camera, but Firefox give a choice and it works fine
![image](https://user-images.githubusercontent.com/4682236/80824677-9ca53380-8be7-11ea-9193-647fc82ad8a2.png)

**Comment by gamboz** [comment]
I'm sorry, you are right.
I had a configuration in  `about:preferences#privacy → Permissions → Camera` that jitsi should access the hardware camera. This prevented the menù from showing up.
Thanks and sorry again :)
