### ISSUE TITLE
Fails to download the face detection CNN on Mac.

### ISSUE THREAD

**Issue by MarkSalabutin** [alievk/avatarify#153]
When calling the `bash run_mac.sh` command it fails after 5-15 minutes, presumably on the `download the face detection CNN` phase. 

OS: macOS Catalina 10.15.4

Here's the output of the command:
```
Key 1: ./avatars/einstein.jpg
Key 2: ./avatars/eminem.jpg
Key 3: ./avatars/jobs.jpg
Key 4: ./avatars/mona.jpg
Key 5: ./avatars/obama.jpg
Key 6: ./avatars/potter.jpg
Key 7: ./avatars/ronaldo.png
Key 8: ./avatars/schwarzenegger.png
load checkpoints..
Downloading the face detection CNN. Please wait...
Traceback (most recent call last):
  File "cam_fomm.py", line 262, in <module>
    fa = face_alignment.FaceAlignment(face_alignment.LandmarksType._2D, flip_input=True, device=device)
  File "/usr/local/Caskroom/miniconda/base/envs/avatarify/lib/python3.7/site-packages/face_alignment/api.py", line 66, in __init__
    self.face_detector = face_detector_module.FaceDetector(device=device, verbose=verbose)
  File "/usr/local/Caskroom/miniconda/base/envs/avatarify/lib/python3.7/site-packages/face_alignment/detection/sfd/sfd_detector.py", line 39, in __init__
    os.path.join(path_to_temp_detector))
  File "/usr/local/Caskroom/miniconda/base/envs/avatarify/lib/python3.7/urllib/request.py", line 288, in urlretrieve
    % (read, size), result)
urllib.error.ContentTooShortError: <urlopen error retrieval incomplete: got only 1949316 out of 89843225 bytes>
```

**Comment by nick714** [comment]
see sfd_detector.py code ,and do it yourself

**Comment by jackylee1** [comment]
i have the same question

**Comment by alievk** [comment]
Can't help here, looks like a networking issue.

**Comment by MarkSalabutin** [comment]
Yeah, actually I was able to resolve this issue by running the `run` command multiple times, it was indeed a networking issue.
Finally was able to run the remote GPU setup, it is brilliant 💎 @alievk thank you so much!

**Comment by alievk** [comment]
@MarkSalabutin thank you!

Do you use a cloud service or running on a dedicated machine?

**Comment by MarkSalabutin** [comment]
@alievk I use AWS EC2 `g4dn.xlarge` instance.

**Comment by alievk** [comment]
@MarkSalabutin Could you show the performance metrics, like logs of the server (RECV/CALL lines) as well as the latency information to the instance (i.e. ping)?

How easy it was to deploy the server on the instance? How much does it cost?

**Comment by MarkSalabutin** [comment]
@alievk Sure thing! 
`ping` logs: https://pastebin.com/NfyU322U
worker logs: https://pastebin.com/63uNZYBt
client logs: https://pastebin.com/Jr5DX3cE
FPS: 
![image](https://user-images.githubusercontent.com/20834494/81536817-d0652380-9374-11ea-814b-39971da7ee58.png)

Regarding instance configuration, basically I just followed this [guide](https://github.com/alievk/avatarify/wiki/Remote-GPU), additionally, I had to install
`libsm6 libxext6 libxrender-dev` packages and Nvidia drivers using this [guide](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/install-nvidia-driver.html#nvidia-gaming-driver).

In terms of const here's what AWS says in the bill details
`$0.658 per On Demand Linux g4dn.xlarge Instance Hour`

**Comment by alievk** [comment]
@MarkSalabutin thank you so much!

We can prepare a public AMI for that.

Does `$0.658 per our` include storage cost?

**Comment by MarkSalabutin** [comment]
@alievk Yeah, the process of configuring the remote GPU setup would be much more user-friendly If we will create AMI for that.
The default 8GB for this type of instance is free but I had to add an additional 8GB in case the instance runs out of storage because currently `47.2% of 15.45GB` is used and those 8GB cost me 0.09$ so far.

**Comment by tgmerritt** [comment]
I'd be happy to write up the process of provisioning an EC2 instance - at least I can make that contribution.

For this thread though - here is every command ran against the server to get it setup, you should be able to almost literally go top to bottom and have everything dialed in: https://gist.github.com/tgmerritt/92cf25f40d4ac66f62a7c2c1256b0736

I used a g4dn.xlarge also - provisioned 64 GB of storage as the first time 8 was too little and I didn't want to run out again - 16GB is probably enough as noted above.

**Comment by alievk** [comment]
@MarkSalabutin I will look into reducing the size of the installation and try to fit into 8Gb
