### ISSUE TITLE
no success in install.bat: my error

### ISSUE THREAD

**Issue by edg65** [alievk/avatarify#154]
**Describe the bug**

**To Reproduce**

**Info (please complete the following information):**
 - OS (e.g., Linux): 
 - GPU model: 
 - Any other relevant information: 

**Screenshots**

**Logs**

**Comment by edg65** [comment]
this is the error, please help.
Downloading and Extracting Packages
pycparser-2.20       | 92 KB     | ############################################################################ | 100%
mkl-2020.0           | 98.9 MB   | ############################################################################ | 100%
blas-1.0             | 6 KB      | ############################################################################ | 100%
intel-openmp-2020.0  | 1.5 MB    | ############################################################################ | 100%
libpng-1.6.37        | 333 KB    | ############################################################################ | 100%
torchvision-0.2.1    | 37 KB     | ############################################################################ | 100%
xz-5.2.5             | 333 KB    | ############################################################################ | 100%
mkl_fft-1.0.15       | 118 KB    | ############################################################################ | 100%
tk-8.6.8             | 3.1 MB    | ############################################################################ | 100%
libtiff-4.1.0        | 737 KB    | ############################################################################ | 100%
olefile-0.46         | 49 KB     | ############################################################################ | 100%
numpy-1.18.1         | 6 KB      | ############################################################################ | 100%
icc_rt-2019.0.0      | 6.0 MB    | ############################################################################ | 100%
ninja-1.9.0          | 238 KB    | ############################################################################ | 100%
freetype-2.9.1       | 450 KB    | ############################################################################ | 100%
cuda100-1.0          | 2 KB      | ############################################################################ | 100%
numpy-base-1.18.1    | 3.8 MB    | ############################################################################ | 100%
jpeg-9b              | 245 KB    | ############################################################################ | 100%
pytorch-1.0.0        | 654.7 MB  | ############################################################################ | 100%
mkl-service-2.3.0    | 210 KB    | ############################################################################ | 100%
mkl_random-1.1.0     | 232 KB    | ############################################################################ | 100%
zstd-1.3.7           | 337 KB    | ############################################################################ | 100%
pillow-7.0.0         | 646 KB    | ############################################################################ | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
Impossibile trovare il file specificato.
Cloning into 'fomm'...
remote: Enumerating objects: 4, done.
remote: Counting objects: 100% (4/4), done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 200 (delta 0), reused 1 (delta 0), pack-reused 196
Receiving objects: 100% (200/200), 58.16 MiB | 27.90 MiB/s, done.
Resolving deltas: 100% (96/96), done.
Traceback (most recent call last):
  File "C:\Users\sikur\miniconda3\envs\avatarify\Scripts\pip-script.py", line 6, in <module>
    from pip._internal.cli.main import main
ModuleNotFoundError: No module named 'pip._internal.cli.main'

**Comment by Madoshakalaka** [comment]
I had this issue on Linux and this helped me:

```
$ conda actiavate avatarify
$ python -m pip install --upgrade pip
```
then run the install script again

`$ bash scripts/install.sh`
