### ISSUE TITLE
Guide update: install-windows.bat no longer exists

### ISSUE THREAD

**Issue by yllekz** [alievk/avatarify#156]
Hi folks, just an FYI in the install guide for Windows, there is no longer an install_windows.bat file. There is run_windows.bat, but I'm not sure if that's the same. Also a clarification, does one need to install MiniConda for all users, or is installing just for the current user sufficient? I'm asking because of the possibility of sensitivity to path variables.

**Comment by alievk** [comment]
install_windows.bat is and was in scripts/install_windows.bat

You can install Miniconda only for one user

**Comment by yllekz** [comment]
Hello, Thanks for the clarification on the script location.

Regarding Miniconda, it does ask during the installation if you want to install for user or for system. It does offer you a choice. Furthermore, when I just installed it for user, the script failed to ru, not finding "conda." This is why I asked here. You may want to consider updating the documentation stating to install it for system as opposed to for user. Thank you.
