### ISSUE TITLE
please help.

### ISSUE THREAD

**Issue by jackylee1** [alievk/avatarify#164]
(base) C:\Users\anbanglee\avatarify>scripts\install_windows.bat
conda found
git found
Collecting package metadata (current_repodata.json): done
Solving environment: done

==> WARNING: A newer version of conda exists. <==
  current version: 4.8.2
  latest version: 4.8.3

Please update conda by running

    $ conda update -n base -c defaults conda

DirectoryNotACondaEnvironmentError: The target directory exists, but it is not a conda environment.
Use 'conda create' to convert the directory to a conda environment.
  target directory: C:\Users\anbanglee\miniconda3\envs\avatarify

DirectoryNotACondaEnvironmentError: The target directory exists, but it is not a conda environment.
Use 'conda create' to convert the directory to a conda environment.
  target directory: C:\Users\anbanglee\miniconda3\envs\avatarify

系统找不到指定的文件。
Cloning into 'fomm'...
remote: Enumerating objects: 200, done.
remote: Total 200 (delta 0), reused 0 (delta 0), pack-reused 200R                                                       Receiving objects:  87
Receiving objects: 100% (200/200), 58.16 MiB | 23.00 KiB/s, done.
Resolving deltas: 100% (99/99), done.
Collecting cloudpickle==0.5.3
  Using cached cloudpickle-0.5.3-py2.py3-none-any.whl (13 kB)
Collecting cycler==0.10.0
  Using cached cycler-0.10.0-py2.py3-none-any.whl (6.5 kB)
Collecting dask==0.18.2
  Using cached dask-0.18.2-py2.py3-none-any.whl (645 kB)
Collecting decorator==4.3.0
  Using cached decorator-4.3.0-py2.py3-none-any.whl (9.2 kB)
Collecting imageio==2.3.0
  Using cached imageio-2.3.0-py2.py3-none-any.whl (3.3 MB)
Collecting kiwisolver==1.0.1
  Using cached kiwisolver-1.0.1.tar.gz (31 kB)
Collecting matplotlib==2.2.2
  Using cached matplotlib-2.2.2.tar.gz (37.3 MB)
    ERROR: Command errored out with exit status 1:
     command: 'c:\python38\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\anbanglee\\AppData\\Local\\Temp\\pip-install-e_tpr9ky\\matplotlib\\setup.py'"'"'; __file__='"'"'C:\\Users\\anbanglee\\AppData\\Local\\Temp\\pip-install-e_tpr9ky\\matplotlib\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\anbanglee\AppData\Local\Temp\pip-pip-egg-info-_mv9_4ps'
         cwd: C:\Users\anbanglee\AppData\Local\Temp\pip-install-e_tpr9ky\matplotlib\
    Complete output (61 lines):
    ============================================================================
    Edit setup.cfg to change the build options

    BUILDING MATPLOTLIB
                matplotlib: yes [2.2.2]
                    python: yes [3.8.1 (tags/v3.8.1:1b293b6, Dec 18 2019,
                            23:11:46) [MSC v.1916 64 bit (AMD64)]]
                  platform: yes [win32]

    REQUIRED DEPENDENCIES AND EXTENSIONS
                     numpy: yes [not found. pip may install it below.]
          install_requires: yes [handled by setuptools]
                    libagg: yes [pkg-config information for 'libagg' could not
                            be found. Using local copy.]
                  freetype: no  [The C/C++ header for freetype
                            (freetype2\ft2build.h) could not be found.  You may
                            need to install the development package.]
                       png: no  [The C/C++ header for png (png.h) could not be
                            found.  You may need to install the development
                            package.]
                     qhull: yes [pkg-config information for 'libqhull' could not
                            be found. Using local copy.]

    OPTIONAL SUBPACKAGES
               sample_data: yes [installing]
                  toolkits: yes [installing]
                     tests: no  [skipping due to configuration]
            toolkits_tests: no  [skipping due to configuration]

    OPTIONAL BACKEND EXTENSIONS
                    macosx: no  [Mac OS-X only]
                    qt5agg: no  [PySide2 not found; PyQt5 not found]
                    qt4agg: no  [PySide not found; PyQt4 not found]
                   gtk3agg: no  [Requires pygobject to be installed.]
                 gtk3cairo: no  [Requires cairocffi or pycairo to be installed.]
                    gtkagg: no  [Requires pygtk]
                     tkagg: yes [installing; run-time loading from Python Tcl /
                            Tk]
                     wxagg: no  [requires wxPython]
                       gtk: no  [Requires pygtk]
                       agg: yes [installing]
                     cairo: no  [cairocffi or pycairo not found]
                 windowing: yes [installing]

    OPTIONAL LATEX DEPENDENCIES
                    dvipng: no
               ghostscript: no
                     latex: no
                   pdftops: no

    OPTIONAL PACKAGE DATA
                      dlls: no  [skipping due to configuration]

    ============================================================================
                            * The following required packages can not be built:
                            * freetype, png
                            * Please check http://gnuwin32.sourceforge.net/packa
                            * ges/freetype.htm for instructions to install
                            * freetype
                            * Please check http://gnuwin32.sourceforge.net/packa
                            * ges/libpng.htm for instructions to install png
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by alievk** [comment]
It says
```
DirectoryNotACondaEnvironmentError: The target directory exists, but it is not a conda environment.
Use 'conda create' to convert the directory to a conda environment.
target directory: C:\Users\anbanglee\miniconda3\envs\avatarify
```

Please swipe off `C:\Users\anbanglee\miniconda3\envs\avatarify`and try again.

**Comment by alievk** [comment]
Also please warp you logs in between ```

**Comment by jackylee1** [comment]
thank you

**Comment by E3V3A** [comment]
Maybe close issue, since no response in >5 days. 
Also useful to add a tag like: `need-author-feedback`.

**Comment by alievk** [comment]
Next time any issue titled like "please help" will be immediately closed :)
