### ISSUE TITLE
Failed loading checkloints

### ISSUE THREAD

**Issue by AT4-CGSG** [alievk/avatarify#17]
Creating virtual camera (this may require sudo password once after reboot)
Could not find conda environment: avatarify
You can list all discoverable environments with `conda info —envs`.

Running Avatarify (may take some while for the first time)...
ffmpeg version 3.4.6-0ubuntu0.18.04.1 Copyright (c) 2000-2019 the FFmpeg developers
 built with gcc 7 (Ubuntu 7.3.0-16ubuntu3)
 configuration: —prefix=/usr —extra-version=0ubuntu0.18.04.1 —toolchain=hardened —libdir=/usr/lib/x86_64-linux-gnu —incdir=/usr/include/x86_64-linux-gnu —enable-gpl —disable-stripping —enable-avresample —enable-avisynth —enable-gnutls —enable-ladspa —enable-libass —enable-libbluray —enable-libbs2b —enable-libcaca —enable-libcdio —enable-libflite —enable-libfontconfig —enable-libfreetype —enable-libfribidi —enable-libgme —enable-libgsm —enable-libmp3lame —enable-libmysofa —enable-libopenjpeg —enable-libopenmpt —enable-libopus —enable-libpulse —enable-librubberband —enable-librsvg —enable-libshine —enable-libsnappy —enable-libsoxr —enable-libspeex —enable-libssh —enable-libtheora —enable-libtwolame —enable-libvorbis —enable-libvpx —enable-libwavpack —enable-libwebp —enable-libx265 —enable-libxml2 —enable-libxvid —enable-libzmq —enable-libzvbi —enable-omx —enable-openal —enable-opengl —enable-sdl2 —enable-libdc1394 —enable-libdrm —enable-libiec61883 —enable-chromaprint —enable-frei0r —enable-libopencv —enable-libx264 —enable-shared
 libavutil 55. 78.100 / 55. 78.100
 libavcodec 57.107.100 / 57.107.100
 libavformat 57. 83.100 / 57. 83.100
 libavdevice 57. 10.100 / 57. 10.100
 libavfilter 6.107.100 / 6.107.100
 libavresample 3. 7. 0 / 3. 7. 0
 libswscale 4. 8.100 / 4. 8.100
 libswresample 2. 9.100 / 2. 9.100
 libpostproc 54. 7.100 / 54. 7.100
0: ./avatars/einstein.jpg
1: ./avatars/eminem.jpg
2: ./avatars/jobs.jpg
3: ./avatars/mona.jpg
4: ./avatars/obama.jpg
5: ./avatars/potter.jpg
6: ./avatars/ronaldo.png
7: ./avatars/schwarzenegger.png
load checkpoints..
cam_fomm.py:26: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
 config = yaml.load(f)
Traceback (most recent call last):
 File "cam_fomm.py", line 189, in <module>
 generator, kp_detector = load_checkpoints(config_path=opt.config, checkpoint_path=opt.checkpoint, device=device)
 File "cam_fomm.py", line 36, in load_checkpoints
 checkpoint = torch.load(checkpoint_path, map_location=device)
 File "/home/iamtheuser/anaconda3/lib/python3.7/site-packages/torch/serialization.py", line 526, in load
 if _is_zipfile(opened_file):
 File "/home/iamtheuser/anaconda3/lib/python3.7/site-packages/torch/serialization.py", line 76, in _is_zipfile
 if ord(magic_byte) != ord(read_byte):
TypeError: ord() expected a character, but string of length 0 found

**Comment by AT4-CGSG** [comment]
I've located vox-adv-cpk.pth.tar into avatarify folder. Am I right?

**Comment by alievk** [comment]
Looks like your file is corrupted , please check md5sum:
`46b26eabacbcf1533ac66dc5cf234c5e  vox-adv-cpk.pth.tar`

**Comment by AT4-CGSG** [comment]
Yes, that was it. Fixed
