### ISSUE TITLE
How run "remote GPU" on Widows?

### ISSUE THREAD

**Issue by Rohlik** [alievk/avatarify#170]
**Describe the bug**

According to a new feature "Remote GPU" I would like to know how I can run Avatarify server on my Windows and connect to it from another PC with Linux/Debian.
I read this arcticle https://github.com/alievk/avatarify/wiki/Remote-GPU and there is mentioned `--no-vcam` parameter but this parameter **is not functional** on `install_windows.bat`.

**Info (please complete the following information):**
 - OS (e.g., Linux): Windows 8.1
 - GPU model: NVIDIA GeForce RTX 2060

**Comment by alievk** [comment]
Just drop `--no-vcam` option, it's for Linux.

**Comment by Rohlik** [comment]
Thank you so much for updating the docs/wiki. I followed your recommendation, but I hit on another problem. If I run `run_windows.bat` on Windows server I got this error:

```
(avatarify) C:\Users\Rohlik\avatarify>run_windows.bat
Loading Predictor
C:\Users\Rohlik\avatarify\afy\predictor_local.py:34: YAMLLoadWarning: calling ya
ml.load() without Loader=... is deprecated, as the default Loader is unsafe. Ple
ase read https://msg.pyyaml.org/load for full details.
  config = yaml.load(f)
Key 1: ./avatars\einstein.jpg
Key 2: ./avatars\eminem.jpg
Key 3: ./avatars\jobs.jpg
Key 4: ./avatars\mona.jpg
Key 5: ./avatars\obama.jpg
Key 6: ./avatars\potter.jpg
Key 7: ./avatars\ronaldo.png
Key 8: ./avatars\schwarzenegger.png
Traceback (most recent call last):
  File "afy/cam_fomm.py", line 155, in <module>
    cap = VideoCaptureAsync(opt.cam)
  File "C:\Users\Rohlik\avatarify\afy\videocaptureasync.py", line 17, in __init_
_
    raise RuntimeError("Cannot open camera. Try to choose other CAMID in './scri
pts/settings.sh'")
RuntimeError: Cannot open camera. Try to choose other CAMID in './scripts/settin
gs.sh'
```

I do not have camera on server, that camera is present on client side.

**Comment by Rohlik** [comment]
You did another changes in documentation and it works! Thank you ;-)
