### ISSUE TITLE
No module named 'afy'

### ISSUE THREAD

**Issue by dev1729** [alievk/avatarify#171]
Iam getting this error while running run_windows.bat

  File "afy/cam_fomm.py", line 10, in <module>
    from afy.videocaptureasync import VideoCaptureAsync
ModuleNotFoundError: No module named 'afy'

**Comment by alievk** [comment]
What if you pull the latest version?

**Comment by dev1729** [comment]
> What if you pull the latest version?

It worked . Thanks for helping.
