### ISSUE TITLE
No module names "modules"

### ISSUE THREAD

**Issue by dev1729** [alievk/avatarify#172]
I got following error after running run_windows.bat

(avatarify) C:\Users\venkat sai\avatarify>run_windows.bat
Loading Predictor
Traceback (most recent call last):
  File "afy/cam_fomm.py", line 132, in <module>
    from afy import predictor_local
  File "C:\Users\venkat sai\avatarify\afy\predictor_local.py", line 4, in <module>
    from modules.keypoint_detector import KPDetector
ModuleNotFoundError: No module named 'modules.keypoint_detector'; 'modules' is not a package

**Comment by EinderJam** [comment]
I had the same issue after pulling yesterday, solved the issue by deleting the repo and re-cloning / re-running install_windows.bat

**Comment by dev1729** [comment]
Tried  deleting the repo and re-cloning / re-running install_windows.bat
 New error popped up
  File "afy/cam_fomm.py", line 136, in <module>
    from afy import predictor_local
  File "C:\Users\venkat sai\avatarify\afy\predictor_local.py", line 8, in <module>
    import face_alignment
ModuleNotFoundError: No module named 'face_alignment'


Iam using anaconda3 command prompt instead of miniconda?
Is that a problem?

**Comment by dev1729** [comment]
> I had the same issue after pulling yesterday, solved the issue by deleting the repo and re-cloning / re-running install_windows.bat

It worked .Thanks for your help .

**Comment by herryzhang** [comment]
I had the same issue just now,and I had deleting the repo and re-cloing/re-running install_windows.bat,but the same error happen,can everyone get this error
