### ISSUE TITLE
Could not connect to gpu_server_address:5556

### ISSUE THREAD

**Issue by kholmatov** [alievk/avatarify#173]
How to run a remote GPU on Mac ?
`kholmatov:avatarify kholmatov$ bash run_mac.sh --worker-host gpu_server_address
Loading Predictor
Could not connect to gpu_server_address:5556`

**Comment by alievk** [comment]
Hi, you have to deploy Avatarify on a dedicated server and connect to it by replacing `gpu_server_address` by its IP address or the DNS name.

https://github.com/alievk/avatarify/wiki/Remote-GPU

**Comment by kholmatov** [comment]
Спасибо за ответ, вот мне еще интересно минимум какая характеристика компьютера и видео карты  нужно чтоб, avatarify сработало?
