### ISSUE TITLE
This is a problem, I can't run the run_windows.bat through the miniconda 

### ISSUE THREAD

**Issue by SPekkOPs1** [alievk/avatarify#175]
"Missing required dependencies {0}".format(missing_dependencies))
ImportError: Missing required dependencies ['pytz']
![ssdw](https://user-images.githubusercontent.com/65247754/81727500-bcfbaa80-9491-11ea-9f14-5509c4512e80.PNG)

This is the error message, I have installed everything and did everything as the video guide showed... And I still have a problem that I can't fix.

EDIT:
I installed a VM to see if it's a problem with my PC or if I installed something not right, and guess what? It doesn't work on my VM either.

**Comment by E3V3A** [comment]
>  I have installed everything and did everything as the video guide showed

No you didn't. You didn't activate the conda environment, and AFAICT you didn't run the installation script either, which is why we ask you to provide the log and outputs in the very issue template text. (Why didn't you do that?)

**Comment by SPekkOPs1** [comment]
> > I have installed everything and did everything as the video guide showed
> 
> No you didn't. You didn't activate the conda environment, and AFAICT you didn't run the installation script either, which is why we ask you to provide the log and outputs in the very issue template text. (Why didn't you do that?)

I don't understand what I did wrong? Could you guide me to do fix it?

**Comment by SPekkOPs1** [comment]
OH, I fixed the problem I just had to activate the environment that's all but it won't open the app because it says "Try using another CAMID" I have tried to use different CAMID's but nothing helps.
