### ISSUE TITLE
contrib/jetsontx2 build fails with http error

### ISSUE THREAD

**Issue by gusev-genotek** [alievk/avatarify#179]
**Describe the bug**
bash scripts/install_jetson.sh fails with request.exceptions.HTTPError: 404 Client Error: Not Found for url: https://pypi.org/simple/uff/
**To Reproduce**

**Info (please complete the following information):**
 - OS (e.g., Linux): Jetson Nano
 - GPU model:

**Comment by alievk** [comment]
@SVL101

**Comment by JohanAR** [comment]
Closing issue since poster did not provide the requested info within 6 months
