### ISSUE TITLE
Nvidia Jetson Nano Port

### ISSUE THREAD

**Issue by umgefahren** [alievk/avatarify#185]
Wouldn't it be amazing, if you could run avatarify on a Nvidia Jetson and your main Computer still has it's full resources available? I would like to make that port, but first you probably have to abolish miniconda, as its not available on ARM.

**Comment by alievk** [comment]
We have a [branch](https://github.com/alievk/avatarify/tree/contrib/jetsontx2 ) with Jetson TX2 support.

You may also consider running in [Google Colab](https://colab.research.google.com/github/alievk/avatarify/blob/master/avatarify.ipynb) if you want to offload the heavy work to a remote GPU.

**Comment by umgefahren** [comment]
Branch is probably doing it
