### ISSUE TITLE
No module name 'modules' in Ubuntu 16.04

### ISSUE THREAD

**Issue by mikmeng** [alievk/avatarify#187]
root@fake-server:/opt/avatarify# ./run.sh
Creating virtual camera /dev/video9 (sudo privelege required)
modprobe: FATAL: Module v4l2loopback not found in directory /lib/modules/4.4.0-179-generic
[1590488734.601980] Loading Predictor
Traceback (most recent call last):
  File "afy/cam_fomm.py", line 175, in <module>
    from afy import predictor_local
  File "/opt/avatarify/afy/predictor_local.py", line 4, in <module>
    from modules.keypoint_detector import KPDetector
ModuleNotFoundError: No module named 'modules'

I try to re-clone the new codes, but the error has happen.
Can everyone help me? Thank you!

**Comment by alievk** [comment]
1. Where there any errors during installation? I see v4l2loopback is not found, it means it was not able to compile and install during the installation.
2. It can't find modules from fomm module. Are you sure it was cloned during the installation? Please check whether it's in the avatarify folder.
3. Generally it's not a good practice to run user scripts with root privilege.
