### ISSUE TITLE
CamTwist - no python (avatarify) menu item in drop-down

### ISSUE THREAD

**Issue by tekumara** [alievk/avatarify#193]
**Describe the bug**

I'm running the colab notebook. Local I run:
```
$ ./run_mac.sh --is-client --in-addr tcp://0.tcp.au.ngrok.io:15281 --out-addr tcp://0.tcp.au.ngrok.io:17440

[1591011677.072708] Loading Predictor
[1591011679.044118] Sending to tcp://0.tcp.au.ngrok.io:15281
[1591011679.045856] Receiving from tcp://0.tcp.au.ngrok.io:17440
[1591011679.048572] SEND 1.388 (1.388)

```

I start CamTwist, click Desktop+, press Select, and in the Settings section choose Confine to Application Window.

But in the dropdown under "Select from existing windows" there is no python (avatarify) menu item.

**To Reproduce**

**Info (please complete the following information):**
 - OS (e.g., Linux): macOS Catalina 10.15.4 (19E287)
 - GPU model: none

 - Any other relevant information: 

**Screenshots**

<img width="951" alt="camtwist window" src="https://user-images.githubusercontent.com/125105/83406141-5abf1580-a451-11ea-9a5d-1b587c76046d.png">

**Logs**

**Comment by alievk** [comment]
Hi @tekumara , do you have the two windows (your webcam and avatar image) after running the `run_mac.sh` command?

**Comment by alekao** [comment]
I encountered similar issues. Occasionally a window(python(cam) window) would pop up after running the `run_mac.sh` command, but most of the times nothing happens. And when the python(cam) window shows up, no more window would pop after selecting python(cam) in the dropdown menu in CamTwist. 

Info:
OS : macOS Catalina 10.15.4
GPU : None


I saw the following messages after the python(cam) window shows up. I am assuming `Virtual  camera streaming will be disabled` explains why it is not working?
```
[1591040447.287081] Virtual camera is supported only on Linux.
[1591040447.287124] Virtual camera streaming will be disabled.
[1591040447.288506] SEND 0.157 (0.225)		
[1591040450.843311] RECV 498.402 (261.813)		
[1591040450.843484] PACK 0.281 (0.269)		UNPACK 0.084 (0.065)		
[1591040450.845031] SEND 0.194 (0.214)
```

**Comment by alievk** [comment]
@alekao Are you able drive an avatar? Does the `avatarify` window appear when you hit X key (calibrate the face pose)? I see from your log that you have a connection with the rendering server.

We have a virtual camera built-in support only for Linux, that's why it say it's not supported on Mac. For Mac you have to use a 3rd party app like CamTwist to be able to capture the `avatarify` window and stream it to Zoom etc.

**Comment by alekao** [comment]
@alievk Update. 
For some reasons, I am now able to have the `avatarify` window appear after I hit X key (which in all my previous attempts the python(cam) just froze when I did that, and I have been following the same procedure) 
However, I don't see the avatarify camera option in Zoom after the two windows show up and I confine CamTwist to python(avatarify). 

I am using Zoom 5.0.4, because
1. all Zoom applications are forced to update to version 5.0 or higher after May 30th, 2020
2. Virtual camera is re-enabled on version 5.0.4

Zoom update: https://support.zoom.us/hc/en-us/articles/201361963-New-updates-for-macOS

But as I previously mentioned, I still don't see the avatarify camera option in Zoom. Any idea on how I can fix that?
Thanks

**Comment by ChandlerXF** [comment]
> **Describe the bug**
> 
> I'm running the colab notebook. Local I run:
> 
> ```
> $ ./run_mac.sh --is-client --in-addr tcp://0.tcp.au.ngrok.io:15281 --out-addr tcp://0.tcp.au.ngrok.io:17440
> 
> [1591011677.072708] Loading Predictor
> [1591011679.044118] Sending to tcp://0.tcp.au.ngrok.io:15281
> [1591011679.045856] Receiving from tcp://0.tcp.au.ngrok.io:17440
> [1591011679.048572] SEND 1.388 (1.388)
> ```
> 
> I start CamTwist, click Desktop+, press Select, and in the Settings section choose Confine to Application Window.
> 
> But in the dropdown under "Select from existing windows" there is no python (avatarify) menu item.
> 
> **To Reproduce**
> 
> **Info (please complete the following information):**
> 
> * OS (e.g., Linux): macOS Catalina 10.15.4 (19E287)
> * GPU model: none
> 
> * Any other relevant information:
> 
> **Screenshots**
> 
> <img alt="camtwist window" width="951" src="https://user-images.githubusercontent.com/125105/83406141-5abf1580-a451-11ea-9a5d-1b587c76046d.png">
> 
> **Logs**

same problem here, with macOS Mojave MBP2019

**Comment by mei-chen** [comment]
@tekumara I had the exact same issue, then I realized I had my {in_addr} and {out_addr} switched. 
`./run_mac.sh --is-client --in-addr {in_addr} --out-addr {out_addr}`
Make sure the order is correct by executing the print command on colab, and give it a second for the camera to be detected. Let us know if this helps!

**Comment by tekumara** [comment]
I tried again using the `ap` region in the colab notebook at it seemed to work. Maybe it was that or maybe I did something else wrong the first time.

I had to wait a minute or two before the cam window appeared.

**Comment by vivek737** [comment]
I have a similar issue  - I am running the client on MacOS (High Sierra)  and the server on an AWS GPU box. 

The client logs as below: 

```
bash run_mac.sh --is-client --in-addr tcp://ec2-public-ip.compute-1.amazonaws.com:5557 --out-addr tcp://ec2-public-ip.compute-1.amazonaws.com:5558

(base) ➜  avatarify git:(master) ✗ bash run_mac.sh --is-client --in-addr tcp://ec2-public-ip.compute-1.amazonaws.com:5557 --out-addr tcp://ec2-public-ip.compute-1.amazonaws.com:5558
[1592364193.133926] Loading Predictor
[1592364193.134321]  send {'name': '__init__', 'critical': True, 'id': 0}
[1592364193.215899] Sending to tcp://ec2-public-ip.compute-1.amazonaws.com:5557
[1592364193.216972] Receiving from tcp://ec2-public-ip.compute-1.amazonaws.com:5558
[1592364193.219758] SEND 0.651 (0.651)		
```

Even with verbose on -- not much to go by. 

In trying to debug - I was able to bypass all the glue from the run_mach.sh and directly run 
```
python afy/cam_fomm.py --config "$CONFIG" --checkpoint "$CKPT" --relative --adapt_scale --no-pad --is-client --in-addr tcp://ec2-xxxx.compute-1.amazonaws.com:5557 --out-addr tcp://ec2-xxxx.compute-1.amazonaws.com:5558 --verbose
```

but got the same output.

When I run camera_selector.py directly -- it does pop a window (but doesn't actuallly activate the camera) and the selector window dies once i click on it. Attached the log here.
[camera_selector_log.txt](https://github.com/alievk/avatarify/files/4790375/camera_selector_log.txt)

The individual log files under /var/log/* don't have more than 1-2 lines of info. 

Please assist or suggest a debugging way forward.

**Comment by ankh2054** [comment]
Hi all im having the same issue on Mac OSX Catalina.

I am running a docker instance on linux ubuntu 18.04 with Nvidia drivers as my GPU server.

```
Creating virtual camera /dev/video9 (sudo privelege required)
modprobe: FATAL: Module v4l2loopback not found in directory /lib/modules/4.15.0-106-generic
[1594890563.175341] Loading Predictor
/usr/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
[1594890564.311871] Receiving on port 5557
[1594890564.317824] Sending on port 5558
/app/avatarify/afy/predictor_local.py:34: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  config = yaml.load(f)
Downloading: "https://www.adrianbulat.com/downloads/python-fan/s3fd-619a316812.pth" to /root/.torch/models/s3fd-619a316812.pth
100%|###########################################################################################| 89843225/89843225 [00:07<00:00, 11702810.93it/s]
Downloading: "https://www.adrianbulat.com/downloads/python-fan/2DFAN4-11f355bf06.pth.tar" to /root/.torch/models/2DFAN4-11f355bf06.pth.tar
100%|###########################################################################################| 95641761/95641761 [00:08<00:00, 11566933.10it/s]
[1594891507.171516] Initialized predictor with: [[], {'config_path': 'fomm/config/vox-adv-256.yaml', 'checkpoint_path': 'vox-adv-cpk.pth.tar', 'relative': True, 'adapt_movement_scale': True, 'enc_downscale': 1}]
```


On my MAC I run the following:

```
./run_mac.sh --is-client --in-addr tcp://x.x.x.x:5557 --out-addr tcp://x.x.x.x:5558
[1594892406.238340] Loading Predictor
[1594892406.288199] Receiving from tcp://90.152.22.234:5558
```

No additional windows are opening. 

Any ideas? Im wondering whether its my container because of the ```modprobe: FATAL: Module v4l2loopback not found in directory /lib/modules/4.15.0-106-generic```

**Comment by ankh2054** [comment]
I got mine working and I realised that my GPU server needed port 5558 and port 5557 open it seemed. Anyways after making those changes the camera's popped up. Its so good!

**Comment by James65780166666** [comment]
![IMG_20230110_175053_979](https://user-images.githubusercontent.com/122387645/211618048-eb13cbc8-1aa5-4a6b-bdc5-c70022b61b45.jpg)
Please how do i go about this error

**Comment by James65780166666** [comment]
Please 🙏

**Comment by eodirah** [comment]
I have same issues but I have the two windows open but when I try to use the zoom or Skype I find that Amit shows my terminal as I'm running on colab with safari or Firefox. From the drop-down I only say terminal avatarify and safari avatarify colab but the two keep showing my laptop camera, what can I do to solve it
