### ISSUE TITLE
One Windows

### ISSUE THREAD

**Issue by herryzhang** [alievk/avatarify#195]
![image](https://user-images.githubusercontent.com/8223359/83602925-0c6f5b00-a5a6-11ea-888f-7e443013d223.png)
Why I only have one Windows

**Comment by mitya12342** [comment]
Fit face in rectangle
Then press X

**Comment by herryzhang** [comment]
thanks，i work it out

**Comment by alievk** [comment]
The title of this issue reminded me the Queen's song One Vision.

**Comment by JohanAR** [comment]
Closing since poster said it is working
