### ISSUE TITLE
Support for google meets

### ISSUE THREAD

**Issue by smuryginim** [alievk/avatarify#20]
Hello! Is it possible to add support for google meets?

**Comment by idovgalyov-4xxi** [comment]
Surprisingly I found that it works pretty fine with Google Meets (tried on Ubuntu, no special actions except from choosing the camera).

**Comment by idhamari** [comment]
In my case, it does not work on google meet or bbb. I am using Ubuntu.

**Comment by JohanAR** [comment]
avatarify-python uses v4l2loopback, and to my understanding it should appear the same as a physical video device in most regards. The only reasons for not working that I can think of are if that particular app doesn't support the video encoding being used, or if that app is actively trying to block potentially altered video streams

@idhamari have you verified that avatarify-python works with other applications? Have you tried a different web browser to run google meets?

**Comment by idhamari** [comment]
@JohanAR thanks for the info,  it works on skype on skype without a problem. It does not work on bbb, google-meet nor OBS studio.

**Comment by JohanAR** [comment]
@idhamari I just tested, and it works in OBS 25.0.3+dfsg1-2 for me, though I'm on Xubuntu 20.04. I'm running avatarify in docker btw

![obs-Screenshot_2021-04-06_13-24-37](https://user-images.githubusercontent.com/4918549/113704037-e93c9d00-96db-11eb-9053-a8d21dad4d11.png)

do you have the correct v4l2loopback installed? i.e. the one that you clone and build yourself (see scripts/install_docker.sh)

Other v4l-related packages I have installed, which may or may not be relevant:
```
/m/n/P/avatarify ❯❯❯ dpkg -l | grep v4l                                                                                                                                                           master 1✱ 16◼
ii  libv4l-0:amd64                                              1.18.0-2build1                                              amd64        Collection of video4linux support libraries
ii  libv4l-0:i386                                               1.18.0-2build1                                              i386         Collection of video4linux support libraries
ii  libv4l2rds0:amd64                                           1.18.0-2build1                                              amd64        Video4Linux Radio Data System (RDS) decoding library
ii  libv4lconvert0:amd64                                        1.18.0-2build1                                              amd64        Video4linux frame format conversion library
ii  libv4lconvert0:i386                                         1.18.0-2build1                                              i386         Video4linux frame format conversion library
ii  v4l-utils                                                   1.18.0-2build1                                              amd64        Collection of command line video4linux utilities
```

**Comment by idhamari** [comment]
@JohanAR

> do you have the correct v4l2loopback installed? i.e. the one that you clone and build yourself (see scripts/install_docker.sh)

Yes.

I am not using docker. So probably there are some libraries missing.

**Comment by idhamari** [comment]
Update: just tested it again now and it works in skype, bbb, google-meet and OBS studio. I found out that I have to run the script and start the camera before running the applications. Thanks for your support!
