### ISSUE TITLE
Can not use 'self' in a static method

### ISSUE THREAD

**Issue by cclauss** [alievk/avatarify#202]
**Describe the bug**

A method named `print()` is a nasty idea anyway but on
https://github.com/alievk/avatarify/blob/master/afy/utils.py#L76 it is not possible to use `self` inside a static method which has no access to `self`.

flake8 testing of https://github.com/alievk/avatarify on Python 3.8.3

$ __flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics__
```
./afy/utils.py:76:26: F821 undefined name 'self'
        for fn, times in self.timing.items():
                         ^
1     F821 undefined name 'self'
1
```

**To Reproduce**

**Info (please complete the following information):**
 - OS (e.g., Linux): 
 - GPU model: 

 - Any other relevant information: 

**Screenshots**

**Logs**

**Comment by alievk** [comment]
Oh thanks, that's a legacy code actually :D
