### ISSUE TITLE
Windows10 : Virtual Cam is supported only on Linux

### ISSUE THREAD

**Issue by super-sachin** [alievk/avatarify#205]
When I am trying to run "run_windows.bat" file, im getting following -

[1591519690.945719] Virtual camera is supported only on Linux.
[1591519690.957750] Virtual camera streaming will be disabled.
![Screenshot (87)](https://user-images.githubusercontent.com/61700383/83964630-e90d1e80-a8cb-11ea-8d59-cd53c2158817.png)

**Comment by alievk** [comment]
This is a warning that virtual camera is not supported on Windows natively, you have to use OBS to enable virtual camera.
