### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by RajDeora** [alievk/avatarify#214]
./run_mac.sh --is-client --in-addr tcp://0.tcp.in.ngrok.io:12968 --out-addr tcp://0.tcp.in.ngrok.io:14640
  File "afy/cam_fomm.py", line 71
    images_list = sorted(glob.glob(f'{opt.avatars}/*'))
                                                    ^
SyntaxError: invalid syntax

**Comment by alievk** [comment]
Are you following the instructions from readme?
If yes, you should be using Python3, but this error shows you're using Python2. We can't help in cases when you don't follow the readme.

**Comment by RajDeora** [comment]
> Are you following the instructions from readme?
> If yes, you should be using Python3, but this error shows you're using Python2. We can't help in cases when you don't follow the readme.

Im using python 3.7.6 and following the readme as is this error showed up suddenly wasn't there before
