### ISSUE TITLE
run client command not working

### ISSUE THREAD

**Issue by sanskrity2611** [alievk/avatarify#218]
**Describe the bug**

**To Reproduce**

**Info (please complete the following information):**
 - OS (e.g., Linux): 
 - GPU model: 

 - Any other relevant information: 

**Screenshots**

**Logs**

**Comment by alievk** [comment]
Hi, please describe what are you doing.

**Comment by JohanAR** [comment]
Closing the issue since we never heard from poster again. Please feel free to re-open or create a new issue if the problem still exists
