### ISSUE TITLE
Not working on Mac

### ISSUE THREAD

**Issue by linchen111** [alievk/avatarify#22]
Traceback (most recent call last):
  File "cam_fomm.py", line 12, in <module>
    from sync_batchnorm import DataParallelWithCallback
ModuleNotFoundError: No module named 'sync_batchnorm'

so when I run bash run_mac.sh, errors are l get the error prompt shown above

**Comment by alievk** [comment]
sync_batchnorm is from fomm directory, please check it's there (should be cloned during installation)

**Comment by linchen111** [comment]
Thank！
This problem has been solved. But when I finally run code "bash run_mac.sh", the following error occurred:

[ERROR:0] global /Users/travis/build/skvark/opencv-python/opencv/modules/videoio/src/cap.cpp (193) open VIDEOIO(AVFOUNDATION): raised unknown C++ exception!
Cannot open camera. Try to choose other CAMID in './scripts/settings.sh'

I saw in this document that the camera code is 0, and my Mac only has one camera. So I don't know why it doesn't work

**Comment by karfly** [comment]
Hi, @linchen111!
Your computer can have some virtual cameras, so it's worth trying to check different values for `CAMID`.

**Comment by linchen111** [comment]
Thanks! 
CAMID=2 works for me.

**Comment by gautamkishore** [comment]
Worked for me too on macbook pro
CAMID=2

**Comment by ainmatter** [comment]
Hello! Having the camid issue, total noob here so forgive me, but in terminal do is the command to change the the camid just 'camid=2' ?

**Comment by xuf12** [comment]
> Hello! Having the camid issue, total noob here so forgive me, but in terminal do is the command to change the the camid just 'camid=2' ?

You need to modify the 3rd line in avatarify/scripts/settings.sh  
`CAMID=2`

**Comment by GuyMasonQA** [comment]
Having the same issue myself with this. Altered the settings file to use CAMID=2, even commented out the if statement, but every time it comes up with the following error:

> Traceback (most recent call last):
>   File "cam_fomm.py", line 264, in <module>
>     cap = VideoCaptureAsync(opt.cam)
>   File "/Users/guymason/Experiments/avatarify/videocaptureasync.py", line 17, in __init__
>     raise RuntimeError("Cannot open camera. Try to choose other CAMID in './scripts/settings.sh'")
> RuntimeError: Cannot open camera. Try to choose other CAMID in './scripts/settings.sh'

When I initially ran this, Mac OS requested for permission to the camera (which I granted immediately), so i'm not sure how it could be a permissions issue still. 

PS. I also only have a single web cam, running latest version of Mac OS, installed this application today (following the relevant instructions).

**Comment by lengain** [comment]
@GuyMasonQA  I also cached this。

> [ERROR:0] global /Users/travis/build/skvark/opencv-python/opencv/modules/videoio/src/cap.cpp (193) open VIDEOIO(AVFOUNDATION): raised unknown C++ exception!
> 
> 
> Traceback (most recent call last):
>   File "cam_fomm.py", line 232, in <module>
>     cap = VideoCaptureAsync(opt.cam)
>   File "/Users/shunlian/Documents/GitProject/avatarify/videocaptureasync.py", line 17, in __init__
>     raise RuntimeError("Cannot open camera. Try to choose other CAMID in './scripts/settings.sh'")
> RuntimeError: Cannot open camera. Try to choose other CAMID in './scripts/settings.sh'

**Comment by lengain** [comment]
@GuyMasonQA 
I alse catched this error

> [ERROR:0] global /Users/travis/build/skvark/opencv-python/opencv/modules/videoio/src/cap.cpp (193) open VIDEOIO(AVFOUNDATION): raised unknown C++ exception!
> 
> 
> Traceback (most recent call last):
>   File "cam_fomm.py", line 232, in <module>
>     cap = VideoCaptureAsync(opt.cam)
>   File "/Users/shunlian/Documents/GitProject/avatarify/videocaptureasync.py", line 17, in __init__
>     raise RuntimeError("Cannot open camera. Try to choose other CAMID in './scripts/settings.sh'")
> RuntimeError: Cannot open camera. Try to choose other CAMID in './scripts/settings.sh'

**Comment by lengain** [comment]
@GuyMasonQA 
Worked for me too on iMac
CAMID=2
