### ISSUE TITLE
Adding new avatar

### ISSUE THREAD

**Issue by shashanks33** [alievk/avatarify#233]
There are only 9 avatars set to use. Is there a way to add our own custom avatars to make them work?

**Comment by alievk** [comment]
Yes, and it's stated clearly in the readme
https://github.com/alievk/avatarify#setup-avatars
https://github.com/alievk/avatarify#controls

**Comment by rabimba** [comment]
> Yes, and it's stated clearly in the readme
> https://github.com/alievk/avatarify#setup-avatars
> https://github.com/alievk/avatarify#controls

After adding e new cropped picture. Do we need to do anything else?
It is not picking up the new avatar. Have cycled through all images and tried reloading avatars by "L". In Colab

**Comment by bobvo23** [comment]
You may have to restart the python scripts in the PC, so it will index the new avatar. Just keep colab running.

**Comment by rosebbb** [comment]
I guess they don't take 10 as a keyboard input. You can change the default avatar in the following line in the cam_form.py as follows:
cur_ava = 1 (change 1 to the value that corresponds to your new avatar. )

**Comment by rabimba** [comment]
> You may have to restart the python scripts in the PC, so it will index the new avatar. Just keep colab running.

In my computer, I am just running the client script. Right? Have already done that quite a few times before posting here.
And also also I have cycled through all avatars using the Next Avatar shortcut and didn't see the new ones.

How do we know which value corresponds to which avatar? We just put a new file in the avatar folder for it to index. We don't assign any value to it anywhere

**Comment by bobvo23** [comment]
Just put new files in it, the files are sorted by alphabet order.
May you try to crop, resize the new one to make it similar to current avatar (size, file type...)
