### ISSUE TITLE
Unable to run run_windows.bat cant open afy/cam_fomm.py

### ISSUE THREAD

**Issue by Jeffbr99** [alievk/avatarify#239]
I am trying to run the run_windows.bat and I receive this error
(base) PS C:\Users\27836> avatarify\run_windows.bat
'scripts' is not recognized as an internal or external command,
operable program or batch file.
python: can't open file 'afy/cam_fomm.py': [Errno 2] No such file or directory

**Info (please complete the following information):**
 - OS  Windows 10
 - GPU model: AMD Radeon R5

On Windows (Miniconda prompt) run:
conda activate avatarify
conda info
conda list
 active environment : avatarify
    active env location : C:\Users\27836\miniconda3\envs\avatarify
            shell level : 2
       user config file : C:\Users\27836\.condarc
 populated config files :
          conda version : 4.8.3
    conda-build version : not installed
         python version : 3.7.7.final.0
       virtual packages :
       base environment : C:\Users\27836\miniconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\27836\miniconda3\pkgs
                          C:\Users\27836\.conda\pkgs
                          C:\Users\27836\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\27836\miniconda3\envs
                          C:\Users\27836\.conda\envs
                          C:\Users\27836\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.8.3 requests/2.23.0 CPython/3.7.7 Windows/10 Windows/10.0.18362
          administrator : False
             netrc file : None
           offline mode : False

(avatarify) PS C:\Users\27836> conda list
# packages in environment at C:\Users\27836\miniconda3\envs\avatarify:
#
# Name                    Version                   Build  Channel
blas                      1.0                         mkl
blosc                     1.19.0               ha925a31_0    conda-forge
ca-certificates           2020.6.20            hecda079_0    conda-forge
certifi                   2020.6.20        py37hc8dfbb8_0    conda-forge
cffi                      1.14.0           py37h7a1dbc1_0
chardet                   3.0.4                    pypi_0    pypi
cloudpickle               0.5.3                    pypi_0    pypi
cuda100                   1.0                           0    pytorch
cycler                    0.10.0                   pypi_0    pypi
dask                      0.18.2                   pypi_0    pypi
decorator                 4.3.0                    pypi_0    pypi
face-alignment            1.0.0                    pypi_0    pypi
freetype                  2.10.2               hd328e21_0
icc_rt                    2019.0.0             h0cc432a_1
idna                      2.10                     pypi_0    pypi
imageio                   2.3.0                    pypi_0    pypi
intel-openmp              2020.1                      216
jpeg                      9b                   hb83a4c4_2
kiwisolver                1.0.1                    pypi_0    pypi
libpng                    1.6.37               h2a8f88b_0
libtiff                   4.1.0                h56a325e_1
lz4-c                     1.9.2                h62dcd97_0
matplotlib                2.2.2                    pypi_0    pypi
mkl                       2020.1                      216
mkl-service               2.3.0            py37hb782905_0
mkl_fft                   1.1.0            py37h45dec08_0
mkl_random                1.1.1            py37h47e9c7a_0
msgpack                   1.0.0                    pypi_0    pypi
msgpack-numpy             0.4.5                    pypi_0    pypi
networkx                  2.1                      pypi_0    pypi
ninja                     1.9.0            py37h74a9793_0
numpy                     1.15.0                   pypi_0    pypi
olefile                   0.46                     py37_0
opencv-python             4.2.0.34                 pypi_0    pypi
openssl                   1.1.1g               he774522_0    conda-forge
pandas                    0.23.4                   pypi_0    pypi
pillow                    6.2.2                    pypi_0    pypi
pip                       20.1.1                   py37_1
pycparser                 2.18                     pypi_0    pypi
pyfakewebcam              0.1.0                    pypi_0    pypi
pygit                     0.1                      pypi_0    pypi
pyparsing                 2.2.0                    pypi_0    pypi
python                    3.7.7                h81c818b_4
python-blosc              1.7.0            py37he774522_0
python-dateutil           2.7.3                    pypi_0    pypi
python_abi                3.7                     1_cp37m    conda-forge
pytorch                   1.0.0           py3.7_cuda100_cudnn7_1  [cuda100]  pytorch
pytz                      2018.5                   pypi_0    pypi
pywavelets                0.5.2                    pypi_0    pypi
pyyaml                    5.1                      pypi_0    pypi
pyzmq                     19.0.0                   pypi_0    pypi
requests                  2.23.0                   pypi_0    pypi
scikit-image              0.14.0                   pypi_0    pypi
scikit-learn              0.19.2                   pypi_0    pypi
scipy                     1.1.0                    pypi_0    pypi
setuptools                47.3.1                   py37_0
six                       1.11.0                   pypi_0    pypi
sqlite                    3.32.3               h2a8f88b_0
tk                        8.6.10               he774522_0
toolz                     0.9.0                    pypi_0    pypi
torchvision               0.2.1                      py_2    pytorch
tqdm                      4.24.0                   pypi_0    pypi
urllib3                   1.25.9                   pypi_0    pypi
vc                        14.1                 h0510ff6_4
vs2015_runtime            14.16.27012          hf0eaf9b_2
wheel                     0.34.2                   py37_0
wincertstore              0.2                      py37_0
xz                        5.2.5                h62dcd97_0
zlib                      1.2.11               h62dcd97_4
zstd                      1.4.4                ha9fde0e_3

**Comment by alievk** [comment]
Your working directory must be `avatarify` when running scripts.
