### ISSUE TITLE
>run_windows.bat can not open two windows and there are some errors.  How to set CAMID?

### ISSUE THREAD

**Issue by LimingGao** [alievk/avatarify#24]
[ WARN:1] global C:\projects\opencv-python\opencv\modules\videoio\src\cap_msmf.cpp (1113) SourceReaderCB::OnReadSample videoio(MSMF): OnReadSample() is called with error status: -2147024809
[ WARN:1] global C:\projects\opencv-python\opencv\modules\videoio\src\cap_msmf.cpp (1125) SourceReaderCB::OnReadSample videoio(MSMF): async ReadSample() call is failed with error status: -2147024809
[ WARN:0] global C:\projects\opencv-python\opencv\modules\videoio\src\cap_msmf.cpp (1159) CvCapture_MSMF::grabFrame videoio(MSMF): can't grab frame. Error: -2147024809
Can't receive frame (stream end?). Exiting ...
[ WARN:0] global C:\projects\opencv-python\opencv\modules\videoio\src\cap_msmf.cpp (674) SourceReaderCB::~SourceReaderCB terminating async callback

**Comment by alievk** [comment]
Looks like wrong webcam chosen, try another one changing CAMID in scripts\settings_windows.bat

**Comment by trover97** [comment]
![Снимок экрана (31)_LI](https://user-images.githubusercontent.com/53858027/79220592-f1615400-7e5c-11ea-80bc-3ca906630af2.jpg)
Do you mean this CAMID?

**Comment by Floory** [comment]
@alievk I installed everything according to the instructions, but when running on point 4, this error is returned

**Comment by alievk** [comment]
@trover97 CAMID is an index number like 0, 1, 2, ...
I don't know an easy way of getting this ID in Windows, so just try different IDs here https://github.com/alievk/avatarify/blob/master/scripts/settings_windows.bat#L2

**Comment by alievk** [comment]
@Floory you have to download model checkpoint https://github.com/alievk/avatarify#download

**Comment by Manuel2087** [comment]
> @Floory you have to download model checkpoint https://github.com/alievk/avatarify#download

I have the same issue and I downloaded model .

![image](https://user-images.githubusercontent.com/62082120/79602324-8192d980-80a7-11ea-8fea-8d6f8e3a4aa3.png)

**Comment by tengallontim** [comment]
You have to move the .tar file to your C:/Users/[YOUR USERNAME]/avatarify folder
