### ISSUE TITLE
Colab script not running

### ISSUE THREAD

**Issue by frosenhain** [alievk/avatarify#242]
**Describe the bug**
When trying to un the step # (Re)Start the worker you get an error stating:

FileNotFoundError                         Traceback (most recent call last)
<ipython-input-54-8aece2177ae8> in <module>()
      3   ps = Popen(
      4       shlex.split(f'./run.sh --is-worker --in-port {local_in_port} --out-port {local_out_port} --no-vcam --no-conda'),
----> 5       stdout=f, stderr=f)
      6   time.sleep(3)

1 frames
/usr/lib/python3.6/subprocess.py in _execute_child(self, args, executable, preexec_fn, close_fds, pass_fds, cwd, env, startupinfo, creationflags, shell, p2cread, p2cwrite, c2pread, c2pwrite, errread, errwrite, restore_signals, start_new_session)
   1362                         if errno_num == errno.ENOENT:
   1363                             err_msg += ': ' + repr(err_filename)
-> 1364                     raise child_exception_type(errno_num, err_msg, err_filename)
   1365                 raise child_exception_type(err_msg)
   1366 

FileNotFoundError: [Errno 2] No such file or directory: './run.sh': './run.sh'

**To Reproduce**
Run the colab script

**Info (please complete the following information):**
 - OS (e.g., Linux): Windows
 - GPU model: No GPU

 - Any other relevant information: 

**Screenshots**
![image](https://user-images.githubusercontent.com/11945292/86538289-8491af00-becb-11ea-997c-1b07a8f3eb14.png)

**Logs**

**Comment by alievk** [comment]
After some time, Colab removes downloaded files. Please re-run the notebook.

**Comment by frosenhain** [comment]
Excellent! Thank you very much!

**Comment by pulakmehta** [comment]
I'm facing the same issue and it is still not working.
