### ISSUE TITLE
Getting multiple cam windows opened while running run.sh 

### ISSUE THREAD

**Issue by shwetkanwal24** [alievk/avatarify#245]
I am on latest Ubuntu I have installed correctly and updated everything but when I run bash run.sh then it didn't. Run so I run with sudo bash run.sh  but so it sometime shows me avatar list to select and sometimes it open webcam and when I press X and configure my face than multiple cam windows start opening and I can't understand what's the issue and how to fix it please help me out

**Comment by shwetkanwal24** [comment]
![Uploading IMG_20200713_160929_1.jpg…]()

**Comment by shwetkanwal24** [comment]
I am on latest Ubuntu I have installed correctly and updated everything but when I run bash run.sh then it didn't. Run so I run with sudo bash run.sh but so it sometime shows me avatar list to select and sometimes it open webcam and when I press X and configure my face than multiple cam windows start opening and I can't understand what's the issue and how to fix it please help me out
![IMG_20200713_160929_1](https://user-images.githubusercontent.com/55040435/87300024-bc7f9e80-c52a-11ea-8bf0-08f8e960d2bf.jpg)

**Comment by shwetkanwal24** [comment]
I am on latest Ubuntu I have installed correctly and updated everything but when I run bash run.sh then it didn't. Run so I run with sudo bash run.sh but so it sometime shows me avatar list to select and sometimes it open webcam and when I press X and configure my face than multiple cam windows start opening and I can't understand what's the issue and how to fix it please help me out

**Comment by arunasank** [comment]
Seeing the same issue.

**Comment by abigflea** [comment]
Identical issue for me.

**Comment by mintmaker** [comment]
We added docker support, but I guess you're running it natively. I tried to run the version before the docker support and I get another error from Opencv. Could you please run`git checkout 56e8f6d` in the avatarify directory and then `bash run.sh`?

**Comment by alievk** [comment]
Hi, I've checked the latest commit on my Ubuntu 18.04, no issues. 

@shwetkanwal24 @arunasank @abigflea could you provide more information about your system?

**Comment by arunasank** [comment]
@mintmaker 
Seeing the same issue on that commit. I made sure to delete my conda environment, reinstall everything and test from scratch.

@alievk 
Running ubuntu 20.04, with the rest of the versions of v4l2loopback and other packages being the same as the recommended versions on the repository. Since it's an issue with the `cam` window (created by opencv in `afy/cam_fomm.py`), and what @mintmaker noticed, I wonder if it's an issue with opencv. I am also debugging and will post back findings here. If you all know exactly where to poke, do let us know.

**Comment by Paxy** [comment]
The same issue with Mint 20.
The problem is caused by line 423 at afy/cam_fomm.py. By commenting on the preview fucntion, new windows are not created.

**Comment by abigflea** [comment]
@alievk  Ubuntu 20.04 clean install, fully updated. Rx570.
Fresh install, followed the guide exactly. 
Reinstalled and tried it all again, same thing. looks very very similar to the post above.
need any other info to help?

**Comment by arunasank** [comment]
@Paxy that doesn't resolve the issue for me. 

I also tried commenting line 436, still no luck. The other problem is that the window with the avatar is blank now -- it no longer shows up w Einstein's face.

**Comment by arunasank** [comment]
UPDATE: Tried @Paxy's suggestion several times, and the development now is that I can't calibrate using the cam window at all. I simply press 'X' and then I am able to control the avatar, but it's a hit or miss depending on whether the camera is configured correctly. Does that give you more clues? @alievk @mintmaker

**Comment by shwetkanwal24** [comment]
> UPDATE: Tried @Paxy's suggestion several times, and the development now is that I can't calibrate using the `cam` window at all. The initial `cam` window that shows up, looks like the one in the above comment. I simply press 'X' and then I am able to control the avatar, but it's a hit or miss depending on whether the camera is configured correctly. Does that give you more clues? @alievk @mintmaker

same happened with me too unable to solve the issue yet please help devs

**Comment by sanchitjain04** [comment]
Similar issue with me opening several window after pressing X on input camera window.

![SS](https://user-images.githubusercontent.com/38455473/87533829-cfbd7600-c6b2-11ea-9407-1292126c7b3a.png)


System configuration:
 
OS: Ubuntu 18.04.3 LTS
Processor: intel core i7 - 7700 CPU @ 3.60 GHZ x 8
Graphics: GeForce GTX 1070Ti/PCIe/SSE2
OS type: 64 bit

**Comment by mintmaker** [comment]
Line 423 controls the preview and normally it should only yield one output window, I guessed it's because of an opencv update. After downgrading to opencv-python=4.2.0.34 (which was installed before the issue; it was cached so I must have installed it already sometime). Now everything works fine for me (I actually got another error from opencv but I didn't care because I normally use Docker).
@alievk I'll try to fix these dependencies.

**Comment by mintmaker** [comment]
@alievk Adding 
```opencv-python==4.2.0.34``` in requirements.txt
resolves the error. Please also add this in the dockertag.
@all the others please add the above mentioned line to requirements.txt and run the install script again. This should resolve the error for you.

**Comment by alievk** [comment]
> @alievk Adding
> `opencv-python==4.2.0.34` in requirements.txt
> resolves the error. Please also add this in the dockertag.
> @ all the others please add the above mentioned line to requirements.txt and run the install script again. This should resolve the error for you.

Done!

**Comment by arunasank** [comment]
@mintmaker! ah fantastic. Thank you so much. I tried messing with the opencv versions in the requirements_client.txt. This resolves the issue for me. Thank you so much for the quick maintenance time, folks. You are heroes! : D

![](https://media.giphy.com/media/KAq7hfwvKFZnoip8TO/giphy.gif)

**Comment by shwetkanwal24** [comment]
> @alievk Adding
> `opencv-python==4.2.0.34` in requirements.txt
> resolves the error. Please also add this in the dockertag.
> @ all the others please add the above mentioned line to requirements.txt and run the install script again. This should resolve the error for you.

Thanks buddy for helping issue is solved I was thinking of same thing about open cv :)
