### ISSUE TITLE
Any possible get a higher resolution output?

### ISSUE THREAD

**Issue by breakstring** [alievk/avatarify#246]
The output windows looks have a very low resolution.  I know that the theory is totally different with normal video/pic editor. But still want know if there any possible to get a higher resolution output windows via tune some parameters (maybe with a high performance manchine/GPU)?

**Comment by alievk** [comment]
It's possible to get higher resolution, you need to re-train the model with images with bigger size and expect performance drop. Please refer to FOMM repository for details.

**Comment by breakstring** [comment]
Thanks for your reply.
