### ISSUE TITLE
can't find avatar for streaming

### ISSUE THREAD

**Issue by YouWu3** [alievk/avatarify#25]
My avatarify works well without streaming, but can't be found on skypes, Microsoft teams or slacks:
![image](https://user-images.githubusercontent.com/28369350/79199500-f2a56900-7de9-11ea-9516-eca36e59679c.png)
Only one camera can be found, any clue?

**Comment by alievk** [comment]
What does `v4l2-ctl --list-devices` show?

**Comment by YouWu3** [comment]
![image](https://user-images.githubusercontent.com/28369350/79206347-0d7cdb00-7df4-11ea-8575-33934f87bfab.png)
Also, I modified run.sh to device 9:
FF_CMD="ffmpeg -re -i pipe:0 -vf format=pix_fmts=yuv420p -f v4l2 /dev/video9"
and I changed stdout to strerr in cam_fomm.py
Before that I got "broke pipeline" error, now it works, just can't be found in streaming

**Comment by alievk** [comment]
Closing this issue since ffmpeg piping is now replaced with pyfakewebcam.

Please update to the latest version.
