### ISSUE TITLE
please add dropbox link for vox-cpk.pth.tar file

### ISSUE THREAD

**Issue by fajrulfnf** [alievk/avatarify#254]
Hi, I've this "download quota exceeded" problem when trying to download this file. So can you please add dropbox link for **vox-cpk.pth.tar** file? Thanks in advance

**Comment by bobvo23** [comment]
Dropbox is good for me now. May you please check again?
How about the Gdrive link?

**Comment by fajrulfnf** [comment]
> Dropbox is good for me now. May you please check again?
> How about the Gdrive link?

Nevermind i just figure out the solution. So when the download quota exceed from Aliaksandr's gdrive, I just have to make a copy of the file > it'll automatically move to your own gdrive folder > then rename it to the original file name > and it just works. I don't even have to download and upload it to my gdrive.
