### ISSUE TITLE
It would be nice if we had an option to remove the red square from the original cam?

### ISSUE THREAD

**Issue by pjsjongsung** [alievk/avatarify#255]
So I noticed some(maybe all) webcams do not support multiple programs using the video. Thus, if you wanted to show both your real face and your fake face, you would have to show the one with the red square. Maybe an option(a hot key?) to remove the red square might be nice?

Just a suggestion. Love your work!

**Comment by mintmaker** [comment]
If you want to show your real face just type "0" (as written in the manual).

**Comment by pjsjongsung** [comment]
But that would have two cams with my face with red square/face with no red square. I'm suggesting a way to have two cams with my face with no red square/fake face.

**Comment by mintmaker** [comment]
Yes, you'll always see two windows (one the actual image, the other one the streamed one). I don't really understand what you want.

**Comment by pjsjongsung** [comment]
Apologies if I'm bad at explaining.
I was hoping for a hotkey to remove the red square from the actual image, so I can use both the original cam and streamed cam side by side.

**Comment by mintmaker** [comment]
The red square is never streamed. So if you press 0 the others will see your actual face (maybe just a bit cropped).
P.S.: I may just be bad at understanding lol

**Comment by pjsjongsung** [comment]
Ok. Now I understand what's happening.
So I wanted to stream both the original cam and the output of the model cam side by side.

So not;
output cam -> press 0 -> original cam

but like;
original cam with no red square & output cam in the same screen

so two cams each having the original cam and output cam
instead of one cam which can change back and forth

**Comment by mintmaker** [comment]
You mean a screen recording?
Tbh, I don't think many will use this, so I wouldn't think we should make a pull request, but you can:
1. Go into the avatarify folder on your local computer, from there go into the afy folder and open cam_fomm.py in a text editor, then go to line [421](https://github.com/alievk/avatarify/blob/master/afy/cam_fomm.py#L421). Click before the first character and write now "pass # " (without the quotes). Then save with Control+S. Now the rectangle shouldn't be rendered.

**Comment by pjsjongsung** [comment]
Thank you! :) I'll go with that.
