### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'ndim'

### ISSUE THREAD

**Issue by ChebyrashkaARDM** [alievk/avatarify#259]
(avatarify) C:\Users\USER\DeepFake\avatarify>run_windows.bat
[1596712401.470741] Loading Predictor
C:\Users\USER\DeepFake\avatarify\afy\predictor_local.py:34: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  config = yaml.load(f)
Traceback (most recent call last):
  File "afy/cam_fomm.py", line 206, in <module>
    avatars, avatar_names = load_images()
  File "afy/cam_fomm.py", line 75, in load_images
    if img.ndim == 2:
**AttributeError: 'NoneType' object has no attribute 'ndim'**

(avatarify) C:\Users\USER\DeepFake\avatarify>

It was beginning after work in Google Colab

**Comment by alievk** [comment]
Shutdown the notebook and start again. Looks like some files where not downloaded.

**Comment by ChebyrashkaARDM** [comment]
Файлы не удалял, перезапускал в разное время довольно много раз. В итоге пару дней назад переустановил, все работает
