### ISSUE TITLE
conda not found

### ISSUE THREAD

**Issue by SiameseDerp** [alievk/avatarify#269]
Whenever I run `scripts\install_windows.bat` I get the message `conda not found. Please refer to the README and install Miniconda.` even though I have it installed

![screenshot](https://user-images.githubusercontent.com/55035871/90306977-405cdb80-de87-11ea-8ee9-a1cd0ff47075.png)

**Info:**
 - OS: Windows 10 (Build 19041.540)
 - GPU model: GTX 1070

**Comment by bobvo23** [comment]
For windows, it is very common that Conda is not added to PATH after installing.
Please add conda to path, and you should be good to go.:
For Windows
Go to Control Panel\System and Security\System\Advanced System Settings then look for Environment Variables.

Your user variables should contain Path=Path\to\Anaconda3\Scripts.

You need to figure where your Anaconda3 folder is (i.e. the path to this folder) . Mine was in C:\Users.

Reference: https://stackoverflow.com/questions/28612500/why-anaconda-does-not-recognize-conda-command/44575773#:~:text=You%20need%20to%20add%20conda,%2Fanaconda3%2Fbin%3A%24PATH%20.&text=When%20you%20install%20anaconda%20on,have%20to%20add%20it%20yourself.
