### ISSUE TITLE
Docker based setup

### ISSUE THREAD

**Issue by jeverling** [alievk/avatarify#27]
I don't know if it's even possible - there is the `--device` flag that allows a container to access devices like webcams: https://medium.com/@zwinny/docker-using-webcam-9fafb26cf1e6

But I'm not sure if it's possible for the host to access the virtual camera device if it's created inside a container.

But if possible, it would be cool to have this working as a Docker container, so you can just fire it up on a Linux based system without having to install anything into your host.

**Comment by jeverling** [comment]
Seems to be possible: https://elder.dev/posts/open-source-virtual-background/

**Comment by alievk** [comment]
@jeverling it would be great to have a Docker setup, indeed. However, not a critical issue at the moment.
Please let us know if you have some progress in this direction :)

**Comment by bijanmmarkes** [comment]
I think the hardest part about Dockerizing this specific application would be controlling the interactive keys.

With Docker, it's best to share the devices with the container rather than adding it to the python code.

**Comment by Rohlik** [comment]
I looking forward to see Docker support.

**Comment by mikaelhg** [comment]
See #224.

**Comment by mintmaker** [comment]
#224 solves this issue, but you still have to create the virtual camera outside the container

**Comment by mintmaker** [comment]
This can be closed now. #224 has been merged and supports running everything (server and client side, and running on the machine) dockerized.
