### ISSUE TITLE
a question about training data

### ISSUE THREAD

**Issue by hkrds1996** [alievk/avatarify#28]
The performance of your application is not good on my computer. I think it's a good app. So I want to improve the performance. Because I'm an Asian, I want to use some Asian faces in your training model. Could you please tell me how can I do it.

**Comment by karfly** [comment]
Hi, @hkrds1996!
Yeah, the bias in the training data is a big problem of machine learning.

We use pretrained models from the [original repository](https://github.com/AliaksandrSiarohin/first-order-model) of "First Order Motion Model", so please refer to it. There you can find training scripts.

**Comment by hkrds1996** [comment]
Hi, @karfly 
Thank you. I read the article before, but I didn't utilize the idea. Thank you for your jobs.

**Comment by E3V3A** [comment]
@karfly
> We use pretrained models from the original repository of "First Order Motion Model", so please refer to it. There you can find training scripts.

Maybe mention this somewhere else, than in this issue? 
Can we open the Wiki and start an FAQ?

**Comment by E3V3A** [comment]
@karfly
> We use pretrained models from the original repository of "First Order Motion Model", so please refer to it. There you can find training scripts.

Maybe mention this somewhere else, than in this issue? 
Can we open the Wiki and start an FAQ?

**Comment by hkrds1996** [comment]
> @karfly
> 
> > We use pretrained models from the original repository of "First Order Motion Model", so please refer to it. There you can find training scripts.
> 
> Maybe mention this somewhere else, than in this issue?
> Can we open the Wiki and start an FAQ?

I think the pre-trained model is good enough to support you get good performances. Because this project just gets your face features at the beginning of the program, you need to keep the distance between your face and your camera. Then, everything will go well.
