### ISSUE TITLE
How to find the IP address of Google Colab Notebook

### ISSUE THREAD

**Issue by tvtr04** [alievk/avatarify#284]
Hi,
I want to run avatarify on macOS, but I need to use google colab...
How do I find the IP address of the notebook so I can connect to the server?
I tried to put the !curl ipecho.net/plain command in the notebook and I received an IP, but when I use this IP, the terminal is stuck on Receiving from.

This is the google colab command:

<img width="1061" alt="google_colab_command" src="https://user-images.githubusercontent.com/71630671/93757631-cbac5800-fc0f-11ea-93dc-2ad3c72ce3d1.png">

and this is what I see in the terminal:
<img width="1061" alt="terminal" src="https://user-images.githubusercontent.com/71630671/93757814-0dd59980-fc10-11ea-8205-1f11d0250ff5.png">

**Comment by alievk** [comment]
You can't connect to the notebook directly: it's behind NAT.

To connect to the notebook proxy is used (ngrok). Just run the notebook from the top to down and run the printed command in the end on you computer.

**Comment by tvtr04** [comment]
Hi, thank you! Now I can connect to the google Colab but when the programs search between cameras, I get an unknown error :(

<img width="1556" alt="Screen Shot 2020-09-22 at 8 58 21" src="https://user-images.githubusercontent.com/71630671/93848408-2b5b3f80-fcb2-11ea-840b-a6574b6c6c6f.png">

**Comment by tvtr04** [comment]
by the way, I saw on the troubleshooting that I should change the MAC_CAMID ("**Try to change MAC_CAMID in scripts/settings.sh (in avatarify folder) from 0 to 1, 2, ..."**).

But I opened the settings.sh file, and I don't have there any MAC_CAMID...
This is what I have:

` # [Linux] Virtual camera device`
`# Make sure this id is greater than maximum device id in the list 'v4l2-ctl --list-devices'`
 `#  Don't set a big number, it's known that Zoom does not detect cameras with id like 99`
 `CAMID_VIRT=9`
 `# Conda environment name` 
 `CONDA_ENV_NAME=avatarify`

**Comment by tvtr04** [comment]
@alievk 
I tried to delete CamTwist, and now I get the next errors:
<img width="1173" alt="Screen Shot 2020-09-22 at 10 56 52" src="https://user-images.githubusercontent.com/71630671/93856889-64031500-fcc2-11ea-9130-e68cf264eb7d.png">

**Comment by alievk** [comment]
You should see a window pop up which allows you to select your web camera.

`MAC_CAMID` is obsolete (will remove it).

**Comment by tvtr04** [comment]
I don't have any window that pops up...
only some "python" file is getting opened in the macOS dock, and I can't open it...


![IMG_5059](https://user-images.githubusercontent.com/71630671/94124795-23400300-fe5e-11ea-8687-ac0e19d1a700.jpg)

**Comment by tvtr04** [comment]
But when I it writes "trying camera with id 0" the camera's green light turns on for one second and then gets turned off...

**Comment by alievk** [comment]
Did you allow Avatarify to use your camera?

**Comment by tvtr04** [comment]
@alievk in the mac settings I have option to allow only to the terminal...

**Comment by tvtr04** [comment]
In the camera section, there is no plus to add other apps...

In the full disk access for example, I have this option...
<img width="371" alt="Screen Shot 2020-09-24 at 12 20 29" src="https://user-images.githubusercontent.com/71630671/94126601-7ca93180-fe60-11ea-819c-596c4c7280af.png">

But in the camera, there is no option...
<img width="371" alt="Screen Shot 2020-09-24 at 12 20 39" src="https://user-images.githubusercontent.com/71630671/94126594-7915aa80-fe60-11ea-8d61-7742032f11f7.png">

**Comment by alievk** [comment]
What happens when you run the script? Does it hang?

Also try top delete cam.yaml from the avatarify folder and try again.

**Comment by tvtr04** [comment]
I don't have cam.yaml file at all, only config.yaml...
and which script should I run?

**Comment by alievk** [comment]
For now, you can just run `./run_mac.sh`. (You need to get your web cam working.) A window with camera snapshots should appear.

**Comment by tvtr04** [comment]
If I try to run this without `bash run_mac.sh`, I get:
`zsh: permission denied: ./run_mac.sh`

**Comment by alievk** [comment]
Ok, that makes sense.

Then please try to connect to the notebook. Try different zones (if you're in Europe, try `eu`, if you're in USA, try `us` etc). Before opening a camera selector window, it will try to connect to the notebook. Run the notebook, copy paste the command it provided to your local terminal, run it and just wait. Sometimes it may take several minutes. This is the problem with the free proxy.

**Comment by ochen1** [comment]
Solution to tunneling issue posted as #369.
