### ISSUE TITLE
How to run avatarify on a window client with a Remote linux GPU?

### ISSUE THREAD

**Issue by HongguLiu** [alievk/avatarify#286]
I followed the step of [https://github.com/alievk/avatarify/wiki/Remote-GPU](https://github.com/alievk/avatarify/wiki/Remote-GPU)
When I run `bash run.sh --is-worker` on my remote linux gpu, I will get this:
![image](https://user-images.githubusercontent.com/36984792/94234333-109bfb80-ff3c-11ea-8a1c-cb3be444375b.png)

And then I run 'run_windows.bat --is-client --in-addr tcp://xxx.xxx.xxx.xxx:5557 --out-addr tcp://xxx.xxx.xxx.xxx:5558', I will get this:
![image](https://user-images.githubusercontent.com/36984792/94234284-feba5880-ff3b-11ea-9039-42aa43b1036d.png)

**Comment by HongguLiu** [comment]
But I don't know how to open the video capture, even I have downloaded OBS Studio.

**Comment by HongguLiu** [comment]
thanks, I have solved this problem....
It caused by the availability if port.

**Comment by rahimentezari** [comment]
> thanks, I have solved this problem....
> It caused by the availability if port.

@HongguLiu Hi. I have the same problem. How did you solve it? I need to open a specific port on the server?
