### ISSUE TITLE
numpy mkl-fft, can't install?

### ISSUE THREAD

**Issue by LilSizzurp** [alievk/avatarify#287]
Attempting uninstall: pycparser
    Found existing installation: pycparser 2.20
    Uninstalling pycparser-2.20:
      Successfully uninstalled pycparser-2.20
ERROR: After October 2020 you may experience errors when installing or updating packages. This is because pip will change the way that it resolves dependency conflicts.

We recommend you use --use-feature=2020-resolver to test your packages with the new resolver before it becomes the default.

mkl-fft 1.2.0 requires numpy>=1.16, but you'll have numpy 1.15.0 which is incompatible.
Successfully installed Pillow-6.2.2 PyWavelets-0.5.2 PyYAML-5.1 chardet-3.0.4 cloudpickle-0.5.3 cycler-0.10.0 dask-0.18.2 decorator-4.3.0 face-alignment-1.0.0 idna-2.10 imageio-2.3.0 kiwisolver-1.0.1 matplotlib-2.2.2 msgpack-1.0.0 msgpack-numpy-0.4.5 networkx-2.1 numpy-1.15.0 opencv-python-4.2.0.34 pandas-0.23.4 pycparser-2.18 pyfakewebcam-0.1.0 pygit-0.1 pyparsing-2.2.0 python-dateutil-2.7.3 pytz-2018.5 pyzmq-19.0.0 requests-2.23.0 scikit-image-0.14.0 scikit-learn-0.19.2 scipy-1.1.0 six-1.11.0 toolz-0.9.0 tqdm-4.24.0 urllib3-1.25.10

**Comment by HanYangZhao** [comment]
Had the same problem. Fixed by running this `pip install -r -requirements.txt --use-feature=2020-resolver`

**Comment by LilSizzurp** [comment]
fixed it by... doing something?
I have no idea.
