### ISSUE TITLE
Can I change my default camera for avatarify?

### ISSUE THREAD

**Issue by manmandy** [alievk/avatarify#289]
When I start avatarify at the first time, "Click on the web camera to use" appeared after I run run.sh and I have clicked to choose my webcam id0.
However, no more "Click on the web camera to use" popped up when I restart avatarify.
It seems that the chosen camera id0 have been set permanently.
Can I choose to use another camera? I would like to change the camera from id0 to id6.

**Comment by alievk** [comment]
You have two options:
1. Delete `cam.yaml` from `avatarify` folder. Camera selection window will appear on the next run.
2. In `cam.yaml`, change `cam_id`.

**Comment by manmandy** [comment]
Thanks Ali for your solution. It works.

Ali Aliev <notifications@github.com> 於 2020年10月7日 週三 下午5:11寫道：

**Comment by JohanAR** [comment]
Closing since this seems to be resolved

**Comment by carverjohn** [comment]
run this code
pip install pyyaml
pip install requests
pip install cv2
pip install scipy
pip install face_alignment
pip install sklearn
pip install pandas

**Comment by geekedpriest** [comment]
- [ ] Is Avatarify working now, please I need some help, been trying to install it but I'm stuck ![image](https://user-images.githubusercontent.com/120290986/210190781-fb33ce07-f98c-491c-bb85-7cd44fff0c9f.png)

**Comment by Saggitus007** [comment]
> * [ ]  Is Avatarify working now, please I need some help, been trying to install it but I'm stuck ![image](https://user-images.githubusercontent.com/120290986/210190781-fb33ce07-f98c-491c-bb85-7cd44fff0c9f.png)

Have you been able to fix it

**Comment by YtachY** [comment]
> You have two options:
> 
> 1. Delete `cam.yaml` from `avatarify` folder. Camera selection window will appear on the next run.
> 2. In `cam.yaml`, change `cam_id`.

Damn, this saves my day.
In my case, cam id change to OBS and I do not know how to switch. Thank you!

<img width="574" alt="CleanShot 2024-09-14 at 19 12 37@2x" src="https://github.com/user-attachments/assets/d8dca4eb-a83c-4f85-9b12-57cfea7b1fdf">

**Comment by YtachY** [comment]
> * [ ]  Is Avatarify working now, please I need some help, been trying to install it but I'm stuck ![image](https://user-images.githubusercontent.com/120290986/210190781-fb33ce07-f98c-491c-bb85-7cd44fff0c9f.png)

Maybe there is no choice of flag '2020-resolver' > just delete that part of command line.

Or following this https://youtu.be/sfkK50wmicw

**Comment by OkeyyDRIOD** [comment]
I need help with ngrok… anyone has a solid solution??
