### ISSUE TITLE
Zoom v4.6.8 installer for Windows

### ISSUE THREAD

**Issue by donganzh** [alievk/avatarify#29]
Hi, I'm trying this on Windows but I can't find the installer file for v4.6.8 or older on Zoom official website. Could you please share a link with us? Thanks!

**Comment by alievk** [comment]
Hi @donganzh 
Tested the latest Windows version 4.6.11 (20559.0413) and it works.

**Comment by donganzh** [comment]
> we found out that in versions after v4.6.8 (March 23, 2020) Zoom disabled support for virtual cameras on both Mac and Windows.

do you mean zoom start supporting virtual camera again in the latest version?

**Comment by alievk** [comment]
I have never noticed it stopped supporting virtual cams on windows...

**Comment by Naouak** [comment]
Zoom fixed it in one of the latest version, it was broken for several versions.
