### ISSUE TITLE
Pls help. having issues.

### ISSUE THREAD

**Issue by leelee086** [alievk/avatarify#292]
Hi. I followed your instructions exactly but i'm having issues. after I do the runs windows bat it gives me this issue. ill copy and paste bellow. I tried many times and couldn't get it to work and finally the last time it did work but one camera showed up with my face not the second one with the avatar .. so I deleted everything once again and reset everything and downloaded everything again following your instructions but now it gives me this issue....maybe its because i deleted and trired too many times?? idk but please help me to fix this.

(avatarify) C:\Users\leele\avatarify>run_windows.bat
[1603160573.568149] Loading Predictor
C:\Users\leele\avatarify\afy\predictor_local.py:34: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  config = yaml.load(f)
Downloading the face detection CNN. Please wait...
Traceback (most recent call last):
  File "C:\Users\leele\Miniconda3\envs\avatarify\lib\urllib\request.py", line 1350, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "C:\Users\leele\Miniconda3\envs\avatarify\lib\http\client.py", line 1277, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\leele\Miniconda3\envs\avatarify\lib\http\client.py", line 1323, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\leele\Miniconda3\envs\avatarify\lib\http\client.py", line 1272, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\leele\Miniconda3\envs\avatarify\lib\http\client.py", line 1032, in _send_output
    self.send(msg)
  File "C:\Users\leele\Miniconda3\envs\avatarify\lib\http\client.py", line 972, in send
    self.connect()
  File "C:\Users\leele\Miniconda3\envs\avatarify\lib\http\client.py", line 1447, in connect
    server_hostname=server_hostname)
  File "C:\Users\leele\Miniconda3\envs\avatarify\lib\ssl.py", line 423, in wrap_socket
    session=session
  File "C:\Users\leele\Miniconda3\envs\avatarify\lib\ssl.py", line 870, in _create
    self.do_handshake()
  File "C:\Users\leele\Miniconda3\envs\avatarify\lib\ssl.py", line 1139, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1091)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "afy/cam_fomm.py", line 195, in <module>
    **predictor_args
  File "C:\Users\leele\avatarify\afy\predictor_local.py", line 27, in __init__
    self.fa = face_alignment.FaceAlignment(face_alignment.LandmarksType._2D, flip_input=True, device=self.device)
  File "C:\Users\leele\Miniconda3\envs\avatarify\lib\site-packages\face_alignment\api.py", line 66, in __init__
    self.face_detector = face_detector_module.FaceDetector(device=device, verbose=verbose)
  File "C:\Users\leele\Miniconda3\envs\avatarify\lib\site-packages\face_alignment\detection\sfd\sfd_detector.py", line 39, in __init__
    os.path.join(path_to_temp_detector))
  File "C:\Users\leele\Miniconda3\envs\avatarify\lib\urllib\request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "C:\Users\leele\Miniconda3\envs\avatarify\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\leele\Miniconda3\envs\avatarify\lib\urllib\request.py", line 525, in open
    response = self._open(req, data)
  File "C:\Users\leele\Miniconda3\envs\avatarify\lib\urllib\request.py", line 543, in _open
    '_open', req)
  File "C:\Users\leele\Miniconda3\envs\avatarify\lib\urllib\request.py", line 503, in _call_chain
    result = func(*args)
  File "C:\Users\leele\Miniconda3\envs\avatarify\lib\urllib\request.py", line 1393, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "C:\Users\leele\Miniconda3\envs\avatarify\lib\urllib\request.py", line 1352, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1091)>

**Comment by alievk** [comment]
On StackOverflow, they mention Python version. What's your Python version?
Run Miniconda and call commads:
```
conda activate avatarify
python -V
```

**Comment by leelee086** [comment]
It says Python 3.7.9(default. aug 31,2020. 17:10:11)
I hope that's what u were asking, sorry i'm not very tech savy but I followed your instructions exactly and downloaded everything you said it. it worked one time before but only one screen popped up so I reset and delete everything and redownloaded everything again a lot of times and now have this problem and its not worried.. im worried its because I did it too many times? Pls help... I would appreciate it sooo much!

**Comment by alievk** [comment]
Python 3.7.9 is ok.

Actually, this issue is not related to Avatarify. It's trying to download face detector weights and failing because of certificate issues. No idea what's happening. Did you try running multiple times? Maybe try to use VPN?

**Comment by leelee086** [comment]
Yes I tried many times. I deleted everything and even reset the computer multiple times to download again like you instructed but it keeps giving me the same issue. I’m so sad because it worked once before with only one camera showing up but it’s like this. Do u think it could be because I tried to download it again and again too many times? Maybe it’s blocked IT? I’ll try to use VPN and get back to u.

**Comment by leelee086** [comment]
Hi. good news i finally fixed the ssl problem and got it to work but now i'm having issues with ob studios when i click windows capture avatarify isn't in the list. what should i do. how can i fix this?

**Comment by alievk** [comment]
How did you fix the SSL issue?

Is Avatarify running (you see both 'cam' and 'avatarify' windows)?

**Comment by leelee086** [comment]
I just kind of messed around with the security on the computer in google. i dont really remember what i did. i just read something on the form somebody suggested and unclicked one of the options and it worked thankfully. yes both cam and avatarify is working my problem now is that when i do fit to screen for some reason it doesn't fit to screen and it just stays small. how do i fix this?

**Comment by leelee086** [comment]
i clicked fit to screen but the avatarify screen just stays small and doesn't fit to screen.... idk why..

**Comment by leelee086** [comment]
Pls help... I tried everything but the avatarify cam is super small and just stays that size even when I do fit to screen. I tried connecting to zoom but the video is super tiny.. can u tell me how I fix this? Is there a way I can adjust the video size of the avatarify in ob studios?

**Comment by leelee086** [comment]
sorry for so many comments. i just wanted to clarify that the avatarify video is small and stays small in one corner within the box. so even if i try to resize it the box fits to screen but the avatarify video screen is still small inside if that makes sense

**Comment by leelee086** [comment]
Is there a way to change the size of the avatarify video? instead of having it to be square so it can fit the size of a mobile phone screen? because right now it just cropped and looks off when you use zoom or skype on mobile?

**Comment by leelee086** [comment]
Hi. i got the system to work but i have an issue with the avatar/ the bottom and side of the video keeps shaking. the picture doesn't stay still.. how do i fix this

**Comment by alievk** [comment]
Make sure there there is enough light in your room and your face is clearly seen.

**Comment by JohanAR** [comment]
As alievk said, unstable/shaking avatar is a symptom of too much noise from your webcam, which makes it impossible for the face detection to generate stable results. Better lighting is the most universal remedy for this, especially old/cheap webcams have problems with noise in poor light conditions. If you have a control panel for your webcam (either in your OS or from the webcam driver) you could try increasing exposure, enabling noise reduction and lowering resolution if you have those options. Exactly what options you have will depend on the type of webcam and the capabilities of its driver.

Closing this issue since you have reporting having Avatarify running, and your remaining issue is outside our control :)
