### ISSUE TITLE
Numpy Issue

### ISSUE THREAD

**Issue by EmmaSavary** [alievk/avatarify#293]
Hello,
I got to step 4, and when I copied and pasted the 3rd link (scripts\install_windows.bat), this error message appears.
I'm sorry if it's obvious, but I'm a python beginner and I have no idea what to do. Can you help me please?

Info :
 - OS: Windows 10
 - GPU model: NVIDIA GeForce GTX 1060 3GB

https://zupimages.net/up/20/43/myog.png

**Comment by alievk** [comment]
Could you attach the picture to a message? The link is not accessible for me.

**Comment by EmmaSavary** [comment]
![Capture2](https://user-images.githubusercontent.com/73246414/97004956-0c183200-153e-11eb-8b9f-92406da521bd.PNG)

Here it is, thank you very much for helping me!

**Comment by alievk** [comment]
Actually, you can ignore this. I'll fix this warning in the next commit.

**Comment by EmmaSavary** [comment]
Thank you very much, it works very well when I ignore the warning!
