### ISSUE TITLE
Mention CUDA/CUDNN versions and nvidia-docker dependencies

### ISSUE THREAD

**Issue by theCalcaholic** [alievk/avatarify#296]
I didn't find these requirements in the readme or the Wiki and had to do some digging to find everything needed. Imho, it would be a good idea to mention

- the CUDA version that needs to be installed (at least for Linux systems; may or may not be bundled for Windows)
- the CUDNN version that needs to be installed (if not running via docker)
- that [nvidia-docker2](https://github.com/NVIDIA/nvidia-docker) is required in order to get GPU support in docker

**Comment by alievk** [comment]
You don't have to install CUDA/CUDNN by yourself, it comes with PyTorch, which is installed via conda.

**Comment by theCalcaholic** [comment]
Ah right - then it's probably just nvidia-docker2. Now I hate myself for installing CUDA again (did mess up my nvidia drivers more than once in the past :wink: )

**Comment by mintmaker** [comment]
`nvidia-docker` is already mentionend in the readme.

> 2. For using the gpu (hardly recommended): Install nvidia drivers and [nvidia docker](https://github.com/NVIDIA/nvidia-docker#quickstart).

**Comment by nospam2k** [comment]
Is that correct? Or should it say (highly recommended)?

**Comment by mintmaker** [comment]
Yes, it should say `highly recommended`.

**Comment by theCalcaholic** [comment]
I figure this can be closed, then
