### ISSUE TITLE
[Feature] Passthrough mode

### ISSUE THREAD

**Issue by theCalcaholic** [alievk/avatarify#298]
It would be very useful to have a passthrough mode, that can be selected similar to any of the avatars.

The camera device is unusable, while avatarify is accessing it, so in order to change to the default camera, it's currently necessary to stop the tool (at least that's my experience on Ubuntu 20.04).

**Comment by alievk** [comment]
It actually has a passthrough mode, press 0.

**Comment by alievk** [comment]
[Controls](https://github.com/alievk/avatarify#controls)

**Comment by theCalcaholic** [comment]
Oh well... :D

Pardon my ignorance
