### ISSUE TITLE
Can't install the 4.6.8 version in mac

### ISSUE THREAD

**Issue by Vincent-xu-Wu** [alievk/avatarify#30]
I tried to install the 4.6.8 version but it showed the info over the install window that This package will run a program to determine if the software can be installed. Then I clicked Continue. But nothing happened then. However, I could successfully install the newest version.

**Comment by redondos** [comment]
This worked for me:
- move zoom to trash
- run installer. it will appear to crash
- expected zoom version appears in Applications

Avatarify on Mac is still way too slow to be usable, but you can follow these steps to use other virtual cameras.
