### ISSUE TITLE
Paper of this work

### ISSUE THREAD

**Issue by mfurkanns** [alievk/avatarify#308]
Could you please tell which papers implementation is this study?

**Comment by EricPedley** [comment]
In the readme, there is a link to this repo: https://github.com/AliaksandrSiarohin/first-order-model
Which is the source code for this paper: https://papers.nips.cc/paper/2019/file/31c0b36aef265d9221af80872ceb62f9-Paper.pdf
Hope this helps

**Comment by JohanAR** [comment]
Closing since the question has been answered
