### ISSUE TITLE
No module named 'sync_batchnorm' on Windows

### ISSUE THREAD

**Issue by artmatv** [alievk/avatarify#32]
Traceback (most recent call last):
  File "cam_fomm.py", line 12, in <module>
    from sync_batchnorm import DataParallelWithCallback
ModuleNotFoundError: No module named 'sync_batchnorm'

System: Windows10

**Comment by alievk** [comment]
Do you have fomm in avatarify directory?

**Comment by artmatv** [comment]
No, I don't, it had some problems during installation so I downloaded and installed modules by myself from requirements.txt
(base) C:\Users\GAMING-PC\Desktop\avatarify-master\avatarify-master\scripts>call git clone https://github.com/alievk/first-order-model.git fomm
'git' is not recognized as an internal or external command,
operable program or batch file.

(base) C:\Users\GAMING-PC\Desktop\avatarify-master\avatarify-master\scripts>call pip install -r fomm/requirements.txt
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'fomm/requirements.txt'

**Comment by artmatv** [comment]
Installed git and installation went fine, now I have fomm in avatarify/scripts

**Comment by alievk** [comment]
I supposed git comes with miniconda.. Could you describe your steps how you installed git?

Please run scripts\install_windows.bat from avatarify root directory as described in the readme.

**Comment by artmatv** [comment]
I just downloaded git from official website and edited PATH in environment variables so the git could be executed from console.
Ran again install_windows.bat and appeared fomm folder with all modules, but the problem still exists

**Comment by artmatv** [comment]
C:\Users\GAMING-PC\Desktop\avatarify-master\avatarify-master>REM @set /P CAMID=0
Traceback (most recent call last):
  File "cam_fomm.py", line 12, in <module>
    from sync_batchnorm import DataParallelWithCallback
ModuleNotFoundError: No module named 'sync_batchnorm'

**Comment by artmatv** [comment]
If it is important, I have this message before the REM @set /P CAMID=0 runs
C:\Users\GAMING-PC\Desktop\avatarify-master\avatarify-master>set CONDA_ENV_NAME=avatarify
Could not find conda environment: avatarify
You can list all discoverable environments with `conda info --envs`.

**Comment by alievk** [comment]
Yes it is a problem. Please show entire output of install_windows.bat script

**Comment by artmatv** [comment]
https://pastebin.com/efwUQkui

**Comment by alievk** [comment]
You are not running the script the way it is described in the readme and as I previously asked you

**Comment by alievk** [comment]
Please run scripts\install_windows.bat from avatarify root directory as described in the readme.

**Comment by artmatv** [comment]
Oh, yes, my mistake, now everything works fine. Thank you! I think you should highlight that paragraph in case of guys like me)

**Comment by alievk** [comment]
Congrats! :)
