### ISSUE TITLE
Straight up bricked my computer

### ISSUE THREAD

**Issue by jfwyatt** [alievk/avatarify#326]
**Describe the bug**
Installed, mouse wasn't responsive. Restarted, and nothing. 

**To Reproduce**
Install

**Info (please complete the following information):**
 - OS Windows 10
 - GPU model: 2080

**Comment by ochen1** [comment]
In order to help you, we will need more information.

What is the error message you receive when restarting your computer?

What do you mean by "nothing"?

**Comment by jfwyatt** [comment]
Sorry - No video out. 
Rebooted in safe mode and everything worked, so I tried booting normally and everything is fine. Really don't know what happened, can't reproduce. Going to chalk this one up to gremlins. Sorry for the trouble!
