### ISSUE TITLE
Could I run this without CUDA? I have a decent GPU, but it's not an Nvidia one.

### ISSUE THREAD

**Issue by RCCRAFT1** [alievk/avatarify#329]
Can I run this without CUDA? I have a decent GPU, but it's not an Nvidia one (AMD). Would disabling CUDA allow me to run it without an Nvidia GPU?

**Comment by ochen1** [comment]
Yes. Please take a look at https://github.com/alievk/avatarify#remote-gpu.

**Comment by RCCRAFT1** [comment]
Nah, I don't want to use colab.

**Comment by RCCRAFT1** [comment]
I am not interested in using webhooks and forwarding servers and other stuff just to get colab to use a webcam

**Comment by ochen1** [comment]
I think the answer, then, would be no.
You can run it on CPU, but with really low fps (ie. < 1 fps)

**Comment by RCCRAFT1** [comment]
I'm sure there is some sort of syntax to disable CUDA because spending hundreds to thousands of dollars to use this doesn't seem efficient and people wouldn't be using it because of the complexity and limits to using it with colab.
