### ISSUE TITLE
yaml is unsafe | please help 

### ISSUE THREAD

**Issue by The-ron** [alievk/avatarify#330]
**Describe the bug**

It says that yaml is unsafe when I run run_windows.bat
this pops up after the directory
avatarify\afy\predictor_local.py:34: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  config = yaml.load(f)
I checked the website but still do not understand how to fix someone please help me

**Comment by ochen1** [comment]
Looks like this is [only a depreciation warning](https://github.com/yaml/pyyaml/wiki/PyYAML-yaml.load(input)-Deprecation).

Does the program not work?

Try running this command before running avatarify?

```bat
set PYTHONWARNINGS=ignore::yaml.YAMLLoadWarning
```

**Comment by The-ron** [comment]
> Looks like this is [only a depreciation warning](https://github.com/yaml/pyyaml/wiki/PyYAML-yaml.load(input)-Deprecation).
> 
> Does the program not work?
> 
> Try running this command before running avatarify?
> 
> ```batchfile
> set PYTHONWARNINGS=ignore::yaml.YAMLLoadWarning
> ```

![image](https://user-images.githubusercontent.com/66538923/103047709-56c42380-455a-11eb-9d1d-936382a5eccf.png)

**Comment by jackyxie511** [comment]
Hello, I have also encountered this problem. Is your face detection CNN always loaded?

`set PYTHONWARNINGS=ignore::yaml.YAMLLoadWarning
 bash run.sh
Creating virtual camera /dev/video9 (sudo privelege required)
[1608780572.440412] Loading Predictor
/home/lab134/xq/xq0914-avatarify-master/avatarify/afy/predictor_local.py:34: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  config = yaml.load(f)
Downloading the face detection CNN. Please wait...`

**Comment by ochen1** [comment]
Please patiently wait for the face detection CNN model to download.

**Comment by alievk** [comment]
You can safely ignore this warning. This is a super minor issue.

**Comment by board808** [comment]
How do I ignore this?

**Comment by board808** [comment]
Please help, everything else is working except this issue and I do not know how to ignore this issue. I could not find anything on how to ignore this issue. Please help.

**Comment by alievk** [comment]
Just don't notice it 🤷‍♂️

**Comment by board808** [comment]
How?

**Comment by board808** [comment]
It stays stuck on the warning and nothing happens

**Comment by ochen1** [comment]
Patiently wait.

It is downloading the model.
