### ISSUE TITLE
Provisioning remote GPU to Win app

### ISSUE THREAD

**Issue by bostjan39** [alievk/avatarify#332]
Hi,

Windows app works like a charm, great job!
Is there a plan to add a remote GPU feature to it, for us who don't have a $2k PC?

Take care:)

**Comment by alievk** [comment]
Thank you! Actually the goal is to make a high quality product from the app, so if we make a remote gpu feature we also have to provide the service for remote gpus. That's costly so until we don't have a monetisation or a big audience there's no reason to do that.

Google Colab feature is just for demonstration, it's not supposed to be used for this purpose, it's very limited so we are not going to use it in the Windows app.

**Comment by bostjan39** [comment]
Thanks for reply, but I thought to have a feature to be able to connect via AWS or something, without you having to offer that service by yourself. Maybe just shot in the dark here?

**Comment by alievk** [comment]
I think if we provide that feature we also have to provide the service. To make it work we have to control the front- and backend. Otherwise there will be complaints that its not working when the problem is on the user's side (poor connection, troubles with AWS server etc.)

**Comment by bostjan39** [comment]
I think not. Users are not that dumb to blame you, if there is a problem not related to Avatarify, you would just need to tell them that. But hey, anyone can disable that feature, if he wants, the main thing is to have it available, right? I know I would love to have it, because there's a difference between paying $1/hour on AWS or $2k for GPU laptop:)
But even if you offer a SaaS version of that, I would bet that you'd get flooded with clients, myself would be the 1st.
Take care:)

**Comment by alievk** [comment]
I will bear this in mind, thank you! :)

**Comment by Mudi400** [comment]
Nice software you have built an amazing software but I have a issue first with the installation i'm using a PC with GPU it installed successfully but only one cam was showing that is my face please I need help tell me what to do. Then starting the worker on google colab it's saying there is an issue with my authoken

**Comment by alievk** [comment]
> Nice software you have built an amazing software but I have a issue first with the installation i'm using a PC with GPU it installed successfully but only one cam was showing that is my face please I need help tell me what to do. Then starting the worker on google colab it's saying there is an issue with my authoken
