### ISSUE TITLE
Cannot upload custom png avatar to google colab

### ISSUE THREAD

**Issue by lithium-codes** [alievk/avatarify#340]
**Describe the bug**

Cannot upload custom png avatar to google colab

**To Reproduce**

Make a google colab of avatarify and run it on windows

**Info (please complete the following information):**
 - OS (e.g., Linux): Windows
 - GPU model: im on google colab, and i have a Intel(R) HD Graphics 530 on my main pc.

 - Any other relevant information: 

**Screenshots**

https://prnt.sc/wjgzky there is not a donovan.png there

**Logs**

**Comment by alievk** [comment]
You have to add avatars in your local avatarify directory.

**Comment by lithium-codes** [comment]
> You have to add avatars in your local avatarify directory.

now it just keeps saying `[1610197723.962747] 88` when i click x to calibrate my face

**Comment by lithium-codes** [comment]
> You have to add avatars in your local avatarify directory.

it has been fixed thank you
