### ISSUE TITLE
cant run install.sh

### ISSUE THREAD

**Issue by ValtokIsHere** [alievk/avatarify#343]
**Describe the bug**
scripts/install.sh: line 2: $'\r': command not found
scripts/install.sh: line 33: syntax error: unexpected end of file[]
![bruhhh](https://user-images.githubusercontent.com/52051301/104311777-5fb36f80-54de-11eb-918b-9fd2012f445a.png)

**Comment by ochen1** [comment]
Duplicate issue. Someone was editing Unix script on windows os. Copy commands manually and execute to fix.

**Comment by JohanAR** [comment]
This should be fixed a while ago so I'm closing the issue. Please report back if pulling the latest master didn't fix it for you.
