### ISSUE TITLE
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'

### ISSUE THREAD

**Issue by chapoogie** [alievk/avatarify#347]
Hello, 

I had this exact problem https://github.com/alievk/avatarify/issues/335#issuecomment-754673690

I then did this from Ali Aliev  (post reference https://github.com/alievk/avatarify/issues/336)
https://github.com/alievk/avatarify/issues/336#issuecomment-759308390

"The problem is that we use old Pytorch version which doesn't support brand new 3080. If we update Pytorch we can break support for older GPUs.

@board808 @hshshv @gabtremblay @sjhill01 @chapoogie Open Miniconda and try these:

cd avatarify
conda activate avatarify
conda install pytorch torchvision cudatoolkit=11.0 -c pytorch
run_windows.bat
This will update Pytorch to the latest version and should help in your case. "

OK here are my PC Specs: i910900K Nvidia RTX 3090
Anything else i should add in here?

![image](https://user-images.githubusercontent.com/77359930/104505150-55ee4280-5598-11eb-881c-20254f73cad1.png)

**Comment by alievk** [comment]
Looks like wrong numpy version. Try this:
```
cd avatarify
conda activate avatarify
conda install -y -c conda-forge numpy==1.19.1
```

**Comment by chapoogie** [comment]
Tried that. Got this. 
![image](https://user-images.githubusercontent.com/77359930/104644730-04f75080-5663-11eb-8923-0fb4d2e0b5ba.png)

**Comment by alievk** [comment]
Ok, it's a known issue. Now do this:
```
conda activate avatarify
pip uninstall scikit-image
conda install -y -c conda-forge scikit-image
```

**Comment by chapoogie** [comment]
Next error after that. 
![image](https://user-images.githubusercontent.com/77359930/104654623-42fb7100-5671-11eb-8f20-3b60e1ae1cf7.png)

**Comment by alievk** [comment]
You don't need to call conda activate before run_windows.bat.
Please pull the latest update from the repo and call run_windows.bat again:
```
cd avatarify
git pull origin master
```

**Comment by chapoogie** [comment]
That did the trick! Thank you very much.

**Comment by alievk** [comment]
Glad to hear that!

Now I wonder whats your FPS? You can press I on your keyboard and it will print info in the `cam` window. If you share screenshot of that window it would be ideal, but FPS would be enough too.

**Comment by chapoogie** [comment]
FPS: avg 32

mode time: flickering at 18-20
pre: flickering at 1-2
post: flickering at 8-12

**Comment by gabtremblay** [comment]
Thanks, fixed the problem. Also running 31 fps here on 3080

**Comment by JohanAR** [comment]
These changes are now on master. I think everybody here has got it working so I'm closing this issue. Feel free to re-open or create a new issue if anyone's still having problems.
