### ISSUE TITLE
vox-adv-cpk.pth.tar vs vox-cpk.pth.tar

### ISSUE THREAD

**Issue by eyaler** [alievk/avatarify#35]
the code uses vox-adv-cpk.pth.tar
but the cmd argument defaults to vox-cpk.pth.tar
by the way, what is the difference between the two?

**Comment by cepaige** [comment]
How do you place the tar file into the root directory? Thank you!

**Comment by E3V3A** [comment]
anyone?

**Comment by E3V3A** [comment]
anyone?

**Comment by E3V3A** [comment]
anyone?

**Comment by akashi117** [comment]
both links are dead please fix them

**Comment by alievk** [comment]
fixed!

use link https://avatarify.s3.amazonaws.com/weights/vox-adv-cpk.pth.tar

**Comment by lem0nade0** [comment]
the link still doesn't have vox-cpk.pth.tar

**Comment by ahwangyuwei** [comment]
Do you know now? Same question

**Comment by JohanAR** [comment]
> Do you know now? Same question

No idea.

Use the download link for vox-adv-cpk.pth.tar in the install instructions. If you have a file that you've downloaded from somewhere else you can try it, but we can't help you.

**Comment by brucebernier451-design** [comment]
I cant seem to download vox-adv-cpk.pth.tar

**Comment by MICKYGEM** [comment]
> I cant seem to download vox-adv-cpk.pth.tar

Send a message to https://wa.me/message/Q2R3YYTP46XKG1

**Comment by MICKYGEM** [comment]
> I cant seem to download vox-adv-cpk.pth.tar

https://avatarify.s3.amazonaws.com/weights/vox-adv-cpk.pth.tar
