### ISSUE TITLE
Intel Intergrated GPUS

### ISSUE THREAD

**Issue by RocketNinja15** [alievk/avatarify#352]
**Describe the bug**

Avatarify does not support Intel Intergrated Gpu's
**To Reproduce**

Use a Intel GPU and it will use CPU only[
**Info (please complete the following information):**
 - OS Windows/MacOs
 - GPU model:  Intel(R) HD Graphics 6000
N/A
 - Any other relevant information: 

**Screenshots**

**Logs**

**Comment by JohanAR** [comment]
Well, yes, it says in the requirements that you need an Nvidia graphics card, so it's not really a bug :)

There is already a feature request to add Intel GPU support in #182

**Comment by RocketNinja15** [comment]
> Well, yes, it says in the requirements that you need an Nvidia graphics card, so it's not really a bug :)
> 
> There is already a feature request to add Intel GPU support in #182

yes... i read that... .i just didn't know if someone had made a suggestion for this yet :)

**Comment by JohanAR** [comment]
No problem. I wasn't sure if you wanted to report this as a bug or feature request so I mentioned both. I'll close this issue and you can comment in #182 if you want to express your support for this request :)
