### ISSUE TITLE
Is there a way to use a video instead of a live camera to move the avatar?

### ISSUE THREAD

**Issue by epiqueras** [alievk/avatarify#355]
>Is there a way to use a video instead of a live camera to move the avatar?

**Comment by JohanAR** [comment]
If you're using Linux you can create multiple virtual camera devices and use ffmpeg to redirect them however you like.

Though it's probably easier to do something with the code from the research which Avatarify is based on: https://github.com/AliaksandrSiarohin/first-order-model

**Comment by epiqueras** [comment]
Thanks. Did you use a checkpoint or trained it on some specific dataset yourself?

**Comment by JohanAR** [comment]
Open Avatarify uses a checkpoint provided by the first-order-model project. If you check their github README.md they have a link to a google drive with different checkpoints

**Comment by epiqueras** [comment]
Thanks!

**Comment by JohanAR** [comment]
No problem. Good luck with your project!
