### ISSUE TITLE
Netowrk Weights - Corrupt file or non-standard format?

### ISSUE THREAD

**Issue by stylemessiah** [alievk/avatarify#36]
Downloaded vox-adv-cpk.pth.tar from google drive, and as i do with any archive file went to open it to test it wasnt corrupt, but it gives an error about corruption or non-standard format

Before i download it a 3rd time on my slow connection, is this archive in a non-standard format by any chance, to protect its content perhaps?

**Comment by alievk** [comment]
Try another [link](https://yadi.sk/d/lEw8uRm140L_eQ/vox-adv-cpk.pth.tar)

**Comment by stylemessiah** [comment]
Same issue corrupt or non-standard format if you try and open or test

Downloaded it 5 times now

Your file is either broken or in a format WinRAR or 7Zip cant understand....

**Comment by alievk** [comment]
You don't have to unpack it, just put it the avatarify folder

**Comment by cepaige** [comment]
I have downloaded the tar file but how do I put it into the avatarify root file?

**Comment by alievk** [comment]
Copy/paste that file where you install avatarify.
Watch video https://www.youtube.com/watch?v=lym9ANVb120
