### ISSUE TITLE
Install error: Could not open requirements file / Run error: no module yaml

### ISSUE THREAD

**Issue by theArthuryus** [alievk/avatarify#39]
`> (base) C:\Users\R2>cd avatarify-master
> 
> (base) C:\Users\R2\avatarify-master>scripts\install_windows.bat
> 
> (base) C:\Users\R2\avatarify-master>call scripts/settings_windows.bat
> 
> (base) C:\Users\R2\avatarify-master>REM Web-camera device id
> 
> (base) C:\Users\R2\avatarify-master>set CAMID=0
> 
> (base) C:\Users\R2\avatarify-master>REM ################################################
> 
> (base) C:\Users\R2\avatarify-master>REM Normally you don't want to change settings below
> 
> (base) C:\Users\R2\avatarify-master>REM Conda environment name
> 
> (base) C:\Users\R2\avatarify-master>set CONDA_ENV_NAME=avatarify
> 
> (base) C:\Users\R2\avatarify-master>call conda create -y -n avatarify python=3.8
> Collecting package metadata (current_repodata.json): done
> Solving environment: done
> 
> ## Package Plan ##
> 
>   environment location: C:\Users\R2\MiniConda3\envs\avatarify
> 
>   added / updated specs:
>     - python=3.8
> 
> 
> The following NEW packages will be INSTALLED:
> 
>   ca-certificates    pkgs/main/win-64::ca-certificates-2020.1.1-0
>   certifi            pkgs/main/win-64::certifi-2020.4.5.1-py38_0
>   openssl            pkgs/main/win-64::openssl-1.1.1f-he774522_0
>   pip                pkgs/main/win-64::pip-20.0.2-py38_1
>   python             pkgs/main/win-64::python-3.8.2-h5fd99cc_11
>   setuptools         pkgs/main/win-64::setuptools-46.1.3-py38_0
>   sqlite             pkgs/main/win-64::sqlite-3.31.1-he774522_0
>   vc                 pkgs/main/win-64::vc-14.1-h0510ff6_4
>   vs2015_runtime     pkgs/main/win-64::vs2015_runtime-14.16.27012-hf0eaf9b_1
>   wheel              pkgs/main/win-64::wheel-0.34.2-py38_0
>   wincertstore       pkgs/main/win-64::wincertstore-0.2-py38_0
> 
> 
> Preparing transaction: done
> Verifying transaction: done
> Executing transaction: done
> 
> To activate this environment, use
> 
>      $ conda activate avatarify
> 
> To deactivate an active environment, use
> 
>      $ conda deactivate
> 
> 
> (base) C:\Users\R2\avatarify-master>call conda activate avatarify
> 
> (avatarify) C:\Users\R2\avatarify-master>call conda install -y pytorch torchvision cudatoolkit=10.1 -c pytorch
> Collecting package metadata (current_repodata.json): done
> Solving environment: done
> 
> ## Package Plan ##
> 
>   environment location: C:\Users\R2\MiniConda3\envs\avatarify
> 
>   added / updated specs:
>     - cudatoolkit=10.1
>     - pytorch
>     - torchvision
> 
> 
> The following NEW packages will be INSTALLED:
> 
>   blas               pkgs/main/win-64::blas-1.0-mkl
>   cudatoolkit        pkgs/main/win-64::cudatoolkit-10.1.243-h74a9793_0
>   freetype           pkgs/main/win-64::freetype-2.9.1-ha9979f8_1
>   icc_rt             pkgs/main/win-64::icc_rt-2019.0.0-h0cc432a_1
>   intel-openmp       pkgs/main/win-64::intel-openmp-2020.0-166
>   jpeg               pkgs/main/win-64::jpeg-9b-hb83a4c4_2
>   libpng             pkgs/main/win-64::libpng-1.6.37-h2a8f88b_0
>   libtiff            pkgs/main/win-64::libtiff-4.1.0-h56a325e_0
>   mkl                pkgs/main/win-64::mkl-2020.0-166
>   mkl-service        pkgs/main/win-64::mkl-service-2.3.0-py38hb782905_0
>   mkl_fft            pkgs/main/win-64::mkl_fft-1.0.15-py38h14836fe_0
>   mkl_random         pkgs/main/win-64::mkl_random-1.1.0-py38hf9181ef_0
>   ninja              pkgs/main/win-64::ninja-1.9.0-py38h74a9793_0
>   numpy              pkgs/main/win-64::numpy-1.18.1-py38h93ca92e_0
>   numpy-base         pkgs/main/win-64::numpy-base-1.18.1-py38hc3f5095_1
>   olefile            pkgs/main/noarch::olefile-0.46-py_0
>   pillow             pkgs/main/win-64::pillow-7.0.0-py38hcc1f983_0
>   pytorch            pytorch/win-64::pytorch-1.4.0-py3.8_cuda101_cudnn7_0
>   six                pkgs/main/win-64::six-1.14.0-py38_0
>   tk                 pkgs/main/win-64::tk-8.6.8-hfa6e2cd_0
>   torchvision        pytorch/win-64::torchvision-0.5.0-py38_cu101
>   xz                 pkgs/main/win-64::xz-5.2.4-h2fa13f4_4
>   zlib               pkgs/main/win-64::zlib-1.2.11-h62dcd97_3
>   zstd               pkgs/main/win-64::zstd-1.3.7-h508b16e_0
> 
> 
> Preparing transaction: done
> Verifying transaction: done
> Executing transaction: done
> 
> (avatarify) C:\Users\R2\avatarify-master>call conda install -y -c 1adrianb face_alignment
> Collecting package metadata (current_repodata.json): done
> Solving environment: done
> 
> ## Package Plan ##
> 
>   environment location: C:\Users\R2\MiniConda3\envs\avatarify
> 
>   added / updated specs:
>     - face_alignment
> 
> 
> The following NEW packages will be INSTALLED:
> 
>   cloudpickle        pkgs/main/noarch::cloudpickle-1.3.0-py_0
>   cycler             pkgs/main/win-64::cycler-0.10.0-py38_0
>   cytoolz            pkgs/main/win-64::cytoolz-0.10.1-py38he774522_0
>   dask-core          pkgs/main/noarch::dask-core-2.14.0-py_0
>   decorator          pkgs/main/noarch::decorator-4.4.2-py_0
>   face_alignment     1adrianb/noarch::face_alignment-1.0.1-py_1
>   hdf5               pkgs/main/win-64::hdf5-1.10.4-h7ebc959_0
>   icu                pkgs/main/win-64::icu-58.2-ha66f8fd_1
>   imageio            pkgs/main/noarch::imageio-2.8.0-py_0
>   kiwisolver         pkgs/main/win-64::kiwisolver-1.0.1-py38ha925a31_0
>   libopencv          pkgs/main/win-64::libopencv-4.0.1-hbb9e17c_0
>   matplotlib         pkgs/main/win-64::matplotlib-3.1.3-py38_0
>   matplotlib-base    pkgs/main/win-64::matplotlib-base-3.1.3-py38h64f37c6_0
>   networkx           pkgs/main/noarch::networkx-2.4-py_0
>   opencv             pkgs/main/win-64::opencv-4.0.1-py38h2a7c758_0
>   py-opencv          pkgs/main/win-64::py-opencv-4.0.1-py38he44ac1e_0
>   pyparsing          pkgs/main/noarch::pyparsing-2.4.6-py_0
>   pyqt               pkgs/main/win-64::pyqt-5.9.2-py38ha925a31_4
>   python-dateutil    pkgs/main/noarch::python-dateutil-2.8.1-py_0
>   pywavelets         pkgs/main/win-64::pywavelets-1.1.1-py38he774522_0
>   qt                 pkgs/main/win-64::qt-5.9.7-vc14h73c81de_0
>   scikit-image       pkgs/main/win-64::scikit-image-0.16.2-py38h47e9c7a_0
>   scipy              pkgs/main/win-64::scipy-1.4.1-py38h9439919_0
>   sip                pkgs/main/win-64::sip-4.19.13-py38ha925a31_0
>   toolz              pkgs/main/noarch::toolz-0.10.0-py_0
>   tornado            pkgs/main/win-64::tornado-6.0.4-py38he774522_1
>   tqdm               pkgs/main/noarch::tqdm-4.44.1-py_0
> 
> 
> Preparing transaction: done
> Verifying transaction: done
> Executing transaction: done
> 
> (avatarify) C:\Users\R2\avatarify-master>REM ###FOMM###
> 
> **(avatarify) C:\Users\R2\avatarify-master>call git clone https://github.com/alievk/first-order-model.git fomm
> 'git' is not recognized as an internal or external command,
> operable program or batch file.**
> 
**> (avatarify) C:\Users\R2\avatarify-master>call pip install -r fomm/requirements.txt
> ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'fomm/requirements.txt'**
> 
> (avatarify) C:\Users\R2\avatarify-master>call pip install requests
> Collecting requests
>   Using cached requests-2.23.0-py2.py3-none-any.whl (58 kB)
> Requirement already satisfied: certifi>=2017.4.17 in c:\users\r2\miniconda3\envs\avatarify\lib\site-packages (from requests) (2020.4.5.1)
> Collecting idna<3,>=2.5
>   Using cached idna-2.9-py2.py3-none-any.whl (58 kB)
> Collecting urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1
>   Using cached urllib3-1.25.8-py2.py3-none-any.whl (125 kB)
> Collecting chardet<4,>=3.0.2
>   Using cached chardet-3.0.4-py2.py3-none-any.whl (133 kB)
> Installing collected packages: idna, urllib3, chardet, requests
> Successfully installed chardet-3.0.4 idna-2.9 requests-2.23.0 urllib3-1.25.8
> 
> (avatarify) C:\Users\R2\avatarify-master>run_windows.bat
> 
> (avatarify) C:\Users\R2\avatarify-master>REM Web-camera device id
> 
> (avatarify) C:\Users\R2\avatarify-master>set CAMID=0
> 
> (avatarify) C:\Users\R2\avatarify-master>REM ################################################
> 
> (avatarify) C:\Users\R2\avatarify-master>REM Normally you don't want to change settings below
> 
> (avatarify) C:\Users\R2\avatarify-master>REM Conda environment name
> 
> (avatarify) C:\Users\R2\avatarify-master>set CONDA_ENV_NAME=avatarify
> 
> (avatarify) C:\Users\R2\avatarify-master>REM @set /P CAMID="Pick the webcam id you want to use (typically "0"): "
> Traceback (most recent call last):
>   File "cam_fomm.py", line 3, in <module>
>     import yaml
> ModuleNotFoundError: No module named 'yaml'`

**Comment by theArthuryus** [comment]
Sorry for the long post, I am still learning.

**Comment by ryanmjordan** [comment]
I am having the same error. I think it is having trouble cloning the following repo? I had to install the git package through conda and run as an Administrator to get this far. Not entirely sure how to fix this on my own. I don't usually use Python on Windows. I pasted the important stuff below:  
  
```
(avatarify) C:\Windows\System32\avatarify>call git clone https://github.com/alievk/first-order-model.git fomm
'git' is not recognized as an internal or external command,
operable program or batch file.

(avatarify) C:\Windows\System32\avatarify>call pip install -r fomm/requirements.txt
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'fomm/requirements.txt'

(avatarify) C:\Windows\System32\avatarify>call pip install requests
Collecting requests
  Using cached requests-2.23.0-py2.py3-none-any.whl (58 kB)
Requirement already satisfied: certifi>=2017.4.17 in c:\programdata\miniconda3\envs\avatarify\lib\site-packages (from requests) (2020.4.5.1)
Collecting idna<3,>=2.5
  Using cached idna-2.9-py2.py3-none-any.whl (58 kB)
Collecting urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1
  Using cached urllib3-1.25.8-py2.py3-none-any.whl (125 kB)
Collecting chardet<4,>=3.0.2
  Using cached chardet-3.0.4-py2.py3-none-any.whl (133 kB)
Installing collected packages: idna, urllib3, chardet, requests
Successfully installed chardet-3.0.4 idna-2.9 requests-2.23.0 urllib3-1.25.8
```

**Comment by theArthuryus** [comment]
Install error still remains. 
Run error: if I install yaml on this instance the error goes away and another one shows
```
Traceback (most recent call last):
  File "cam_fomm.py", line 13, in <module>
    from sync_batchnorm import DataParallelWithCallback
ModuleNotFoundError: No module named 'sync_batchnorm'
```

**Comment by alievk** [comment]
Please install [Git](https://git-scm.com/download/win) and choose "Git from the command line and also from the 3-rd party software" at "Adjusting your PATH environment step"

**Comment by theArthuryus** [comment]
thanks, that was real noob of me. 
Installation worked (it created a folder "avatarify" "whithin avatarify-master" folder) in which I had to put the "vox-adv-cpk.pth". Eventually when running it solves the issue I was having, and it wasnt even necessary to install "Yaml module" as I had done. 

 I am getting another error when running it, but it isnt related to this issue. So I will open another.
