### ISSUE TITLE
Windows version?

### ISSUE THREAD

**Issue by DenisSergeevitch** [alievk/avatarify#4]
Hi, thanks for this amazing repo, did you tried to run this code on Windows?

**Comment by alievk** [comment]
Hi,
No, we haven't. I guess it's possible to create virtual camera in Windows, so technically it will run on Windows too.

**Comment by karfly** [comment]
Hi! You can follow instructions for Mac, but instead of using CamTwist find some Windows analogue (https://alternativeto.net/software/camtwist/?platform=windows).

You need any software that can capture separate window and stream it to a virtual camera.

Please, share your findings with Windows here :)

**Comment by eyaler** [comment]
wfm in windows. used vmix to stream to zoom. this is pure awesomeness!

**Comment by alievk** [comment]
@eyaler awesome! 
Could you please describe your solution in detail so that the community would benefit from that?

**Comment by eyaler** [comment]
@alievk so i actually just got it working during a 1 hour zoom meetup just so i can connect as an avatar, and it was a dirty process... but it was so nice that i will be giving a meetup on FOMM and avatarify next week, so i will try streamline the installation process on a clean system in the next days. nothing to difficult just technicalities.

**Comment by DenisSergeevitch** [comment]
@eyaler Hi, could you please explain what "wfm in windows" mean? If you mean WSL it cant access CUDA drivers, no?

**Comment by eyaler** [comment]
@DenisSergeevitch WFM = works for me :)

**Comment by DenisSergeevitch** [comment]
@eyaler but how did you run .sh files? :) I just dont get it how to it without second OS

**Comment by alievk** [comment]
Added Windows version, closing the issue.
