### ISSUE TITLE
command no found 

### ISSUE THREAD

**Issue by starking8b** [alievk/avatarify#40]
hello , I get this error while running the script
`$ sudo bash run.sh 
run.sh: line 9: conda: command not found
run.sh: line 9: /etc/profile.d/conda.sh: No such file or directory
run.sh: line 10: conda: command not found
  File "cam_fomm.py", line 36
    generator = OcclusionAwareGenerator(**config['model_params']['generator_params'],
                                                                                    ^
SyntaxError: invalid syntax
`

**Comment by alievk** [comment]
Download miniconda https://docs.conda.io/en/latest/miniconda.html#linux-installers
Run `bash Miniconda3-latest-Linux-x86_64.sh`

**Comment by starking8b** [comment]
I installed miniconda and actually I had anaconda also

**Comment by starking8b** [comment]
the problem still

**Comment by kuzdogan** [comment]
In my case, I didn't see the miniconda3 folder when I `ls /root/`. I reinstalled conda3 WITH saying yes to the initialization option.

Then I executed `sudo -i` and `bash run.sh`

**Comment by alievk** [comment]
Make sure you downloaded conda with Python3.7 .

You don't have to run `scripts/install.sh` as sudo.

**Comment by RazZziel** [comment]
Is the conda dependency really needed?

It seems to run well replacing conda with plain python and virtualenv:

```shell
git submodule update --init

virtualenv .venv
.venv/bin/pip install -r fomm/requirements.txt
.venv/bin/pip install face-alignment pyfakewebcam requests

sudo modprobe -r v4l2loopback
sudo modprobe v4l2loopback devices=1 video_nr=20 card_label="v4l2loopback" exclusive_caps=1

PYTHONPATH=$PYTHONPATH:$(pwd)/fomm .venv/bin/python cam_fomm.py --config fomm/config/vox-adv-256.yaml --checkpoint vox-adv-cpk.pth.tar --cam 0 --virt-cam 20 --relative --adapt_scale
```

**Comment by alievk** [comment]
What's wrong with conda? :)
