### ISSUE TITLE
AVATAR cam shaking...

### ISSUE THREAD

**Issue by ZeroCool22** [alievk/avatarify#41]
I run it on Windows (thx to this tutorial: https://www.youtube.com/watch?v=i0XBGXnyejg), but the problem is te AVATAR cam shakes always a little, even if i'm very quiet.
What could be the problem?

**Comment by alievk** [comment]
One possible reason is poor lightning. The algorithm relies on face keypoints which may jitter in bad lighting conditions due to ISO noise.

**Comment by Waykon12** [comment]
Alievk 
How can you help me install avatarify without issues . Mine shakes alot

**Comment by JohanAR** [comment]
@Waykon12 "install" a lamp next to your computer or buy a better web cam.

What alievk said means that shaking avatar happens when the image from the camera is too noisy. Having more light on your face reduces the noise in the image.
