### ISSUE TITLE
Can I change the CPU?

### ISSUE THREAD

**Issue by amgdy** [alievk/avatarify#42]
Can I run the app using CPU1 not 0?

**Comment by alievk** [comment]
You mean GPU?

**Comment by amgdy** [comment]
Yes, sorry GPU. Can I run it on Intel? or has to be NVidia?

**Comment by alievk** [comment]
It need to be NVidia at the moment.

**Comment by amgdy** [comment]
The issue is I do have NVidia Quadro K1100M and it recognize it as an old gpu and it doesn't work with it.
