### ISSUE TITLE
modprobe: ERROR: could not insert 'v4l2loopback': Operation not permitted

### ISSUE THREAD

**Issue by kuzdogan** [alievk/avatarify#43]
### OS Version 
Ubuntu  19.10

When I'm trying to run `bash run.sh` I see following errors:
```
Creating virtual camera /dev/video9 (sudo privelege required)
modprobe: ERROR: could not insert 'v4l2loopback': Operation not permitted
0: ./avatars/einstein.jpg
... #similar lines
7: ./avatars/schwarzenegger.png
load checkpoints..
cam_fomm.py:34: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  config = yaml.load(f)
--- Make sure the v4l2loopback kernel module is loaded ---
sudo modprobe v4l2loopback devices=1
Traceback (most recent call last):
  File "cam_fomm.py", line 230, in <module>
    stream = pyfakewebcam.FakeWebcam(f'/dev/video{opt.virt_cam}', frame.shape[1], frame.shape[0])
  File "/root/miniconda3/envs/avatarify/lib/python3.8/site-packages/pyfakewebcam/pyfakewebcam.py", line 31, in __init__
    raise FileNotFoundError('device does not exist: {}'.format(video_device))
FileNotFoundError: device does not exist: /dev/video9
```
I am not familiar with conda environments so maybe it could be the problem. On terminal I see it's running the base environment:
```
(base) kuzdogan@kuzdogan-UX331UN
```

Another thing to notice is I can only run `bash run.sh` as a root user so after `sudo -i`. If I run `sudo bash run.sh` I get 
```
run.sh: line 9: conda: command not found
run.sh: line 9: /etc/profile.d/conda.sh: No such file or directory
run.sh: line 10: conda: command not found
```

Thank you

**Comment by alievk** [comment]
Normally you don't have to run run.sh as sudo, it will ask you sudo pass for loading v4l2loopback kernel module. Does this happen?

**Comment by potassium-chloride** [comment]
I have the same problem in Cinnamon 19.3. I catched #37 and tried to solve it. install.sh cloned and made v4l2loopback driver successfully but module was not signed.

**Comment by kuzdogan** [comment]
@alievk yes I am getting exactly the same error

**Comment by grschtroumpf** [comment]
same issue here

**Comment by alievk** [comment]
This may be relevant https://github.com/xairy/unlockdown#method-0-sysrq-trigger

**Comment by potassium-chloride** [comment]
@alievk this method equivalents `sudo echo x > /proc/sysrq-trigger` and causes same effect (help line in dmesg). This problem is related to security boot and security police in last versions of Linux Kernel. Module should be signed. I think the true way would be to ask the v4l2loopback developers about this and publish signed v4l2loopback module
