### ISSUE TITLE
Add virtual soundcard adding the same delay as the avatarified video

### ISSUE THREAD

**Issue by brozkeff** [alievk/avatarify#44]
The avatar video delay can desync a lot with the actual sound.
Adding a fake sound card adding exactly or approximately the same delay to the mic input, and picking this sound card mic in the Zoom/any other SW instead of the real non-delayed mic would re-sync the video and audio, making the result much more authentic.

**Comment by alievk** [comment]
This is problematic as delay depends on the specific hardware. It is also non-trivial to measure the video latency.
