### ISSUE TITLE
No Sync_batchnorm

### ISSUE THREAD

**Issue by celeronpm** [alievk/avatarify#45]
Trying to run on windows, error:

Traceback (most recent call last):
  File "cam_fomm.py", line 13, in <module>
    from sync_batchnorm import DataParallelWithCallback
ModuleNotFoundError: No module named 'sync_batchnorm'

**Comment by exgllo** [comment]
Traceback (most recent call last):
  File "cam_fomm.py", line 13, in <module>
    from sync_batchnorm import DataParallelWithCallback
ModuleNotFoundError: No module named 'sync_batchnorm'

**Comment by html5css3-pro** [comment]
The same situation with macOS

Traceback (most recent call last):
  File "cam_fomm.py", line 13, in <module>
    from sync_batchnorm import DataParallelWithCallback
ModuleNotFoundError: No module named 'sync_batchnorm'

**Comment by AndreasW79** [comment]
Same here, Windows 10 latest.
`Traceback (most recent call last):
  File "cam_fomm.py", line 13, in <module>
    from sync_batchnorm import DataParallelWithCallback
ModuleNotFoundError: No module named 'sync_batchnorm'`

**Comment by alievk** [comment]
Do you run run_windows.bat from avatarify root folder?
Is fomm in avatarify folder?
Where there any errors during installation?

**Comment by AndreasW79** [comment]
Thanks for the fast reply.  
fomm is inside the scripts folder.
run_windows.bat is in root folder, there was it started from.
No errors during installation.

**Comment by alievk** [comment]
@AndreasW79 you ran install_windows.bat from the scripts folder, but you have to do it from the root avatarify folder, as it is mentioned in the readme.

**Comment by AndreasW79** [comment]
> @AndreasW79 you ran install_windows.bat from the scripts folder, but you have to do it from the root avatarify folder, as it is mentioned in the readme.

yes after your first reply i guess it could be that... will start with a fresh install.

**Comment by html5css3-pro** [comment]
i've updated python to version 3 and it is works now

**Comment by virajs16** [comment]
@alievk facing the same issue on mac. I have both run_mac.sh and cam.fomm.py in the root folder

**Comment by celeronpm** [comment]
> @AndreasW79 you ran install_windows.bat from the scripts folder, but you have to do it from the root avatarify folder, as it is mentioned in the readme.

Now I get: 

cam_fomm.py:34: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  config = yaml.load(f)
Traceback (most recent call last):
  File "cam_fomm.py", line 215, in <module>
    generator, kp_detector = load_checkpoints(config_path=opt.config, checkpoint_path=opt.checkpoint, device=device)
  File "cam_fomm.py", line 44, in load_checkpoints
    checkpoint = torch.load(checkpoint_path, map_location=device)
  File "C:\Users\md101064\Miniconda3\envs\avatarify\lib\site-packages\torch\serialization.py", line 525, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "C:\Users\md101064\Miniconda3\envs\avatarify\lib\site-packages\torch\serialization.py", line 212, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "C:\Users\md101064\Miniconda3\envs\avatarify\lib\site-packages\torch\serialization.py", line 193, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'vox-adv-cpk.pth.tar'

**Comment by alievk** [comment]
@celeronpm did you download and put `vox-adv-cpk.pth.tar` into avatar root directory?

**Comment by celeronpm** [comment]
> @celeronpm did you download and put `vox-adv-cpk.pth.tar` into avatar root directory?

All this was user error, thanks for helping!
