### ISSUE TITLE
I get this output when I run the script

### ISSUE THREAD

**Issue by starking8b** [alievk/avatarify#46]
Error: BadDrawable (invalid Pixmap or Window parameter) 9
  Major opcode: 62 (X_CopyArea)
  Resource id:  0x5a00013
X Error: BadDrawable (invalid Pixmap or Window parameter) 9
  Major opcode: 62 (X_CopyArea)
  Resource id:  0x5a00011

**Comment by E3V3A** [comment]
Not enough info! Please post more details with *OS, info, versions* with *screenshots* and *commands* + (text) *output* leading up to the issue. Otherwise close this.
