### ISSUE TITLE
Unable to see "[python.exe]: avatarify" in Window drop-down menu in OBS Windows Capture dropdown

### ISSUE THREAD

**Issue by nirmalashome** [alievk/avatarify#47]
Hi there, thanks for creating this. I followed the instructions for Windows and completed step 5. I saw this message in the Anaconda Prompt:

Successfully installed chardet-3.0.4 idna-2.9 requests-2.23.0 urllib3-1.25.9

When I try to complete step 9. to step up the window capture in OBS I don't see the option for "[python.exe]: avatarify".

I've kept the Anaconda prompt window open and moved the .tar file into the root folder too. Is there anything else I'm missing?

**Comment by theArthuryus** [comment]
Are there two screens, one with your webcam and the other the manipulated image, showing?
If so, try to close OBS, open and create new profile.

**Comment by jfwyatt** [comment]
I'm having the same issue (Windows 10). Only 1 screen, closed OBS and created a new profile, still don't see [python.exe]: avatarify in the drop down. 

**Anaconda Prompt:**
Successfully installed chardet-3.0.4 idna-2.9 requests-2.23.0 urllib3-1.25.9

Not sure what I missed - any ideas?

**Comment by jfwyatt** [comment]
Decided to just burn everything & try again. It's working now, not sure what I missed the first time.

**Comment by nirmalashome** [comment]
I'll try again too and see what happens - thanks

**Comment by nirmalashome** [comment]
Not sure if this is the issue but when I try and open the run_windows in the avatarify folder I get this pop up for a second before closing again.

![image](https://user-images.githubusercontent.com/19733498/79616942-a2137000-8149-11ea-9987-48f428322e72.png)

**Comment by alievk** [comment]
@nirmalashome you mean this "pick the webcam id ..." line?

**Comment by nirmalashome** [comment]
Yes that's right - do I need to assign the web cam and where would I do this. This message only popped up for a second before automatically closing on me. I also only have a single webcam. Thanks for your help so far.

**Comment by alievk** [comment]
That's just a blank message, will remove it.
Follow instructions to set the camera https://github.com/alievk/avatarify#windows-1

**Comment by bartosz-pluta** [comment]
I had same problem like rest. I think this is important. After installation in C:/Users/<myusername> everythings went good

**Comment by kamseydgenius** [comment]
i know this was created years ago, I just hope there is still someone here to respond, i cannot find [python.exe]: avatarify in windows of OBS studio, i could really use urgent help on hoe to go about this or possible suggestions on causes, thanks. aynone?

**Comment by geekedpriest** [comment]
Any idea on how to run Avatarify on Mac, I have it installed but I don't know how to run it .![image](https://user-images.githubusercontent.com/120290986/232176804-adf46fb5-c982-4838-82ef-8fae87eb2971.jpeg) i am stuck here
