### ISSUE TITLE
Running on win10, i7 and 1070gtx poor results

### ISSUE THREAD

**Issue by theArthuryus** [alievk/avatarify#48]
First of, thanks for the help into having it running.  It seems that it isnt using my gpu, thus less than 1fps and weird warping at frames.  My face is fully lit, centered and plain background.
Check it out.
![image](https://user-images.githubusercontent.com/29991898/79572241-fa3b6b00-8092-11ea-8475-26ebe7998d78.png)

**Comment by ThomasBarth** [comment]
Yep, have the same. 
Win 10,  Ryzen 7 3800X, Radeon RX590, 16GB RAM. Runs with 60% CPU load and same result as mentioned.

**Comment by theArthuryus** [comment]
I just replaced the webcam video output to Avatarify with a GIF of Obama moving his lips through OBS and though still less than 1fps, it didnt warp. So I am guessing the warping is related to the capture while the subject in front of the webcam (me) isnt completely still during the slow process of converting to the model.

![image](https://user-images.githubusercontent.com/29991898/79573968-d3caff00-8095-11ea-94fe-db4dd5f2f462.png)

**Comment by ThomasBarth** [comment]
I guess the resolution of the input also is quiet low? this way we might eliminate the webcam resolution as primary issue.

**Comment by theArthuryus** [comment]
I lowered the resolution to 150x120 pixels and still less than 1fps.
![image](https://user-images.githubusercontent.com/29991898/79574947-5b653d80-8097-11ea-95cb-956cbd745fae.png)

**Comment by theArthuryus** [comment]
> Yep, have the same.
> Win 10, Ryzen 7 3800X, Radeon RX590, 16GB RAM. Runs with 60% CPU load and same result as mentioned.
> 
> Webcam is 720p, maybe that's too high.

Regarding using radeon cards, I found this in one of the issues:
https://github.com/alievk/avatarify/issues/9#issuecomment-611448118

but it seems that our gpu's arent being used at all

**Comment by ThomasBarth** [comment]
> > Yep, have the same.
> > Win 10, Ryzen 7 3800X, Radeon RX590, 16GB RAM. Runs with 60% CPU load and same result as mentioned.
> > Webcam is 720p, maybe that's too high.
> 
> Regarding using radeon cards, I found this in one of the issues:
> [#9 (comment)](https://github.com/alievk/avatarify/issues/9#issuecomment-611448118)
> 
> but it seems that our gpu's arent being used at all

I see, nope no CUDA and also not used (obviously).

**Comment by alievk** [comment]
Pytorch (a library for running neural network under the hood) heavily relies on CUDA. It's a shame :(

**Comment by theArthuryus** [comment]
> Pytorch (a library for running neural network under the hood) heavily relies on CUDA. It's a shame :(

Yeah, but in my case, running a gtx 1070 should have around 15fps no?

**Comment by theArthuryus** [comment]
![image](https://user-images.githubusercontent.com/29991898/79608967-435be100-80cc-11ea-88e9-d7682bd29194.png)

**Comment by alievk** [comment]
@theArthuryus Please try to install [CUDA](https://developer.nvidia.com/cuda-downloads?target_os=Windows&target_arch=x86_64&target_version=10&target_type=exenetwork) and write back if that helped

**Comment by theArthuryus** [comment]
I couldve sworn I had already installed CUDA. Working flawlessly.  GPU at 30% and fps around 15-20.
Thanks, great work by the way!
