### ISSUE TITLE
Join Slack!

### ISSUE THREAD

**Issue by alievk** [alievk/avatarify#49]
We’ve created Slack for Avatarify community! Please join:
[<img src="https://img.shields.io/badge/slack-join-brightgreen?style=flat&logo=slack">](https://join.slack.com/t/avatarify/shared_invite/zt-dyoqy8tc-~4U2ObQ6WoxuwSaWKKVOgg)

There you can ask any questions to get quick answers, discuss ideas of new features, share works you created using Avatarify and more.

**Comment by 18845045369** [comment]
When run_windows.bat
![问题截图](https://user-images.githubusercontent.com/64247303/80855899-c73ecd00-8c77-11ea-961c-0b7bd89166a5.jpg)

**Comment by 18845045369** [comment]
Problem complement:This is a problem that I downloaded and sent to my friend on his computer

**Comment by alievk** [comment]
I decided to stop supporting Slack group since it's easier and more productive to track issues on GitHub. You can still join the group, but I will maintain only GitHub issues from now.

Thank you!
