### ISSUE TITLE
OpenCV error on Mac OS

### ISSUE THREAD

**Issue by giorgiop** [alievk/avatarify#5]
`bash run_mac.sh` hangs at:

```
[ERROR:0] global /Users/travis/build/skvark/opencv-python/opencv/modules/videoio/src/cap.cpp (193) open VIDEOIO(AVFOUNDATION): raised unknown C++ exception!


Cannot open camera
```

**Comment by no-karma-no-cry** [comment]
> `bash run_mac.sh` hangs at:
> 
> ```
> [ERROR:0] global /Users/travis/build/skvark/opencv-python/opencv/modules/videoio/src/cap.cpp (193) open VIDEOIO(AVFOUNDATION): raised unknown C++ exception!
> 
> 
> Cannot open camera
> ```

Try to change `CAMID` in `run_mac.sh` from `0` to `1` or `2`

**Comment by giorgiop** [comment]
That solved it, thanks.

**Comment by YubinXie** [comment]
Changing to 2 works for me.

**Comment by patni11** [comment]
> > `bash run_mac.sh` hangs at:
> > ```
> > [ERROR:0] global /Users/travis/build/skvark/opencv-python/opencv/modules/videoio/src/cap.cpp (193) open VIDEOIO(AVFOUNDATION): raised unknown C++ exception!
> > 
> > 
> > Cannot open camera
> > ```
> 
> Try to change `CAMID` in `run_mac.sh` from `0` to `1` or `2`

Can you please tell how todo that?

**Comment by karfly** [comment]
@patni11, first check that you use the latest version of Avatarify.
If you have the latest on, open `./scripts/settings.sh` with any text editor and change `MAC_CAMID=2` to `MAC_CAMID=0`, `MAC_CAMID=1` or other values.
