### ISSUE TITLE
No module named 'sync_batchnorm'

### ISSUE THREAD

**Issue by newtonke** [alievk/avatarify#50]
Windows 10 system. 

Traceback (most recent call last):
  File "cam_fomm.py", line 13, in <module>
    from sync_batchnorm import DataParallelWithCallback
ModuleNotFoundError: No module named 'sync_batchnorm'

**Comment by newtonke** [comment]
run from the application root directory, tar file is in the avatar dir

**Comment by alievk** [comment]
Where there any errors during installation?

**Comment by Melvin-Abraham** [comment]
Did you change directory to **"scripts"** folder before executing `install_windows.bat`? Make sure you install from the root directory of *"avatarify"*:

```batch
drive:\somepath\avtarify> scripts\install_windows.bat
```

**Comment by bazmatic** [comment]
I'm got same error. `ModuleNotFoundError: No module named 'sync_batchnorm'`

Then I re-ran `scripts/install_windows.bat` from the root directory and observed the following error:

```ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'fomm/requirements.txt'```

Could be a clue?

**Comment by bobrich** [comment]
There's something very broken with the batch files on windows 10.  
 
Open the batch files up in notepad and copy them to the windows command line and execute them one by one.

Also make sure that Miniconda's install and install\scripts directory are at the front of your PATH 

Once that is all done you have to do the same thing with the run_windows.bat file

**Comment by alievk** [comment]
@bazmatic any errors during installation?
Try to swipe off avatarify directory and start again.

**Comment by bazmatic** [comment]
I'll start again and watch the installation log like a hawk this time.

**Comment by bazmatic** [comment]
Indeed, I found an error: `ERROR conda.core.link:_execute(700): An error occurred while installing package 'defaults::vs2015_runtime-14.16.27012-hf0eaf9b_1'.`

Here's the full context:
```(base) C:\projects\avatarify>scripts\install_windows.bat

(base) C:\projects\avatarify>call scripts/settings_windows.bat

(base) C:\projects\avatarify>REM Web-camera device id

(base) C:\projects\avatarify>set CAMID=0

(base) C:\projects\avatarify>REM ################################################

(base) C:\projects\avatarify>REM Normally you don't want to change settings below

(base) C:\projects\avatarify>REM Conda environment name

(base) C:\projects\avatarify>set CONDA_ENV_NAME=avatarify

(base) C:\projects\avatarify>call conda create -y -n avatarify python=3.8
Collecting package metadata (current_repodata.json): done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.8.2
  latest version: 4.8.3

Please update conda by running

    $ conda update -n base -c defaults conda



## Package Plan ##

  environment location: C:\Users\barry\miniconda3\envs\avatarify

  added / updated specs:
    - python=3.8


The following NEW packages will be INSTALLED:

  ca-certificates    pkgs/main/win-64::ca-certificates-2020.1.1-0
  certifi            pkgs/main/win-64::certifi-2020.4.5.1-py38_0
  openssl            pkgs/main/win-64::openssl-1.1.1f-he774522_0
  pip                pkgs/main/win-64::pip-20.0.2-py38_1
  python             pkgs/main/win-64::python-3.8.2-h5fd99cc_11
  setuptools         pkgs/main/win-64::setuptools-46.1.3-py38_0
  sqlite             pkgs/main/win-64::sqlite-3.31.1-he774522_0
  vc                 pkgs/main/win-64::vc-14.1-h0510ff6_4
  vs2015_runtime     pkgs/main/win-64::vs2015_runtime-14.16.27012-hf0eaf9b_1
  wheel              pkgs/main/win-64::wheel-0.34.2-py38_0
  wincertstore       pkgs/main/win-64::wincertstore-0.2-py38_0


Preparing transaction: done
Verifying transaction: done
Executing transaction: done
ERROR conda.core.link:_execute(700): An error occurred while installing package 'defaults::vs2015_runtime-14.16.27012-hf0eaf9b_1'.
Rolling back transaction: done

[Errno 13] Permission denied: 'C:\\Users\\barry\\miniconda3\\envs\\avatarify\\vcruntime140.dll'
()
```

I then attempted @bobrich 's suggestion and ran each command manually. It worked. The application ran successfully.

**Comment by alievk** [comment]
@bazmatic could you also include the entire log when installing the way @bobrich suggested?

**Comment by JpEncausse** [comment]
> I then attempted @bobrich 's suggestion and ran each command manually. It worked. The application ran successfully.

Same here, thanks !

**Comment by baganaakh** [comment]
same error debian linux

**Comment by JoelSund** [comment]
Same here windows 10:


`(avatarify) A:\app\avatarify>call git clone https://github.com/alievk/first-order-model.git fomm
'git' n’est pas reconnu en tant que commande interne
ou externe, un programme exécutable ou un fichier de commandes.

(avatarify) A:\app\avatarify>call pip install -r requirements.txt
Collecting cloudpickle==0.5.3
  Using cached cloudpickle-0.5.3-py2.py3-none-any.whl (13 kB)
Collecting cycler==0.10.0
  Using cached cycler-0.10.0-py2.py3-none-any.whl (6.5 kB)
Collecting dask==0.18.2
  Using cached dask-0.18.2-py2.py3-none-any.whl (645 kB)
Collecting decorator==4.3.0
  Using cached decorator-4.3.0-py2.py3-none-any.whl (9.2 kB)
Collecting imageio==2.3.0
  Using cached imageio-2.3.0-py2.py3-none-any.whl (3.3 MB)
Collecting kiwisolver==1.0.1
  Using cached kiwisolver-1.0.1-cp37-none-win_amd64.whl (57 kB)
Collecting matplotlib==2.2.2
  Using cached matplotlib-2.2.2-cp37-cp37m-win_amd64.whl (8.7 MB)
Processing c:\users\py_user\appdata\local\pip\cache\wheels\48\b1\c4\94ca0cdd84961331402e857d562d9822ccfcb0567c3d064bf2\networkx-2.1-py2.py3-none-any.whl
Collecting numpy==1.15.0
  Using cached numpy-1.15.0-cp37-none-win_amd64.whl (13.5 MB)
Collecting pandas==0.23.4
  Using cached pandas-0.23.4-cp37-cp37m-win_amd64.whl (7.9 MB)
Collecting Pillow==6.2.2
  Using cached Pillow-6.2.2-cp37-cp37m-win_amd64.whl (2.0 MB)
Processing c:\users\py_user\appdata\local\pip\cache\wheels\5d\c6\29\87a8bb797e60b55a91bd0a1e8455365c5f5dff9fc45c05f3e4\pycparser-2.18-py2.py3-none-any.whl
Processing c:\users\py_user\appdata\local\pip\cache\wheels\ab\fa\ec\ea49bbbceea9f691dbe68d47e4b4272d1153fe6ab09ffe3eaa\pygit-0.1-py3-none-any.whl
Collecting pyparsing==2.2.0
  Using cached pyparsing-2.2.0-py2.py3-none-any.whl (56 kB)
Collecting python-dateutil==2.7.3
  Using cached python_dateutil-2.7.3-py2.py3-none-any.whl (211 kB)
Collecting pytz==2018.5
  Using cached pytz-2018.5-py2.py3-none-any.whl (510 kB)
Collecting PyWavelets==0.5.2
  Using cached PyWavelets-0.5.2-cp37-none-win_amd64.whl (4.2 MB)
Collecting PyYAML==5.1
  Using cached PyYAML-5.1-cp37-cp37m-win_amd64.whl (215 kB)
Collecting scikit-image==0.14.0
  Using cached scikit_image-0.14.0-cp37-none-win_amd64.whl (24.6 MB)
Collecting scikit-learn==0.19.2
  Using cached scikit_learn-0.19.2-cp37-cp37m-win_amd64.whl (4.4 MB)
Collecting scipy==1.1.0
  Using cached scipy-1.1.0-cp37-none-win_amd64.whl (30.9 MB)
Collecting six==1.11.0
  Using cached six-1.11.0-py2.py3-none-any.whl (10 kB)
Processing c:\users\py_user\appdata\local\pip\cache\wheels\58\85\f9\3a8ac8d6acedfb76fb78ed9dedd7b5c86dc5bfdef4b2427219\toolz-0.9.0-py3-none-any.whl
Collecting tqdm==4.24.0
  Using cached tqdm-4.24.0-py2.py3-none-any.whl (43 kB)
Collecting requests==2.23
  Using cached requests-2.23.0-py2.py3-none-any.whl (58 kB)
Collecting face-alignment==1.0.0
  Using cached face_alignment-1.0.0-py2.py3-none-any.whl (22 kB)
Processing c:\users\py_user\appdata\local\pip\cache\wheels\33\7e\9f\0fe880831cd6c9f55dc616885118bab53104c580e635fbe415\pyfakewebcam-0.1.0-py3-none-any.whl
Requirement already satisfied: setuptools in c:\users\py_user\miniconda3\envs\avatarify\lib\site-packages (from kiwisolver==1.0.1->-r requirements.txt (line 7)) (46.1.3.post20200330)
Collecting idna<3,>=2.5
  Using cached idna-2.9-py2.py3-none-any.whl (58 kB)
Collecting chardet<4,>=3.0.2
  Using cached chardet-3.0.4-py2.py3-none-any.whl (133 kB)
Collecting urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1
  Using cached urllib3-1.25.9-py2.py3-none-any.whl (126 kB)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\py_user\miniconda3\envs\avatarify\lib\site-packages (from requests==2.23->-r requirements.txt (line 28)) (2020.4.5.1)
Collecting opencv-python
  Using cached opencv_python-4.2.0.34-cp37-cp37m-win_amd64.whl (33.0 MB)
Requirement already satisfied: torch in c:\users\py_user\miniconda3\envs\avatarify\lib\site-packages (from face-alignment==1.0.0->-r requirements.txt (line 29)) (1.0.0)
Installing collected packages: cloudpickle, six, cycler, dask, decorator, Pillow, numpy, imageio, kiwisolver, pytz, python-dateutil, pyparsing, matplotlib, networkx, pandas, pycparser, pygit, PyWavelets, PyYAML, scikit-image, scikit-learn, scipy, toolz, tqdm, idna, chardet, urllib3, requests, opencv-python, face-alignment, pyfakewebcam
  Attempting uninstall: six
    Found existing installation: six 1.14.0
    Uninstalling six-1.14.0:
      Successfully uninstalled six-1.14.0
  Attempting uninstall: Pillow
    Found existing installation: Pillow 7.0.0
    Uninstalling Pillow-7.0.0:
      Successfully uninstalled Pillow-7.0.0
  Attempting uninstall: numpy
    Found existing installation: numpy 1.18.1
    Uninstalling numpy-1.18.1:
      Successfully uninstalled numpy-1.18.1
  Attempting uninstall: pycparser
    Found existing installation: pycparser 2.20
    Uninstalling pycparser-2.20:
      Successfully uninstalled pycparser-2.20
Successfully installed Pillow-6.2.2 PyWavelets-0.5.2 PyYAML-5.1 chardet-3.0.4 cloudpickle-0.5.3 cycler-0.10.0 dask-0.18.2 decorator-4.3.0 face-alignment-1.0.0 idna-2.9 imageio-2.3.0 kiwisolver-1.0.1 matplotlib-2.2.2 networkx-2.1 numpy-1.15.0 opencv-python-4.2.0.34 pandas-0.23.4 pycparser-2.18 pyfakewebcam-0.1.0 pygit-0.1 pyparsing-2.2.0 python-dateutil-2.7.3 pytz-2018.5 requests-2.23.0 scikit-image-0.14.0 scikit-learn-0.19.2 scipy-1.1.0 six-1.11.0 toolz-0.9.0 tqdm-4.24.0 urllib3-1.25.9





(avatarify) A:\app\avatarify>conda update -n base -c defaults conda
Collecting package metadata (current_repodata.json): done
Solving environment: done

# All requested packages already installed.





(avatarify) A:\app\avatarify>

(avatarify) A:\app\avatarify>run_windows.bat

(avatarify) A:\app\avatarify>REM Web-camera device id

(avatarify) A:\app\avatarify>set CAMID=0

(avatarify) A:\app\avatarify>REM ################################################

(avatarify) A:\app\avatarify>REM Normally you don't want to change settings below

(avatarify) A:\app\avatarify>REM Conda environment name

(avatarify) A:\app\avatarify>set CONDA_ENV_NAME=avatarify
Traceback (most recent call last):
  File "cam_fomm.py", line 14, in <module>
    from sync_batchnorm import DataParallelWithCallback
ModuleNotFoundError: No module named 'sync_batchnorm'
`

**Comment by canDry** [comment]
If you don't install git this line in the install_windows.bat will silently fail:
`call git clone https://github.com/alievk/first-order-model.git fomm`
So... you'd need to create the fomm subdirectory and extract all the files manually into fomm from the fomm git file.

**Comment by kunkka234** [comment]
I'm using win10, met same problem and found the reason is that i didn't install git for windows.

At first i only installed git in miniconda, but it's not enough. 
When running install_windows.bat, it failed in "call git clone https://github.com/alievk/first-order-model.git fomm", so in the later run_windows the error occured in cam_fomm.py

My solution is to install git for windows, restart miniconda and run from install_windows.bat.
Everything works fine for me now

**Comment by JoelSund** [comment]
For me, solution was to re-install git 32 (instead of git 64). It works now. Thank you @alievk

**Comment by hmartinbarroso** [comment]
The same problem on a MAC:

bash run_mac.sh
Traceback (most recent call last):
  File "cam_fomm.py", line 13, in <module>
    from sync_batchnorm import DataParallelWithCallback
ModuleNotFoundError: No module named 'sync_batchnorm'

**Comment by JoelSund** [comment]
> The same problem on a MAC:
> 
> bash run_mac.sh
> Traceback (most recent call last):
> File "cam_fomm.py", line 13, in
> from sync_batchnorm import DataParallelWithCallback
> ModuleNotFoundError: No module named 'sync_batchnorm'

Try to re install git

**Comment by Pratyush-DS** [comment]
Traceback (most recent call last):
  File "cam_fomm.py", line 12, in <module>
    from sync_batchnorm import DataParallelWithCallback
ModuleNotFoundError: No module named 'sync_batchnorm'
i have installed from root dir 
using python 3.8
