### ISSUE TITLE
Doesn't seem to use GPU

### ISSUE THREAD

**Issue by nelsonblaha** [alievk/avatarify#51]
Installation was easy on Ubuntu 18.04, but I don't think my GPU is in use based on nvidia-smi. Is that even possible?

**Comment by nelsonblaha** [comment]
I see only xorg and gnome processes in `nvidia-smi`, if that's any indication

**Comment by karfly** [comment]
Hi, @nelsonblaha.
Please check that PyTorch can see the GPU by running these lines in bash:
```bash
conda activate avatarify
python -c "import torch; print(torch.cuda.is_available())"
```

**Comment by 3atharvkurdukar** [comment]
It displays `True` but still uses CPU all the time.

**Comment by alievk** [comment]
@3atharvkurdukar what is your system?

**Comment by 3atharvkurdukar** [comment]
Intel i5-7300HQ
12GB DDR4 RAM
Nvidia GTX 1050 4GB

**Comment by alievk** [comment]
OS?

**Comment by 3atharvkurdukar** [comment]
Windows 10 1909 x64

**Comment by alievk** [comment]
Where there any errors during installation?

**Comment by 3atharvkurdukar** [comment]
No error while installation. I re-run the `install_windows.bat` to be sure. 
But, there are some warnings while running `run_windows.bat`
```
Here are the warnings I am getting:
cam_fomm.py:34: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the
default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  config = yaml.load(f)
C:\Users\3atha\.conda\envs\avatarify\lib\site-packages\torch\nn\functional.py:2705: UserWarning: Default grid_sample and affine_grid behavior has changed to align_corners=False since 1.3.0. Please specify align_corners=True if the old behavior is desired. See the documentation of grid_sample for details.
  warnings.warn("Default grid_sample and affine_grid behavior has changed "
C:\Users\3atha\.conda\envs\avatarify\lib\site-packages\torch\nn\functional.py:2503: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of
nn.Upsample for details.
  warnings.warn("Default upsampling behavior when mode={} is changed "
C:\Users\3atha\.conda\envs\avatarify\lib\site-packages\torch\nn\functional.py:1351: UserWarning: nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.
  warnings.warn("nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.")
```

**Comment by 3atharvkurdukar** [comment]
Here's the program in action. It works, but  uses CPU instead of GPU. The GPU1, which is the dedicated GPU, has 0% utilization.
![image](https://user-images.githubusercontent.com/19382880/79666872-78069000-81d3-11ea-9251-47c1d7457bd5.png)

**Comment by 3atharvkurdukar** [comment]
After some digging, I found out that it does use CUDA as the `device` variable gets set to `'cuda'`, but the usage is minimum, around 0% - 4%, while the main load is on CPU.

**Comment by alievk** [comment]
What does `torch.cuda.device_count()` return?

```
conda activate avatarify
python -c "import torch; print(torch.cuda.device_count())"
```

**Comment by 3atharvkurdukar** [comment]
It returns 1

**Comment by alievk** [comment]
And `https://github.com/xairy/unlockdown#method-0-sysrq-trigger` ?

**Comment by 3atharvkurdukar** [comment]
`4096`

**Comment by alievk** [comment]
It's mystical. Do you want to open an issue in pytorch repo?

**Comment by eponce92** [comment]
having exactly the same issue here. I followed all your questions and had same results as 3atharvkurdukar. System is i7 8700k, 2080ti, 32gb ram, running windows 10.

**Comment by alievk** [comment]
That's really weird, guys. What if you swipe off nvidia driver, cuda, then install the latest nvidia driver and don't install cuda?

cuda comes with older version of nvidia driver. Maybe that't the problem. especially with 2080ti.

**Comment by basemdabbour** [comment]
I received the same error, please note that yesterday it worked with GPU and everything went fine, even I got a message from ubuntu saying "GPU is low might affect your camera" something like that. but it's not working now and that's really weird !!!. 

do you know how can I fix this error or use CPU instead!!, I am using ubuntu 16.04 


(avatarify) stefan@stefan-XPS-15-9550:~/avatarify$ bash run.sh
Creating virtual camera /dev/video9 (sudo privelege required)
modprobe: FATAL: Module v4l2loopback not found in directory /lib/modules/4.4.0-177-generic
0: ./avatars/einstein.jpg
1: ./avatars/eminem.jpg
2: ./avatars/jobs.jpg
3: ./avatars/mona.jpg
4: ./avatars/obama.jpg
5: ./avatars/potter.jpg
6: ./avatars/ronaldo.png
7: ./avatars/schwarzenegger.png
load checkpoints..
Traceback (most recent call last):
  File "cam_fomm.py", line 219, in <module>
    generator, kp_detector = load_checkpoints(config_path=opt.config, checkpoint_path=opt.checkpoint, device=device)
  File "cam_fomm.py", line 45, in load_checkpoints
    checkpoint = torch.load(checkpoint_path, map_location=device)
  File "/home/stefan/miniconda3/envs/avatarify/lib/python3.8/site-packages/torch/serialization.py", line 593, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/stefan/miniconda3/envs/avatarify/lib/python3.8/site-packages/torch/serialization.py", line 773, in _legacy_load
    result = unpickler.load()
  File "/home/stefan/miniconda3/envs/avatarify/lib/python3.8/site-packages/torch/serialization.py", line 729, in persistent_load
    deserialized_objects[root_key] = restore_location(obj, location)
  File "/home/stefan/miniconda3/envs/avatarify/lib/python3.8/site-packages/torch/serialization.py", line 808, in restore_location
    return default_restore_location(storage, map_location)
  File "/home/stefan/miniconda3/envs/avatarify/lib/python3.8/site-packages/torch/serialization.py", line 178, in default_restore_location
    result = fn(storage, location)
  File "/home/stefan/miniconda3/envs/avatarify/lib/python3.8/site-packages/torch/serialization.py", line 158, in _cuda_deserialize
    return storage_type(obj.size())
  File "/home/stefan/miniconda3/envs/avatarify/lib/python3.8/site-packages/torch/cuda/__init__.py", line 433, in _lazy_new
    return super(_CudaBase, cls).__new__(cls, *args, **kwargs)
RuntimeError: CUDA out of memory. Tried to allocate 36.00 MiB (GPU 0; 1.96 GiB total capacity; 471.45 MiB already allocated; 25.69 MiB free; 492.00 MiB reserved in total by PyTorch)
(avatarify) stefan@stefan-XPS-15-9550:~/avatarify$ python -c "import torch; print(torch.cuda.is_available())"
True
(avatarify) stefan@stefan-XPS-15-9550:~/avatarify$ python -c "import torch; print(torch.cuda.device_count())"
1
(avatarify) stefan@stefan-XPS-15-9550:~/avatarify$ python -c "import torch; x = torch.zeros(1024).int().cuda();
> print(torch.cuda.memory_allocated(0))"
4096
(avatarify) stefan@stefan-XPS-15-9550:~/avatarify$

**Comment by E3V3A** [comment]
I just read somehwer in the nVidia setting docs that GPU performance is consdiered a Develper option for security reasons. Maybe this has soemthing to do with it? (I have the same zero results, with no sign of cuda running, but if I disable it with `set BLABLA=''` I get stalled. So something is running...

**Comment by basemdabbour** [comment]
Finally, it worked with me and using the GPU.
I just changed my operating system to use Fedora instead of ubuntu and everything went just perfect without asking me about any missing modules or CUDA problems. but unfortunately, I have a low VRAM and the streaming was not clear enough to do a call :) 

![1111](https://user-images.githubusercontent.com/32684082/79918523-d7aba800-842c-11ea-8a0c-c58898a4c82f.png)

**Comment by E3V3A** [comment]
That's cheating! ;)

**Comment by E3V3A** [comment]
Try to run this: 
https://github.com/alievk/avatarify/issues/98#issuecomment-617446727
for more CUDA info

**Comment by xtagon** [comment]
I'm also experiencing this, on two different machines, one a laptop with a Quadro T1000 and another a desktop with a RTX 2060. Both Windows 10.

The desktop has only the one dedicated GPU, no integrated - the laptop has an integrated Intel 620 as well, but strangely the PyTorch commands above all show the right results for device 0 having the name of the dedicated GPU. I even enabled the toolbar icon for Nvidia to show which applications are using that GPU, and when I run Avatarify it shows that it is using the GPU in the toolbar - but the GPU says at 0% in the task manager and the CPU is pegged to nearly maximum trying to keep up the framerate.

**Comment by E3V3A** [comment]
@xtagon 
> the GPU says at 0% in the task manager and the CPU is pegged to nearly maximum 

I now believe this is a Windows issue, as the *Task manager* (TM) reported percentage is (wrongly) averaged between each GPU "engine". (IDK what is an *engine* in case?) Thus if you're using 800 cores (or 27 engines) and 90% of total GPU power, it will show 90/800 = 0% (or 90/27 ~3%). 

In addition there are some number of GPU processor cores selections buried in the TM display settings, where you need to select cores...but it just doesn't make any sense...

---

![TM_GPU_1](https://user-images.githubusercontent.com/194392/80689448-0af9d100-8ad6-11ea-8f4b-f598229eb5dd.png)

![TM_GPU_2](https://user-images.githubusercontent.com/194392/80689452-0c2afe00-8ad6-11ea-9d53-30dcb0830a94.png)

---

You should use the `nvidia-smi` tool to [get the correct](https://nvidia.custhelp.com/app/answers/detail/a_id/3751/~/useful-nvidia-smi-queries) values. 
```bash
nvidia-smi --query-gpu=pci.bus_id,pstate,temperature.gpu,utilization.gpu,utilization.memory,memory.free,memory.used --format=csv -l 5
```

**Comment by xtagon** [comment]
@E3V3A Thanks! Got it to show up under the Cuda engine. I didn't realize it was possible to switch between the engines in task manager. It's showing a little over 50% on that engine.

![image](https://user-images.githubusercontent.com/47229/80887429-f4d54780-8c72-11ea-960d-cd07fb80da54.png)

**Comment by Nene020** [comment]
I have 12th Gen Intel core in-12900H, DDR5 64gb Ram and Nvidia 3080 16gb, but avatarify use cpu instead of GPU anyone has a solution yet?.

**Comment by MICKYGEM** [comment]
text your fps on my email or whatsapp
