### ISSUE TITLE
OpenCL support to increase performance on ATI Radeon cards

### ISSUE THREAD

**Issue by abdrakhmanov** [alievk/avatarify#53]
Can we use OpenCL instead of CUDA to increase performance when using ATI Radeon cards with Adrenalin drivers?

**Comment by weltonrodrigo** [comment]
This model uses an Pytorch model. Pytorch is compatible only with CUDA, which is available only to NVIDIA cards.

**Comment by alievk** [comment]
@abdrakhmanov that means moving from Pytorch to something else. OpenCL is not the best option in terms of performance. It's better to target specific hardware/OS.

@weltonrodrigo I would say more, Pytorch pre-built package isn't supporting some older nVidia GPUs, you need to compile it from source.

**Comment by sovanyio** [comment]
PyTorch can be built with AMD ROCm: https://github.com/pytorch/pytorch/issues/10657, trying to do this locally to see if it "just works" after using the locally built version.

**Comment by elixx** [comment]
@sovanyio any luck? should I bother trying, or think about #182 ?

**Comment by sovanyio** [comment]
This has taken a backseat for me since I was able to do a remote gpu with a laptop I had with nvidia. But there are some folks working on adding the AUR PKGBUILDs for ROCm here: https://github.com/RadeonOpenCompute/ROCm

**Comment by claudiuskastner** [comment]
If anyone is still interested in this issue:

Time passend, and pytorch has finally AMD ROCm support. It is still in beta; but here you go: https://github.com/pytorch/pytorch/releases/tag/v1.8.0

I'll give it a try these days.
