### ISSUE TITLE
 Solving environment:

### ISSUE THREAD

**Issue by happyif90** [alievk/avatarify#561]
good evening every one,
i need help on Solving environment: failed with initial frozen solve. Retrying with flexible solve.

is over 2 days now 

please i need help

**Comment by happyif90** [comment]
The following NEW packages will be INSTALLED:

  ca-certificates    pkgs/main/win-64::ca-certificates-2023.01.10-haa95532_0
  certifi            pkgs/main/win-64::certifi-2022.12.7-py37haa95532_0
  openssl            pkgs/main/win-64::openssl-1.1.1t-h2bbff1b_0
  pip                pkgs/main/win-64::pip-22.3.1-py37haa95532_0
  python             pkgs/main/win-64::python-3.7.16-h6244533_0
  setuptools         pkgs/main/win-64::setuptools-65.6.3-py37haa95532_0
  sqlite             pkgs/main/win-64::sqlite-3.41.1-h2bbff1b_0
  vc                 pkgs/main/win-64::vc-14.2-h21ff451_1
  vs2015_runtime     pkgs/main/win-64::vs2015_runtime-14.27.29016-h5e58377_2
  wheel              pkgs/main/win-64::wheel-0.38.4-py37haa95532_0
  wincertstore       pkgs/main/win-64::wincertstore-0.2-py37haa95532_2



Downloading and Extracting Packages

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate avatarify
#
# To deactivate an active environment, use
#
#     $ conda deactivate

Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: /

**Comment by JohanAR** [comment]
This problem has already been reported, check open issues please. I don't know if anyone has found a solution for it.

**Comment by abladefelix** [comment]
There’s already a solution available. It only seems most people here can’t implement the solution. 
you can reach me on royalhappy@gmail.com and I’ll assist. Maybe sometime I’ll do a PR

**Comment by Private090** [comment]
hi please i sent you a mail i still haven't figure it out yet

**Comment by abladefelix** [comment]
You need to make some modifications to the scripts first

**Comment by Private090** [comment]
Ok what are the modification

**Comment by Private090** [comment]
And I also sent you an email if you don't mind please

**Comment by abladefelix** [comment]
What’s your PC spec
OS Ram processors and GPU spec

**Comment by Private090** [comment]
Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz   2.50 GHz

**Comment by abladefelix** [comment]
I need the GPU (Graphics spec)

**Comment by Private090** [comment]
8GB ram
intel hd graphics 520

**Comment by abladefelix** [comment]
You can only run this on nvidia graphics

**Comment by Private090** [comment]
ok thank you

**Comment by Private090** [comment]
sorry the google colab alternative wont work for it as well

**Comment by abladefelix** [comment]
That will work

**Comment by abladefelix** [comment]
I thought you run that already

**Comment by happyif90** [comment]
> There’s already a solution available. It only seems most people here can’t implement the solution. you can reach me on [royalhappy@gmail.com](mailto:royalhappy@gmail.com) and I’ll assist. Maybe sometime I’ll do a PR

i need help,
i have 8gb video memory rtx 2070

**Comment by happyif90** [comment]
> There’s already a solution available. It only seems most people here can’t implement the solution. you can reach me on [royalhappy@gmail.com](mailto:royalhappy@gmail.com) and I’ll assist. Maybe sometime I’ll do a PR

please can tell us the step of the solution

**Comment by abladefelix** [comment]
From your reply it suggest you are in Nigeria. +2330542595112 WhatsApp me

**Comment by George152-max** [comment]
DM https://wa.me/+2348119663355
To fix this issue

**Comment by Private090** [comment]
Hi please I bought a nivida GeForce GTX 1650 will that run the program

**Comment by Private090** [comment]
Happyify90 have you figure it out yet

**Comment by happyif90** [comment]
> Happyify90 have you figure it out yet

yes

**Comment by happyif90** [comment]
here is my WhatsApp number +2347010663407

**Comment by happyif90** [comment]
> here is my WhatsApp number +2347010663407


here is my WhatsApp number +2347010663407

write me if you need help
