### ISSUE TITLE
old gpu support ?

### ISSUE THREAD

**Issue by Caidezel** [alievk/avatarify#58]
Hey, i'ù struggle with an old gpu... 

`    Found GPU0 GeForce GTX 660 Ti which is of cuda capability 3.0.
    PyTorch no longer supports this GPU because it is too old.
    The minimum cuda capability that we support is 3.5.`

`RuntimeError: CUDA error: no kernel image is available for execution on the device`

Any tips for me ? I tried to understand how envs stuff working...

**Comment by Caidezel** [comment]
Built on Windows 10.

**Comment by karfly** [comment]
Hi, @Caidezel.
Looks like you just have an old GPU which is not supported by PyTorch. I don't think it's possible to du anything about it.

**Comment by E3V3A** [comment]
According to other posts and links to pytorch repo issues, they're re-considering only using cuda 3.7 and above so it's compiled also for 3.0 which was the case for older pytroch. try downgrade as suggested here somwehere.
