### ISSUE TITLE
My Laptop has Intel(R) UHD Graphics 620! the picture is so slow and doesnt referesh for almost 30 seonds, making it basically unusuable. Any suggestions?

### ISSUE THREAD

**Issue by ambanna** [alievk/avatarify#63]

**Comment by geoffsee** [comment]
the intel 620 uhd is integrated gfx

**Comment by weltonrodrigo** [comment]
This model has very poor performance outside of CUDA. So you need a CUDA compatible GPU to get it working.

**Comment by ambanna** [comment]
Is there another model that would work on integrated graphics cards like this intel card?

**Comment by nt314p** [comment]
Short answer: no. Most neural networks require dedicated graphics cards to run and have good performance.

**Comment by Dobby009** [comment]
Am having the same issue my system uses Intel(R) UHD Graphics 620 which makes everything slow i try to download the NVidia GeForce, but it says not compactable with my windows please advise on what to do
