### ISSUE TITLE
Frame is None

### ISSUE THREAD

**Issue by SadatAnwar** [alievk/avatarify#64]
Fun idea, I wanted to give it a try. But looks like I am hitting some errors. 

```
Traceback (most recent call last):
  File "cam_fomm.py", line 228, in <module>
    ret, frame = cap.read()
  File "avatarify/videocaptureasync.py", line 40, in read
    frame = self.frame.copy()
AttributeError: 'NoneType' object has no attribute 'copy'
```
After running `run_mac.sh` I get uptil this stage, where I can also see the cameras light come on, but then after a few seconds I see this error and it stops.

Thanks

**Comment by glitch003** [comment]
I got it to work - 2 things.  I needed to change the CAMID in scripts/settings.sh and also add `time.sleep(10)` below the `self.cap = cv2.VideoCapture(self.src)` line in videocaptureasync.py.  However without GPU support it runs super slow.

**Comment by petermillgram** [comment]
What @glitch003 has suggested worked for me.

You can identify the right device with FFmpeg:

    ffmpeg -f avfoundation -list_devices true -i ""

And don’t forget to import the `time` module.

**Comment by bradandersen** [comment]
`conda install ffmpeg
ffmpeg -f avfoundation -list_devices true -i ""`
[AVFoundation input device @ 0x7fb6f1e1d0c0] AVFoundation video devices:
[AVFoundation input device @ 0x7fb6f1e1d0c0] [0] CamTwist
[AVFoundation input device @ 0x7fb6f1e1d0c0] [1] CamTwist (2VUY)
[AVFoundation input device @ 0x7fb6f1e1d0c0] [2] FaceTime HD Camera (Built-in)
[AVFoundation input device @ 0x7fb6f1e1d0c0] [3] Capture screen 0
[AVFoundation input device @ 0x7fb6f1e1d0c0] [4] Capture screen 1

Setting the CamID to 1 in scripts/settings.sh

I did not need import time nor time.sleep(10) on MacBook Pro
