### ISSUE TITLE
'NoneType' object has no attribute 'copy'

### ISSUE THREAD

**Issue by mikeyla** [alievk/avatarify#67]
Hi all,

I am on MacOS Catalina 10.15.4, which I think must be part of the reason this isn't working.

I installed everything, and when I ran run_mac.sh I got this error:

> 2020-04-19 00:43:57.994 python[29458:127273] DN: CamTwist (2VUY)
> 2020-04-19 00:43:57.994 python[29458:127273] MyPlugObjectHasProperty
> 2020-04-19 00:43:57.994 python[29458:127273] dulp
> 2020-04-19 00:43:57.994 python[29458:127273] tpni
> 2020-04-19 00:43:57.994 python[29458:127273] 0
> 2020-04-19 00:43:57.994 python[29458:127273] MyPlugObjectGetPropertyDataSize
> 2020-04-19 00:43:57.994 python[29458:127273] sel dnwo
> 2020-04-19 00:43:57.994 python[29458:127273] scope bolg
> 2020-04-19 00:43:57.994 python[29458:127273] elt 0
> Traceback (most recent call last):
>   File "cam_fomm.py", line 228, in <module>
>     ret, frame = cap.read()
>   File "/Users/mikemorgenstern/avatarify/videocaptureasync.py", line 40, in read
>     frame = self.frame.copy()
> AttributeError: 'NoneType' object has no attribute 'copy'
> 2020-04-19 00:44:01.319 python[29458:127273] MyPlugTeardown
> 2020-04-19 00:44:01.319 python[29458:127273] MyPlugTeardown

I've tried a bunch of things: Changing the OpenCV version to 4.1.2.30, messing around with Python settings, modifying the camera number. Nothing works. Any ideas?

**Comment by mikeyla** [comment]
I was able to get the code run by changing
>     # cap = cv2.VideoCapture(opt.cam)
>     cap = VideoCaptureAsync(opt.cam)

to
>     cap = cv2.VideoCapture(opt.cam)
>     # cap = VideoCaptureAsync(opt.cam)

and removing the line
>     cap.start()

, therefore disabling the asynchronous override...but it's incredibly slow. I'd like to get the asynchronous video capture back.

**Comment by OneWorld-github** [comment]
I had the same issue.  So I made the ammendments you suggested, however I got a different error message.  This is on windows 10 :-

```
AttributeError: 'NoneType' object has no attribute 'copy'

(avatarify) C:\avatarify>run_windows.bat

(avatarify) C:\avatarify>REM Web-camera device id

(avatarify) C:\avatarify>set CAMID=0

(avatarify) C:\avatarify>REM ################################################

(avatarify) C:\avatarify>REM Normally you don't want to change settings below

(avatarify) C:\avatarify>REM Conda environment name

(avatarify) C:\avatarify>set CONDA_ENV_NAME=avatarify
0: ./avatars\einstein.jpg
1: ./avatars\eminem.jpg
2: ./avatars\jobs.jpg
3: ./avatars\mona.jpg
4: ./avatars\obama.jpg
5: ./avatars\potter.jpg
6: ./avatars\ronaldo.png
7: ./avatars\schwarzenegger.png
load checkpoints..
cam_fomm.py:35: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  config = yaml.load(f)
[ WARN:0] global C:\projects\opencv-python\opencv\modules\videoio\src\cap_msmf.cpp (1113) SourceReaderCB::OnReadSample videoio(MSMF): OnReadSample() is called with error status: -2147024809
[ WARN:0] global C:\projects\opencv-python\opencv\modules\videoio\src\cap_msmf.cpp (1125) SourceReaderCB::OnReadSample videoio(MSMF): async ReadSample() call is failed with error status: -2147024809
[ WARN:1] global C:\projects\opencv-python\opencv\modules\videoio\src\cap_msmf.cpp (1159) CvCapture_MSMF::grabFrame videoio(MSMF): can't grab frame. Error: -2147024809
Cannot read from camera
[ WARN:1] global C:\projects\opencv-python\opencv\modules\videoio\src\cap_msmf.cpp (674) SourceReaderCB::~SourceReaderCB terminating async callback
```

If anyone has a solution for async, that would be great

**Comment by alievk** [comment]
Check out the last update. Should be fixed in https://github.com/alievk/avatarify/commit/179cd3ef43563d0b09eea7f8d589133910fac3a4
