### ISSUE TITLE
vox-adv-cpk.pth.tar quota exceeded on Google Drive

### ISSUE THREAD

**Issue by ztepler** [alievk/avatarify#7]
It is not possible to download file with model's weights, because provided in scripts/download_data.sh url is returning html page that says "Sorry, you can't view or download this file at this time."

**Comment by karfly** [comment]
Hi, @ztepler.
We've just noticed that and changed model's weights downloading to manual mode in the commit https://github.com/alievk/avatarify/commit/020cd6df50b5b17905482f49047ab43de984b70d.

**Comment by eyaler** [comment]
this worked for me:
https://medium.com/@acpanjan/download-google-drive-files-using-wget-3c2c025a8b99

**Comment by 121710316007** [comment]
> It is not possible to download file with model's weights, because provided in scripts/download_data.sh url is returning html page that says "Sorry, you can't view or download this file at this time."

so what is the alternate way to download the file? please help me to download the files.

**Comment by triplestar3** [comment]
i can not install my mini
