### ISSUE TITLE
Small change to handle non-Apt Linux distro installation

### ISSUE THREAD

**Issue by nmstoker** [alievk/avatarify#72]
Firstly, thank you so much for putting this together, it's great fun!

I use Arch and whilst I suspect many Arch users would figure this out, it would be worth looking at a small tweak in the install.sh so that it only ran the apt command for installing v4l2loopback-dkms on systems where apt is used by the distribution (and ideally used pacman or whatever other installers there are for order distros). I looked through the code in some detail beforehand so spotted this before I tried it and once that was switched, installation worked very smoothly.

https://github.com/alievk/avatarify/blob/e3120e50621f8679dfbfb313b76b54e4a323135b/scripts/install.sh#L6

On Arch you just need https://aur.archlinux.org/packages/v4l2loopback-dkms/ and the Linux Headers if you don't already have them installed.

Even if you don't want to build in support for others, it might be best it doesn't crash due to the command being absent, instead leaving it to the user in that case (I suspect more sophisticated users will generally want to know what's being installed anyway and can handle it themselves anyway)

**Comment by alievk** [comment]
Agreed. Then how that tweak would look like?

**Comment by nmstoker** [comment]
I'll see if I can suggest something specific later on, but there are a few ideas on approaches here:
https://askubuntu.com/questions/459402/how-to-know-if-the-running-platform-is-ubuntu-or-centos-with-help-of-a-bash-scri

A potentially simpler route than finding the distro would be to check for the installer (since there's some overlap: eg apt in Ubuntu + Debian, pacman on Arch + Mankato, yum on Redhat + Fedora)

**Comment by JohanAR** [comment]
Closing since Avatarify builds v4l2loopback from git now, and does not use apt
