### ISSUE TITLE
Does not run in ubutu

### ISSUE THREAD

**Issue by bgpantojar** [alievk/avatarify#73]
Hellow,

Just found this error

![Screenshot from 2020-04-19 16-05-15](https://user-images.githubusercontent.com/35929939/79689839-aa59d100-8257-11ea-8f67-6235a534580d.png)

The only problem is when I run the program

**Comment by alievk** [comment]
`uname -a`
`lsb_release -a` ?

**Comment by bgpantojar** [comment]
Linux eesdpc10Ubuntu 5.3.0-46-generic #38~18.04.1-Ubuntu SMP Tue Mar 31 04:17:56 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

LSB Version:	core-9.20170808ubuntu1-noarch:security-9.20170808ubuntu1-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.4 LTS
Release:	18.04
Codename:	bionic

**Comment by nunojusto** [comment]
The same error with me:

Linux hostname 5.3.0-46-generic #38~18.04.1-Ubuntu SMP Tue Mar 31 04:17:56 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.4 LTS
Release:	18.04
Codename:	bionic

**Comment by alievk** [comment]
Please check if this helps https://github.com/alievk/avatarify/issues/37#issuecomment-614503547

**Comment by nunojusto** [comment]
@alievk It worked using https://github.com/alievk/avatarify/issues/37#issuecomment-614503547 !!
Thank you

**Comment by bgpantojar** [comment]
it worked. Thanks!

**Comment by alievk** [comment]
There is a fix made recently in the official v4l2loopback repo, will add that to the master branch

**Comment by RoberMB** [comment]
Hi, I'm using Ubuntu as a vmware virtual machine and it's doesn't working too.

This is the error, when I execute run.sh script:

```
robermb@ubuntu:~/Downloads/avatarify$ bash run.sh 
Traceback (most recent call last):
  File "cam_fomm.py", line 3, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'
```

Info:
uname -a
```
Linux ubuntu 5.3.0-46-generic #38~18.04.1-Ubuntu SMP Tue Mar 31 04:17:56 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
```
lsb_release -a
```
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.4 LTS
Release:	18.04
Codename:	bionic
```

v4l2-ctl --list-devices
```
avatarify (platform:v4l2loopback-000):
	/dev/video9

VMware Virtual USB Video Device (usb-0000:02:03.0-1):
	/dev/video0
	/dev/video1
```

Any idea ?

Thanks

**Comment by alievk** [comment]
It should be activating conda environment with pre-installed packages including yaml. Did you alter `run.sh` ?

**Comment by RoberMB** [comment]
No, I've no altered run.sh script.
After the installation of Miniconda3, I executed the following commands:

```
$ eval "$(/home/robermb/miniconda3/bin/conda shell.bash hook)"
$ conda init
```

I could start again from some point ¿?

**Comment by RoberMB** [comment]
I started from a clean Ubuntu installation and in the step 3. Install avatarify I get the following errors:

(base) robermb@ubuntu:~/Downloads/avatarify$ ls -l /dev/video*
```
crw-rw----+ 1 root video 81, 0 Apr 22 00:59 /dev/video0
crw-rw----+ 1 root video 81, 1 Apr 22 00:59 /dev/video1
```

(base) robermb@ubuntu:~/Downloads/avatarify$ sudo bash scripts/install.sh
```
Submodule 'fomm' (https://github.com/alievk/first-order-model) registered for path 'fomm'
Submodule 'v4l2loopback' (https://github.com/umlaeute/v4l2loopback.git) registered for path 'v4l2loopback'
Cloning into '/home/robermb/Downloads/avatarify/fomm'...
Cloning into '/home/robermb/Downloads/avatarify/v4l2loopback'...
Submodule path 'fomm': checked out '6c1fbf39690130e2303bcecd3c6126c71cfacf85'
Submodule path 'v4l2loopback': checked out '72a32a67dee3a67dff76f565551907a2fc7e88e6'
--- Installing v4l2loopback (sudo privelege required)
Building v4l2-loopback driver...
make -C /lib/modules/`uname -r`/build M=/home/robermb/Downloads/avatarify/v4l2loopback modules
make[1]: Entering directory '/usr/src/linux-headers-5.3.0-46-generic'
  CC [M]  /home/robermb/Downloads/avatarify/v4l2loopback/v4l2loopback.o
  Building modules, stage 2.
  MODPOST 1 modules
  CC      /home/robermb/Downloads/avatarify/v4l2loopback/v4l2loopback.mod.o
  LD [M]  /home/robermb/Downloads/avatarify/v4l2loopback/v4l2loopback.ko
make[1]: Leaving directory '/usr/src/linux-headers-5.3.0-46-generic'
make -C /lib/modules/`uname -r`/build M=/home/robermb/Downloads/avatarify/v4l2loopback modules_install
make[1]: Entering directory '/usr/src/linux-headers-5.3.0-46-generic'
  INSTALL /home/robermb/Downloads/avatarify/v4l2loopback/v4l2loopback.ko
At main.c:160:
- SSL error:02001002:system library:fopen:No such file or directory: ../crypto/bio/bss_file.c:72
- SSL error:2006D080:BIO routines:BIO_new_file:no such file: ../crypto/bio/bss_file.c:79
sign-file: certs/signing_key.pem: No such file or directory
  DEPMOD  5.3.0-46-generic
Warning: modules_install: missing 'System.map' file. Skipping depmod.
make[1]: Leaving directory '/usr/src/linux-headers-5.3.0-46-generic'

SUCCESS (if you got 'SSL errors' above, you can safely ignore them)

scripts/install.sh: line 14: conda: command not found
scripts/install.sh: line 14: /etc/profile.d/conda.sh: No such file or directory
scripts/install.sh: line 15: conda: command not found
scripts/install.sh: line 16: conda: command not found
scripts/install.sh: line 18: pip: command not found
scripts/install.sh: line 21: pip: command not found
scripts/install.sh: line 22: pip: command not found
```


Not sure why the file **/etc/profile.d/conda.sh** is not exist ¿?
The installation of Miniconda3 contained the **command pip** but I can see the message "pip: command not found", so the user root has any problem with the PATH variable. I've fixed adding it to the PATH variable in the file .bashrc.

This is the line:
```
PATH=/home/robermb/miniconda3/bin:/home/robermb/miniconda3/condabin:$PATH
```

I'm still confusing about the file /etc/profile.d/conda.sh. I found the script conda.sh in the miniconda3 path installation, so I created a symbolic link to try:

```
root@ubuntu:/etc/profile.d# ln -s /home/robermb/miniconda3/etc/profile.d/conda.sh conda.sh
```

I've relaunched the installation of avatarify to try again. And finally it's working fine !!!

<img width="900" alt="screenshot_avatarify" src="https://user-images.githubusercontent.com/7288834/79959938-0f463e80-8485-11ea-9b73-4a6e59b3f914.png">

**Comment by RoberMB** [comment]
It works but so slow in my virtual machine. 
It's a really interesting project, @alievk congrats !

<img width="498" alt="screenshot2" src="https://user-images.githubusercontent.com/7288834/79961910-a1e7dd00-8487-11ea-9f79-5f00627a98b1.png">
