### ISSUE TITLE
Cameras don't appear when i execute run_windows.bat

### ISSUE THREAD

**Issue by i-mreed** [alievk/avatarify#744]
after installing everything and following instructions precisely. when i run run_windows.bat this appears, but no cameras appear

[1722825390.680134] Loading Predictor
[1722825396.300499] Trying camera with id 0
[1722825442.603774] Trying camera with id 1
[1722825446.125555] Trying camera with id 2

![Screenshot 2024-08-04 224503](https://github.com/user-attachments/assets/d8da63a7-6b45-49ca-bb5f-4c94973780da)

**Comment by JohanAR** [comment]
Your camera might not be compatible with OpenCV, which is what avatarify-python uses to capture video.

**Comment by Updatedme** [comment]
There are many factors that can cause this .
1. Camera may not be active 
2. Camera may be engaged by another application  

● Did you install using miniconda 3.8 or 3.7
Never the less, Among all you should do this 1st
From your Local disk . Locate the avatarify folder delete the cam file then go back to your miniconda prompt and then run_windows bat.  

Do that and let me know. 
If it does not work .

**Comment by i-mreed** [comment]
i figured out why it wasn't working. it wasn't compatible with the latest versions of opencv and the face-alignment modules, so i installed the older versions and it worked for me. thank you very much

**Comment by pricey24** [comment]
@Updatedme could you help me out with avatarify???
