### ISSUE TITLE
Warning: No faces were detected.

### ISSUE THREAD

**Issue by Suryansh5545** [alievk/avatarify#77]
As the title suggest . The avatarify is unable to detect my webcam that is PS3EYE . the webcam is showing up on zoom and skype but avatarify is unable to detect it.

MY SPEC:
CPU- Ryzen 5 3600
GPU- Rtx 2060S 8GB
Webcam- PS3EYE
OS- Windows 10

**Comment by Suryansh5545** [comment]
Can someone help me?

**Comment by alievk** [comment]
Did you try changing CAMID variable?

**Comment by Suryansh5545** [comment]
@alievk Yes from 0 to 9 . But still no luck

**Comment by alievk** [comment]
Are you sure the camera is not in use when you open avatarify?

**Comment by Suryansh5545** [comment]
@alievk Yes . When I open it the avatarify have the model ready and the cam is showing a gray screen and when I open obs and start then the avatarify model start rotating as it is unable to detect my ps3 eye

**Comment by Suryansh5545** [comment]
@alievk i tried it in Deepin and it worked finally after changing some CAMID . maybe as i cant see the camid in windows i might hav'ent put a wrong one . i will test again and tell you

**Comment by Suryansh5545** [comment]
@alievk is there a way that i can make my own model weight and also how can i or from where can i get more model weight(like the one you made of Elon Musk)

**Comment by alievk** [comment]
You don't need a particular model for an avatar, it generalizes on other images.

**Comment by Suryansh5545** [comment]
So how can I create the Elon musk face?

**Comment by alievk** [comment]
Just find Elon Musk face in the internet and it to `avatars` folder :)
