### ISSUE TITLE
VirtualCam not found

### ISSUE THREAD

**Issue by LetterC67** [alievk/avatarify#79]
After installing VirtualCam in the correct directory. I opened OBS and go to Tools but I didn't see VirtualCam. I opened Zoom but there was "OBS-Camera: in the camera list.

**Comment by Suryansh5545** [comment]
@LetterC67 VirtualCam is a option in OBS which will open this box
![47582820-797b3300-d923-11e8-99a0-10a50cedfd92](https://user-images.githubusercontent.com/34577232/79749261-83210380-832c-11ea-8262-84ad7dcc2a15.png)
and then you have to select the OBS-Camera

**Comment by LetterC67** [comment]
I have already installed VirtualCam plugins but I can't find it in Tools
![image](https://user-images.githubusercontent.com/53361407/79763889-d6a44900-834e-11ea-91dc-c1122dfec04c.png)

**Comment by alievk** [comment]
@LetterC67 

1. Remove OBS Studio and the plugin
2. Install OBS Studio
3. Install the plugin in the same directory as OBS Studio
4. Run OBS Studio and check Tools -> VirtualCam

**Comment by E3V3A** [comment]
@LetterC67  make sure you install VirtualCam in the same Program Folder as your OBS Studio. 
(i.e. 64bit vs 32bit versions.) Which did you install?

**Comment by JohanAR** [comment]
Since we haven't heard anything from @LetterC67 in almost a year, I'm going to assume that they either fixed their problem or moved on to other things.
