### ISSUE TITLE
Problems installing in Mac

### ISSUE THREAD

**Issue by tomasdiez** [alievk/avatarify#80]
I keep getting this:
Tomass-MacBook-Pro:avatarify tomasdiez$ bash scripts/install_mac.sh
scripts/install_mac.sh: line 5: conda: command not found
scripts/install_mac.sh: line 7: conda: command not found
scripts/install_mac.sh: line 7: /etc/profile.d/conda.sh: No such file or directory
scripts/install_mac.sh: line 8: conda: command not found
scripts/install_mac.sh: line 12: pip: command not found
scripts/install_mac.sh: line 14: pip: command not found
scripts/install_mac.sh: line 15: pip: command not found
scripts/install_mac.sh: line 16: pip: command not found
Tomass-MacBook-Pro:avatarify tomasdiez$ 

Apparently, the new version of JDK is not supporting the apt command

I am in MacOS 10.13.6

**Comment by centogram** [comment]
You will need to install conda first.  If you think you already have then you likely need to restart your shell as well.

**Comment by weltonrodrigo** [comment]
`brew cask install miniconda` will do it.

**Comment by harriskhurram** [comment]
On mac cannot install v4l or find its alternatives.

@tomasdiez `brew cask install miniconda` should do it.

**Comment by alievk** [comment]
@tomasdiez is the problem solved? If yes, please close the issue.

**Comment by tomasdiez** [comment]
Yes, finally it worked out by installing miniconda, thank you so much

It is laggy in Mac, this is my setup: MacBook Pro (Retina, 13-inch, Early 2015), 2,7 GHz Intel Core i5, 16 GB 1867 MHz DDR3, Intel Iris Graphics 6100 1536 MB

Thanks for the help
