### ISSUE TITLE
Intel Neural Compute Stick 2

### ISSUE THREAD

**Issue by LukaszGajowski** [alievk/avatarify#82]
Hi,

Will it be possible to run "avatarify" on "Intel Neural Compute Stick 2"?

Kind regards,
Lukasz

**Comment by weltonrodrigo** [comment]
To use the intel stick, you need to create an Open Vino version of the model. I don't know if that is possible for this model, as it is quite complicated and not traceable (changes its behaviour based on data).

It is certainly not compatible with ONNX (an open vino competitor) as you can see here https://github.com/AliaksandrSiarohin/first-order-model/issues/92

**Comment by weltonrodrigo** [comment]
Just for the sake of completeness, to generate an Open Vino version of your pytorch model, you should first generate an ONNX version (https://pytorch.org/tutorials/advanced/super_resolution_with_onnxruntime.html)  and them do the conversion https://docs.openvinotoolkit.org/2020.1/_docs_MO_DG_prepare_model_convert_model_Convert_Model_From_ONNX.html
