### ISSUE TITLE
Is it possible to use virtualCam as the initial webcam Avatarify uses?

### ISSUE THREAD

**Issue by andefraser** [alievk/avatarify#83]
I already use VirtualCam/OBS studio as my webcam, with a pro-grade camera. 

Is it possible to have this as the webcam input for Avatarify?

At the moment when I run `run_windows.bat` nothing happens - no error message and no windows appear.

**Comment by alievk** [comment]
It is possible. You have to find your virtual camera ID (integer number) by changing the CAMVID variable (see readme)

**Comment by andefraser** [comment]
OKay no worries, thanks for the response. 

I did try changing up to ID=4 but I'll keep testing other IDs

**Comment by alievk** [comment]
Some day we will make a convenient tool for camera selection :)
