### ISSUE TITLE
run.sh: line 17: 16681 Segmentation fault      python cam_fomm.py ...

### ISSUE THREAD

**Issue by phreaker0** [alievk/avatarify#86]
When I try to run it, I get an segmentation fault:

OS: Ubuntu 18.04.4 LTS
NVIDIA Driver Version: 440.64.00
CUDA Version: 10.2

```
$ bash run.sh
0: ./avatars/einstein.jpg
1: ./avatars/eminem.jpg
2: ./avatars/jobs.jpg
3: ./avatars/mona.jpg
4: ./avatars/obama.jpg
5: ./avatars/potter.jpg
6: ./avatars/ronaldo.png
7: ./avatars/schwarzenegger.png
load checkpoints..
QObject::moveToThread: Current thread (0x564b7a9ad500) is not the object's thread (0x564b7b04d950).
Cannot move to target thread (0x564b7a9ad500)

run.sh: line 17: 16681 Segmentation fault      python cam_fomm.py --config $CONFIG --checkpoint $CKPT --cam $CAMID --virt-cam $CAMID_VIRT --relative --adapt_scale $@
```

kernel log contains:
`python[16681]: segfault at 0 ip 00007fc6e3c9d1ce sp 00007ffdd37f57a0 error 4 in libxcb.so.1.1.0[7fc6e3c91000+26000]`

**Comment by heiner73** [comment]
I had the same issue because my qt environment was configured to breeze.
please try to run it with "LD_DEBUG=files" enabled and try with different desktop layouts

**Comment by phreaker0** [comment]
@heiner73 thank you! This was indeed the cause, the following files were loaded and therefore it failed. Switching desktop theme didn't work for me but temporarily moving the files somewhere else, so they can't be loaded, worked:
```
 ls -l /usr/lib/kde4/plugins/styles/*
-rw-r--r-- 1 root root 501480 Jul  4  2019 /usr/lib/kde4/plugins/styles/breeze.so
-rw-r--r-- 1 root root 813072 Jul  4  2019 /usr/lib/kde4/plugins/styles/oxygen.so

```
