### ISSUE TITLE
Runtime error when running run_windows.bat.

### ISSUE THREAD

**Issue by tengallontim** [alievk/avatarify#88]
Receiving the following message:
![image](https://user-images.githubusercontent.com/64040185/79792807-6375e500-8304-11ea-87eb-226d625eecb4.png)

**Comment by alievk** [comment]
This is not a full message

**Comment by tengallontim** [comment]
Here you go
![image](https://user-images.githubusercontent.com/64040185/79796308-32001800-830a-11ea-96b7-97a3f7bee344.png)

**Comment by tengallontim** [comment]
> This is not a full message. Please show until the foot.
@alievk here you go
![image](https://user-images.githubusercontent.com/64040185/79799173-ea2fbf80-830e-11ea-80ee-bdb9e59b6236.png)

**Comment by tengallontim** [comment]
@alievk Made it past that problem by deleting the checkpoints folder. Now having this issue: 
![image](https://user-images.githubusercontent.com/64040185/79807007-975e0400-831e-11ea-8e7c-5da6d2ac55dd.png)

**Comment by alievk** [comment]
Try choosing another camera (change `CAMID` var).

**Comment by tengallontim** [comment]
That worked, but then the program crashed when I tried pressing "f" to make the program readjust to my face. Had to completely reinstall, as running run_windows.bat simply brought up error messages. Upon reinstall, got this message. 
![image](https://user-images.githubusercontent.com/64040185/79897417-8f55a100-83be-11ea-9a32-d6368d543ad2.png)

**Comment by alievk** [comment]
Looks like wrong pillow version

Please show
```
conda activate avatarify
pip show pillow
```

**Comment by opytel** [comment]
> Looks like wrong pillow version
> 
> Please show
>
> conda activate avatarify
> pip show pillow
> ```

I have exact the same error as OP. Please see the picture.

Weird thing is, when i installed it 2 days ago, everything worked. Today i updated and it broke.

Tried some things, including complete clean reinstall (incl. conda; i removed all files associated to conda and avatarify before
![pillow_error](https://user-images.githubusercontent.com/34780946/79976770-72dc6600-849d-11ea-89ec-56169e9a7385.PNG)
)

**Comment by opytel** [comment]
i have a workaround fix:

...\PIL\ __init__.py 

i added on line 22:
`PILLOW_VERSION = __version__ = _version.__version__`

**Comment by alievk** [comment]
Fixed package version https://github.com/alievk/avatarify/issues/105

**Comment by tengallontim** [comment]
@alievk @opytel Seems to work. Can't activate the camera on Zoom. I tried switching the camera to OBS - still nothing. 
![image](https://user-images.githubusercontent.com/64040185/80027264-55f16400-8498-11ea-8e91-eb4d15983633.png)

**Comment by tengallontim** [comment]
Seems to work. Can't activate the camera on Zoom. I tried switching the camera to OBS - still nothing.
![image](https://user-images.githubusercontent.com/64040185/80027436-9cdf5980-8498-11ea-91fa-2db40c43b5d3.png)

**Comment by Adesina0** [comment]
please it doesnt pop up camera  when running run_windows.bat. 
![Screenshot (3)](https://user-images.githubusercontent.com/115165085/194745932-221ffd85-cd12-4825-a4ec-b0d8dd30d0c5.png)
