### ISSUE TITLE
Very slow performance on high sierra

### ISSUE THREAD

**Issue by cocodr1lo** [alievk/avatarify#9]
Hi! Awesome work. I was finally able to install all the dependencies and run the application, but the avatar changes so slowly that it almost doesn't change at all. I have a Macbook Pro 2012 with SSD disk. Is there any way to make it work faster?

Thanks!

**Comment by xechehot** [comment]
The same thing with me. The avarify worked as a slideshow. I have Macbook Pro 2017 with SSD (Mojave OS), Radeon Pro 555 2 ГБ and Intel HD Graphics 630 1536 МБ. Is it because of poor GPU?

**Comment by xechehot** [comment]
Is it possible to use remote server with CUDA?

**Comment by alievk** [comment]
Running real-time on machines without CUDA-enabled GPUs requires dramatic neural network optimization under the hood, like quantization. This is not what could be easily done, but I think this is just a matter of time.

**Comment by alievk** [comment]
> The same thing with me. The avarify worked as a slideshow. I have Macbook Pro 2017 with SSD (Mojave OS), Radeon Pro 555 2 ГБ and Intel HD Graphics 630 1536 МБ. Is it because of poor GPU?

You need a CUDA-enabled GPU, Radeon cards doesn't support CUDA.

**Comment by alievk** [comment]
> Is it possible to use remote server with GPU and CUDA?

It is possible, but expect a large latency due to data transfer overhead.

**Comment by YubinXie** [comment]
It is also very slow on my 2018-15inch MacBook pro. It is too slow that it is not functioning in the meeting...

**Comment by YubinXie** [comment]
One suggestion is to reduce the network size.

**Comment by Alex-Yi-AskNicely** [comment]
![image](https://user-images.githubusercontent.com/52642817/79081360-c994c200-7d70-11ea-8840-754c37ed33e1.png)

Excellent work! If it has a better performance in my Macbook Pro would be awesome.

**Comment by alievk** [comment]
Similar issue https://github.com/alievk/avatarify/issues/16

**Comment by alievk** [comment]
Now you can run on Mac with a good speed using [Google Colab](https://colab.research.google.com/github/alievk/avatarify/blob/master/avatarify.ipynb)
