### ISSUE TITLE
Losing keyboard console return in Windows 10 version

### ISSUE THREAD

**Issue by rrabelo1** [alievk/avatarify#91]
Dear,

after start the run_windows.bat script, everything run, but I dont have the keyboard feedback from the console and I cant configure the application on run time (for example, changing the avatar or adjust the parameters). My screen shows those warnings

![image](https://user-images.githubusercontent.com/13523437/79805201-ff6f1300-833b-11ea-92dd-e3f50e4bcb5e.png)

**Comment by E3V3A** [comment]
I have the same issue but the keyboard controls works inside the video window. 
however, there is no pretty exit. Hitting `ctrl-C` makes the Python console just hang...

**Comment by alievk** [comment]
Esc doesn't work?

**Comment by E3V3A** [comment]
> Esc doesn't work?

We didn't know `ESC` would work. Where is that written? Usually you exit anything CL with `CTRL-C`... Either way, it should not hang when you do CTRL-C.

**Comment by alievk** [comment]
It's written in the readme.

It doesn't exit gracefully because there is another tread running with camera reading loop. Seems a minor issue to me, but feel free to make a PR.
