### ISSUE TITLE
 Improvement: README for configuring OBS Studio

### ISSUE THREAD

**Issue by E3V3A** [alievk/avatarify#95]
I'll just post these screen shots to clarify the short comings of the README.

---

Step 1

![obs32_2020-04-21_01-30-47](https://user-images.githubusercontent.com/194392/79813751-2ef63d80-8385-11ea-90c4-6b867e563eab.png)

step 2

![obs32_2020-04-21_01-31-19](https://user-images.githubusercontent.com/194392/79813754-2f8ed400-8385-11ea-91bf-88418d0e4b70.png)

step 3

![obs32_2020-04-21_01-32-06](https://user-images.githubusercontent.com/194392/79813755-30276a80-8385-11ea-82cf-571eb80e6f86.png)

step 4

![obs32_2020-04-21_01-34-28](https://user-images.githubusercontent.com/194392/79813756-30276a80-8385-11ea-9b91-1c5792ccc92d.png)

**Comment by alievk** [comment]
I will be recording Windows installation tutorial after clarifying some questions.
