### ISSUE TITLE
Virtual camera Skype/zoom

### ISSUE THREAD

**Issue by stephane92400** [alievk/avatarify#97]
Hello, I just tried on Skype and zoom when avatary is launched, Skype and zoom no longer see the cameras (impossible to access the camera).  Is there a solution..?  Thank you

**Comment by stephane92400** [comment]
Does it still work with skype and zoom?
Everything starts correctly, but when I launch one of the two software, impossible to connect to the camera (this is only done when avatary (with virtualcam) is launched)

**Comment by DarkWayfarer** [comment]
@stephane92400 Hey. You did install OBS and virtual cam. After config him you saw 4 virtual cam.

**Comment by DarkWayfarer** [comment]
![image](https://user-images.githubusercontent.com/16899697/80005167-8cfe5e80-8506-11ea-91ff-61e7644f27a9.png)

**Comment by stephane92400** [comment]
I can see obs cal but when avatary is launched it is impossible to use the camera either this one or the computer one

**Comment by DarkWayfarer** [comment]
@stephane92400 sory, my english is bad. I can misunderstand you. 

If you want to see the original image. Click on the avatar and press 0.

**Comment by stephane92400** [comment]
Skype and zoom detect the virtual camera.  So when the program is launched, the cameras no longer work. Are you still working on Skype or zoom?

**Comment by stephane92400** [comment]
When avatarify launch, I see the errors(zoom) 
Unable to start video Unable to start the video camera.  Please select another video camera in the settings

**Comment by stephane92400** [comment]
Sorry tha work Skype 8.16.04

**Comment by alievk** [comment]
Zoom and Skype still support Avatarify. Try:
- close Zoom
- open Avatarify
- open Zoom -> Settings -> Video -> Camera -> OBS-Camera

**Comment by E3V3A** [comment]
^^ Make sure you have enabled the *OBS Studio (32-bit)* `Tool  >>  Virtual Cam`.

**Comment by stephane92400** [comment]
It's work Thanks you

**Comment by E3V3A** [comment]
@stephane92400 Please close this issue if fixed. Thanks!
